content/6_Advanced/Interactive.mdx
content/ordering.ts

Should I add more problems? I could totally just refer the reader to https://oj.uz/problems?search=&type=INTERACTIVE though...

Started the interactive module

---

content/4_Gold/Divis.mdx
src/utils/algolia-queries.ts

Closes https://github.com/cpinitiative/usaco-guide/issues/239

Number of divisors code + explanation

---

solutions/CSES Flight Discount.mdx

Update CSES Flight Discount.mdx

---

content/4_Gold/LIS.mdx

I'll finish the last section later.

Dp lis java support

---

content/2_Bronze/Intro_Sorting.mdx
content/3_Silver/Flood_Fill.mdx

fixing some format stuff + adding a resource for sorting

Ff java support

---

content/4_Gold/All_Roots.mdx
content/4_Gold/Divis.mdx
content/4_Gold/Modular.mdx
content/5_Plat/Geo_Pri.mdx
content/6_Advanced/Eulerian_Tours.mdx

Closes https://github.com/cpinitiative/usaco-guide/issues/225
Also, the Balkan problems were meant for a different branch/PR oops...

Gold descriptions

---

content/1_General/Contributing.mdx
src/components/MarkdownLayout/TableOfContents/TableOfContentsBlock.tsx
src/components/MarkdownLayout/TableOfContents/TableOfContentsSidebar.tsx
src/components/MarkdownLayout/TableOfContents/getGithubUrl.tsx
src/models/module.ts
src/models/solution.ts
src/templates/moduleTemplate.tsx
src/templates/solutionTemplate.tsx
src/utils/utils.ts

Github Links

---

content/4_Gold/Tree_Euler.mdx
solutions/USACO feb19-cowland.mdx

Finished cowland solution, includes C++ implementation.

Add non-HLD cowland solution (as the section implies)

---

USACO feb17-lemonade.mdx
content/3_Silver/Greedy.mdx

For USACO silver lemonade line. I also need someone to tell me how to find the problem ID.

Create USACO feb17-lemonade.mdx

---

content/4_Gold/All_Roots.mdx
content/5_Plat/Seg_Ext.mdx
content/6_Advanced/Eulerian_Tours.mdx
solutions/Balkan 17-cityattractions.mdx

Also linked to BkOI 2016 Acrobat's solution

BkOI 2017 Cityattractions solution

---

src/context/FirebaseContext.tsx
src/context/UserDataContext/UserDataContext.tsx
src/pages/dashboard.tsx

Closes https://github.com/cpinitiative/usaco-guide/issues/174
Not sure how well this works yet though

Count online users

---

USACO feb17-maxcross.mdx
content/3_Silver/Prefix_Sums.mdx

Added a java implementation. Please let me know how to add the problem ID as I don't know that.

Create USACO feb17-maxcross.mdx

---

solutions/USACO jan17-hoof-paper-scissors.mdx

Update USACO jan17-hoof-paper-scissors.mdx

---

content/5_Plat/2DRQ.mdx
content/5_Plat/Slope.mdx
content/5_Plat/Sqrt.mdx
content/5_Plat/String_Search.mdx
content/6_Advanced/Interactive.mdx
content/6_Advanced/SPneg.mdx
solutions/APIO 16-gap.mdx
solutions/APIO 17-koala.mdx
solutions/APIO 17-merchant.mdx
solutions/APIO 19-bridges.mdx

- 16 Gap (Interactive module)
- 17 Merchant (SPNeg module)
- 17 Koala (Interactive module)
- 19 Bridges (Sqrt module)

Editorials for 4 APIO problems

---

content/3_Silver/2P.mdx

- CEOI 2010 Tower
- SAPO 2018 Stadium

Two harder 2-pointer problems

---

package.json
src/pages/liveupdate.tsx
yarn.lock

Added lazily-loaded monaco editor with lazy-loading into /liveupdate. Still need to connect it to the renderer. Closed #326 as I had to re-create my fork and use separate branches on my local dev environment.

Add monaco editor

---

content/5_Plat/DC-DP.mdx

Google Translate was insanely confusing for me...

content: add english statement for JOI Bubblesort

---

content/5_Plat/String_Search.mdx

not entirely sure if this is a good problem oops, but better than not having it...?

content: add POI 06-Periods to String Searching

---

solutions/USACO feb17-maxcross.mdx

Adds a C++ Implementation to Implementation to the problem "Why Did the
Cow Cross the Road II," from the Silver Context in February 2017 from
the Prefix Sums section.

content: add cpp implementation to feb17-maxcross

---

content/3_Silver/Intro_Tree.mdx
solutions/POI 14-hot.mdx

For https://github.com/cpinitiative/usaco-guide/issues/302 (doesn't close it though)

Editorial for POI Hotels

---

content/5_Plat/CHT.mdx

lol I haven't actually solved this problem yet so I'm not sure if the solution / the difficulty is correct XD

content: add CEOI 09-Harbingers

---

content/2_Bronze/Intro_Greedy.mdx

I think it's fine now after 8f30f291473d1e42ef9666aa1df8844e980da978 ?
Also closes #314

content: remove incomplete section from bronze greedy

---

content/3_Silver/2P.mdx
solutions/SAPO 18-stadium.mdx

Closes https://github.com/cpinitiative/usaco-guide/issues/376

SAPO stadium editorial

---

content/4_Gold/PURS.mdx

Moved "Note that if it were not the case that all elements of the input array were distinct, then this code would be incorrect since `Tree<int>` would remove duplicates. Instead, we would use an indexed set of pairs (`Tree<pair<int,int>>`), where the first element of each pair would denote the value while the second would denote the position of the value in the array." to C++ section since it's not relevant to the Java solution of Inversion Counting.

moved description to C++ section

---

content/4_Gold/Knapsack_DP.mdx

note that this video appears in Intro to DP as well (I think that's fine...)

content: add a dp video

---

content/4_Gold/Intro_DP.mdx

content: add some dp videos

---

content/2_Bronze/Intro_Sets.mdx

Remove c++ content when another language is selected.
- https://usaco.guide/bronze/intro-sets#inserting--deleting-keys-while-iterating

Content: Add language tags 

---

content/2_Bronze/Complete_Rec.mdx

- [https://usaco.guide/bronze/complete-rec#solution---apple-division](https://usaco.guide/bronze/complete-rec#solution---apple-division)

content: add python solutions to apple division 

---

content/2_Bronze/Complete_Rec.mdx

Sorry for 2nd pull req, wasn't sure how to add to my other one

Added Java implementation for backtracking in Chessboard and Queens

---

content/1_General/Intro.mdx

- https://usaco.guide/general/intro

Add language tags

---

solutions/USACO open16-diamond.mdx

Sorry for the misspelled commit message. Python is not an undergarment.

Added python code for open16-diamond

---

solutions/USACO dec16-blockgame.mdx

- https://usaco-guide-git-dliu426-patch-7.cpinitiative.vercel.app/solutions/usaco-664

Add python solution for Block Game

---

solutions/Baltic 16-swap.mdx

This was a kinda weird problem, so my editorial might be a bit confusing oops. Also, I'm not quite sure how to describe the memory optimizations. (Are they even possible in not-C/C++?)

DP solution for BOI Swap

---

content/3_Silver/Binary_Search_Ans.mdx

Add python code for Binary_Search_Ans.mdx

---

content/4_Gold/DSU.mdx

Add [Ski Course Rating](http://www.usaco.org/index.php?page=viewproblem2&cpid=382)

Add problem to DSU module

---

content/3_Silver/Binary_Search_Sorted.mdx

OK. Hopefully it's good now. (BTW It doesnt actually overlap with the other pull req; his was in the bsearch_ans section)

Binary search sorted section -- better java/py support

---

content/5_Plat/Sqrt.mdx

Not sure about the difficulty though

Some additional sqrt problems

---

content/4_Gold/String_Hashing.mdx
solutions/USACO jan16-lightsout.mdx

Appropriate because it's in the hashing section

Lightsout solution with hashing

---

content/3_Silver/Greedy.mdx
solutions/CSES Stick Divisions.mdx

Add Stick Divisions solution

---

content/4_Gold/Intro_DP.mdx

- https://usaco-guide-git-dliu426-patch-11.cpinitiative.vercel.app/gold/intro-dp#harder-usaco

Add cowmbat to problem list

---

solutions/CSES Flight Discount.mdx

Add the alternative solution for CSES Flight Discount described in #416 
The code is taken from my CSES submission [here](https://cses.fi/paste/25edeb9eb3f461c413cd6e/).
Let me know if there's anything I should change. This is my first PR so I've probably messed something up or forgotten to do something.

Add alternative solution to CSES Flight Discount

---

content/3_Silver/DFS.mdx

not sure how to deal with language-specific issues. Should I even mention stackoverflow for c++?

Dfs stack size

---

content/4_Gold/DP_NT.txt
content/4_Gold/Knapsack_DP.mdx
solutions/POI 04-mak.mdx

Closes https://github.com/cpinitiative/usaco-guide/issues/383

POI Maximal editorial

---

content/3_Silver/Intro_Tree.mdx
solutions/CSES Tree Distances II.mdx

Closes https://github.com/cpinitiative/usaco-guide/issues/447

CSES Tree Distances II solution

---

content/4_Gold/Sliding.mdx
solutions/APIO 15-bridge.mdx

Addressing the recent feedback email

Editorial for APIO 2015 Palembang Bridges

---

content/4_Gold/BFS.mdx

Closes https://github.com/cpinitiative/usaco-guide/issues/456

Straightforward 0/1 BFS example

---

content/4_Gold/Intro_DP.mdx

seems fine if it's long since we starred one of them (& have a video)?

content: remove incomplete section from intro to dp module

---

content/5_Plat/2DRQ.mdx
content/5_Plat/RURQ.mdx

Got rid of the `<IncompleteSection/>` tags. I just linked to an implementation of a 2D segtree

Implementations + resources for 2DRQ module

---

src/components/Classes/AssignmentProgressView.tsx
src/components/Dashboard/ActiveItems.tsx
src/components/markdown/ProblemsList/ProblemStatusCheckbox.tsx
src/models/problem.ts
src/pages/dashboard.tsx
src/templates/syllabusTemplate.tsx

> https://forum.usaco.guide/t/review-markings-for-problems/164
Problems to "review" appear on dashboard, included in solved problems count.

"review" option

---

content/1_General/Debugging_General.mdx
content/1_General/Debugging_Lang.mdx

Added another bullet point for debugging wrong answer and other forms of not accepted programs.

Added another way to debug.

---

content/4_Gold/All_Roots.mdx
content/4_Gold/MST.mdx
content/5_Plat/Bitsets.mdx
content/5_Plat/Mat_Exp.mdx
content/6_Advanced/DP_More.mdx
content/6_Advanced/DP_SOS.mdx
content/6_Advanced/FFT.mdx
content/6_Advanced/Persistent.mdx
content/6_Advanced/String_Search.mdx

The difficulty might be a bit off for some of these

Various problems

---

content/5_Plat/Slope.mdx
content/6_Advanced/Slope.mdx

oops I'm not sure how to make graphs; are these alright or should I change them?

content: add diagrams for buy low sell high

---

content/1_General/Contributing.mdx
solutions/USACO jan17-cow-dance-show.mdx
solutions/USACO open19-500.mdx

Added a concrete solution for the math approach.

Update USACO open19-500.mdx

---

src/components/markdown/ProblemsList/ProblemsList.tsx

#386 smth like this, but idk how to get a link to appear to one side of the table if hovered over ...

+ extra col for URL

---

solutions/CF Orac-LCM.mdx

In my opinion, the new example code is much easier to read

Clean up example code

---

content/4_Gold/MST.mdx

DSU should be initialized with size n+1 instead of n because its 1 indexed

Edit solution to Road Reparation

---

solutions/CSES Tree Distances I.mdx

Update CSES Tree Distances I.mdx

---

content/2_Bronze/Intro_Complete.mdx
solutions/USACO dec19-gymnastics.mdx

May not be working, wasn't able to test the site locally for some reason.

Add Java solution to Bronze Dec 2019 Cow Gymnastics

---

solutions/APIO 17-rainbow.mdx

oops I have no idea what planar graphs are so idk if this link is good

add link to planar graph

---

src/components/Dashboard/DashboardProgress.tsx
src/components/MarkdownLayout/MarkdownLayout.tsx
src/components/MarkdownLayout/TableOfContents/TableOfContentsBlock.tsx
src/templates/syllabusTemplate.tsx

hide TOC when length <= 1

---

solutions/CSES List Removals.mdx

Add a segment tree-based solution.

Add a fourth solution for List Removals

---

content/4_Gold/Divis.mdx

Thanks to Jerry for catching this

Add language section for cpp specific exercise

---

src/components/ContactUsSlideover/ContactUsSlideover.tsx
src/components/MarkdownLayout/ModuleFeedback.tsx
src/components/markdown/IncompleteSection.tsx

- changed module incomplete message to encourage PR's rather than emails
- updated module feedback to link to USACO Forum only (instead of having the form)
- updated contact us slideover to include a banner pointing to USACO Forum (but the email form is still there)

Redirect emails to Forum

---

content/2_Bronze/Intro_DS.mdx

Relevant change (for C++ only):

cleanup bronze DS; add strings section

---

content/1_General/Debugging_Lang.mdx

Hi everyone!
I have added an interactive Java testing script. To use it, you need to put the script, the `.java` file and the input and output files (`1.in`, `1.out`, etc.) in one directory.
Feel free to reach out if you have any changes you would like me to make.
Thanks!

Add a Java testing script

---

content/1_General/Running_Code_Locally.mdx

Added installation instructions for Linux and macOS. Added more instructions for Windows.

Add installation instructions for Java

---

content/1_General/Running_Code_Locally.mdx

Accidentally used the Windows command not found error for Mac.

Change the Mac command not found error

---

solutions/CSES Concert Tickets .mdx
solutions/CSES Concert Tickets.mdx
solutions/CSES Traffic Lights.mdx

I added a solution for this problem (https://usaco.guide/silver/intro-ordered#problem-https://cses.fi/problemset/task/1163). Hope it might help.

cses concert tickets + traffic lights sol

---

solutions/USACO dec20-stuck-silver.mdx

Reverts cpinitiative/usaco-guide#552

Revert "Got rid of unnecessary lines"

---

solutions/CSES Concert Tickets.mdx

Sorry I forgot to redefine the endl after clearing the macros

Add line #define endl "\n" to make it optimized

---

solutions/CSES Towers.mdx

I added the second implementation using multiset to this problem.

Added another implementation for CSES Towers

---

gatsby-browser.tsx
src/components/MarkdownLayout/MarkdownLayout.tsx
src/context/UserDataContext/UserDataContext.tsx
src/context/UserDataContext/properties/userLang.ts

Share url + lang

---

content/2_Bronze/Intro_Graphs.mdx
solutions/USACO open19-milk-factory.mdx

I used DFS in this sol. The official sol doesn't use DFS.

Create USACO open19 milk-factory.mdx

---

content/1_General/Choosing_Lang.mdx
gatsby-node.ts
solutions/USACO jan17-promote.mdx
src/components/Dashboard/ModuleLink.tsx
src/components/MarkdownLayout/MarkdownLayout.tsx
src/components/MarkdownLayout/ModuleHeaders.tsx
src/components/markdown/ProblemsList/DivisionList.tsx
src/context/UserDataContext/UserDataContext.tsx
src/context/UserDataContext/properties/divisionTableQuery.ts
src/models/module.ts
src/templates/moduleTemplate.tsx
src/templates/syllabusTemplate.tsx
src/utils/utils.ts

also Jan promotion counting, change default division value

display modification times on syllabus for recently modified files

---

solutions/USACO dec15-breed-counting.mdx
solutions/USACO jan17-hoof-paper-scissors.mdx

Just added a Java solution for Breed Counting (bcount), and Hooves Paper Scissors (hps). (Don't worry, I tested it)

Add Java solutions for multiple problems

---

solutions/CSES Increasing Subsequence II.mdx

If someone could tell me how to make edits in a pull request that would be great lol

CSES Increasing Subsequences II Revision II

---

content/1_General/Resources_CP.mdx

added youtube channel section, cp3, visualgo (from cp4),  fixed punctuation

Updated resources

---

content/6_Advanced/Lagrange.mdx
solutions/JOI 20-joitter.mdx

(Also, added BOI 19-tennis to Aliens Trick)

JOI 20-joitter explanation + code without templates

---

content/1_General/Resources_CP.mdx

last patch rolled back after merge after a mistaken commit on my end... this should restore it.

Resources patch

---

content/4_Gold/Intro_DP.mdx

I found a  problemset with classical dp problems. I think it is a suitable contest for begginers. You decide if it is starred or not.

added dp begginer problemset

---

content/2_Bronze/Time_Comp.mdx

I thought this video was kinda cool, but I'm not sure where to put it? hopefully this is fine (I left a comment stating that it's optional)

content: add p vs np video

---

content/1_General/Contributing.mdx
solutions/CF Orac-LCM.mdx

Java solution + explanation of alternate solution

Alternate solution to CF Orac-LCM

---

content/1_General/IO.mdx
content/1_General/Resources_CP.mdx
content/3_Silver/Func_Graphs.mdx

Just added some java support to this section

Functional Graphs and IO

---

content/3_Silver/2P.mdx
solutions/CEOI 10-tower.mdx

C++ solution for CEOI 2010 - A Huge Tower

add_cpp_solution

---

solutions/CF Cellular Network.mdx

I'm thinking of making Cellular Network the challenge problem for Binary Search on Sorted Array for CPI clubs.

content: add binary search impl for cellular network

---

content/1_General/Cpp_Command.mdx

More aligned with the spec and some pointers and tips. Also removed some potentially dangerous advice and other unorthodox tips in favor of best practices.

Fixes and Updates for C++ Command Line Module

---

solutions/USACO jan16-subseq-summing-to-sevens.mdx

The solution passes all test cases and is more straight forward than the current solution. 
It uses simpler data structures and eliminates redundant writes to the prefix sum array.
Hope this helps!

Faster, more space efficient and simpler solution to "Subsequences Summing to Sevens"

---

content/2_Bronze/Rect_Geo.mdx
solutions/USACO dec16-square-pasture.mdx

I added a C++ solution to Square Pasture (2016 dec bronze).

Square Pasture 2016 December Bronze

---

content/2_Bronze/Intro_Greedy.mdx
solutions/USACO jan17-cow-tipping.mdx
solutions/USACO jan18-out-of-place.mdx

I added C++ Solutions to Cow Tipping (January 2017 Bronze) and Out of Place (January 2018 Bronze).

Cow Tipping and Out of Place C++ Solutions

---

content/1_General/Cpp_Command.mdx
content/1_General/Running_Code_Locally.mdx

This includes how to get the header bits/stdc++ on windows, as well as the different compiler options available. This was made with the help of @wastingtime#1534

Add some Windows-specific information for Running Code Locally

---

content/3_Silver/Greedy.mdx
solutions/CSES Ferris Wheel.mdx

Added alternate C++ implementation, wrote brief explanation for both solutions, added problem tags

Modifying solution for Ferris Wheel

---

content/4_Gold/PURS.mdx
content/5_Plat/DC-SRQ.mdx
content/5_Plat/Sqrt.mdx

cses problem rename

---

solutions/CSES Ordered Coin Change.mdx

I added the Codeforces Unofficial Editorial for this problem as the editorial uses another approach which could be useful. I also add some explanation for Michael Cao's solution.

Added #2 solution for CSES - Coin Combinations II

---

solutions/USACO feb16-milk-pails.mdx

https://github.com/cpinitiative/usaco-guide/issues/683

Milk Pails: Add java bfs solution & clean up solution file

---

content/2_Bronze/Intro_Complete.mdx
content/3_Silver/DFS.mdx
solutions/USACO feb16-load-bronze.mdx
solutions/USACO open16-closing-the-farm.mdx

I added a C++ solution to Load Balancing (Feb 2016 Bronze) and a C++ solution using dfs (the official solution uses dsu) to Closing the Farm (Open 2016 Silver).

Load Balancing and Closing the Farm C++ Solutions

---

solutions/USACO jan17-balanced-photo.mdx

quick fixes - balanced photos

---

src/components/markdown/ProblemsList/ProblemsList.tsx
src/context/UserDataContext/UserDataContext.tsx

not sure what to change so that page doesn't scroll when URL is clicked

feat: copy url to clipboard

---

content/3_Silver/DFS.mdx
content/3_Silver/Intro_Tree.mdx

Since the solution involves finding a spanning tree.

move even outdegree edges to tree

---

content/3_Silver/Flood_Fill.mdx
solutions/USACO jan16-build-gates.mdx

I added a C++ solution to Build Gates (January 2016 Silver). 
I also had a question about the [official solution](http://www.usaco.org/current/data/sol_gates_silver_jan16.html), they only made the farm 2005 by 2005 and started at (1002, 1002), but they also doubled the length of the fence. Wouldn't this go out of bounds for an input of 1000 Ns?

Build Gates C++ Solution

---

content/3_Silver/Prefix_Sums.mdx
content/5_Plat/HLD.mdx

haybale stacking, grass planting

---

content/3_Silver/Bipartite.mdx
content/3_Silver/DFS.mdx
content/3_Silver/Flood_Fill.mdx
content/3_Silver/Intro_Tree.mdx
solutions/POI 17-sab.mdx

Add / modify tags, move two probs from DFS to flood fill, fix POI Sabotage sol

Silver Graphs

---

content/3_Silver/Flood_Fill.mdx

Flood Fill - reorder, change intro

---

solutions/CF Cellular Network.mdx

I added a C++ solution using sets to CF Cellular Network. #729

Cellular Network C++ Solution Using Sets

---

gatsby-config.ts
gatsby-node.ts
package.json
yarn.lock

if module / solution URL changes, add redirects to the frontmatter:
```
title: blah blah blah
redirects:
- /my/old/url
- /another/old/url
```

add redirects support

---

content/3_Silver/Greedy.mdx

Studying Algorithms

---

content/2_Bronze/Complete_Rec.mdx
content/2_Bronze/Intro_Bitwise.mdx
content/3_Silver/Binary_Search.mdx
content/3_Silver/Greedy.mdx
content/ordering.ts

- move bitwise to Bronze (doesn't belong, but it seems really random for it to be in the middle of silver, and at least it's mentioned in one of the Bronze modules). 
- Move binsearch into sorting section.

sorting & searching

---

content/2_Bronze/Intro_Greedy.mdx
content/3_Silver/Binary_Search.mdx
content/3_Silver/Func_Graphs.mdx
content/3_Silver/Greedy_Sorting.mdx
content/4_Gold/All_Roots.mdx
content/4_Gold/BFS.mdx
content/4_Gold/DSU.mdx
content/4_Gold/Faster_Hash.mdx
content/4_Gold/Intro_DP.mdx
content/4_Gold/Knapsack_DP.mdx
content/4_Gold/Stacks.mdx
content/5_Plat/2DRQ.mdx
content/5_Plat/DC-DP.mdx
content/5_Plat/Mat_Exp.mdx
content/5_Plat/Range_Sweep.mdx
content/5_Plat/Sqrt.mdx
content/5_Plat/Sweep_Line.mdx
content/6_Advanced/BCC_2CC.mdx
content/6_Advanced/DP_More.mdx
content/6_Advanced/FFT-ext.mdx
content/6_Advanced/Springboards.mdx
content/6_Advanced/Suffix_Array.mdx
content/ordering.ts
gatsby-node.ts
solutions/1_extra_usaco_probs.ts
src/components/markdown/ProblemsList/DivisionList.tsx
src/components/markdown/ProblemsList/ProblemsList.tsx

- add most remaining usaco tags (by find & replace)
- link to contest in division table
- make sure single problems in `problems` are processed correctly

Division Table Upgrade

---

content/1_General/Lambdas.mdx
content/1_General/Notes_CPP_DS.mdx
content/2_Bronze/Ad_Hoc.mdx
content/2_Bronze/Intro_DS.mdx
content/2_Bronze/Intro_Sets.mdx
content/2_Bronze/Intro_Sorting.mdx
content/2_Bronze/Simulation.mdx
content/ordering.ts
solutions/USACO dec15-speeding-ticket.mdx
solutions/USACO feb16-circularbarn.mdx
solutions/USACO feb17-whyIII.mdx
solutions/USACO open18-team-tic-tac-toe.mdx
src/components/Dashboard/ModuleLink.tsx

- better ad hoc definition
- capitalize Bronze
- update times are displayed for longer

Ad Hoc + Update Times

---

solutions/USACO dec19-gymnastics.mdx
solutions/USACO feb20-triangles.mdx

Included C++ Implementation in USACO feb20-triangles.mdx
Included C++ Implementation in USACO dec19-gymnastics.mdx

Included C++ Implementation in USACO feb20-triangles and dec19-gymnastics

---

content/4_Gold/DSU.mdx

Updated the "p" in line 187 to "disjoint" to clear up confusion

Update p to disjoint in java

---

content/4_Gold/Intro_DP.mdx

fix spacing

---

content/4_Gold/Divis.mdx
solutions/AC Div Game.mdx

I added a C++ solution to AC Div Game. I linked the [editorial for the problem](https://atcoder.jp/contests/abc169/tasks/abc169_d/editorial), but there is no editorial there yet. Should I link the [overall editorial](https://img.atcoder.jp/abc169/editorial.pdf#page=12) instead?

Div Game C++ Solution

---

content/4_Gold/Paths_Grids.mdx
solutions/USACO dec16-cow-checklist.mdx

I added a C++ solution to Cow Checklist (December 2016 Gold).

Cow Checklist C++ Solution

---

solutions/USACO jan18-mootube-silver.mdx

Mootube java sol

---

solutions/CSES Subarray Sums II.mdx

CSES Subarray Sums II: Change TC to N log

---

solutions/CCC 20-escape.mdx

Removed that atrocious template, and also added some whitespace to make the code easier on the eyes.

Made Escape Room solution more readable

---

content/1_General/Contributing.mdx
content/1_General/IO.mdx

editorial code reqs are still TBD? #803

add note about kattio, upd contributing

---

solutions/USACO dec16-moocast-silver.mdx
src/components/MarkdownLayout/MarkdownLayout.tsx
src/components/MarkdownLayout/ModuleHeaders.tsx
src/context/MarkdownLayoutContext.tsx
src/pages/liveupdate.tsx

- Add ruler to `liveupdate`, closes #822.
- Directly link to problem statement in solution page
- just copied "Edit with LiveUpdate" style, should probably be better?
- Fix moocast overflowing lines, upd C++ sol

liveupdate ruler, solution links

---

gatsby-config.ts
src/pages/liveupdate.tsx

liveupdate force tabs, close #812

---

content/3_Silver/Binary_Search.mdx

Binary Search - minor modifications

---

content/4_Gold/Paths_Grids.mdx
solutions/USACO jan16-radio-contact.mdx

official solution top down. this one is bottom up.

radio contact solution

---

content/4_Gold/Intro_DP.mdx
solutions/USACO jan17-hoof-paper-scissors-gold.mdx

different (probably cleaner?) implementation of HPS w/ guide template

solution for HPS

---

content/1_General/Fast_IO.mdx
content/1_General/IO.mdx

- add headers
- fix compile error due to extraneous parenthesis

rewrite java fast i/o in same style as kattio

---

solutions/USACO open18-team-tic-tac-toe.mdx

No templates used (nor `bits/stdc++`), but I hope that's fine.

Cleaned up TTTT

---

content/4_Gold/String_Hashing.mdx

Two solutions:
- Sliding window + polynomial hash
- Modified hash + polynomial hash

Added solutions for the CCC string hashing focus problem

---

content/3_Silver/Binary_Search.mdx

Bin search fix

---

solutions/CSES Restaurant Customers.mdx

Remove the template for the 2nd implementation which was mentioned in [this thread](https://github.com/cpinitiative/usaco-guide/issues/806)
I also fixed a minor mistake in the visualization

Detemplate for CSES Restaurant Customers (2nd sol)

---

solutions/USACO dec15-speeding-ticket.mdx
solutions/USACO dec16-cowsignal.mdx
solutions/USACO open19-milk-factory.mdx

Worked on removing templates from the three non Benq templates from [This Thread](https://github.com/cpinitiative/usaco-guide/issues/806#issuecomment-784260077):
- The Cow Signal
- Speeding
- Milk Factory

Detemplate 3 Bronze Problems

---

src/components/Dashboard/Activity.tsx
src/components/Dashboard/heatmap-styles.css
src/pages/dashboard.tsx

(proof of concept; are there any features we should add before merging?)

feat: add basic activity chart to dashboard

---

solutions/CSES Path Queries.mdx

Removed previous solution (template + macros) and elaborated on the provided expl

path queries solution

---

solutions/USACO dec18-backforth.mdx

I am already in the middle of #850 and didn't feel like commiting and forcing the people that have spent so long agonizing over my terrible detemplating skills with another one, but I did back and forth, removed everything, fixed spacing, and works on the grader.
Taken from #872 
(I promise this one is better)

Cleaned up Back and Forth

---

solutions/USACO dec19-gymnastics.mdx

I also more clearly separated the official / alternate solution

add video solution for cow gymnastics

---

content/4_Gold/LIS.mdx

https://github.com/cpinitiative/usaco-guide/issues/839

LIS: add focus problem

---

content/1_General/Cpp_Command.mdx
content/1_General/IO.mdx

Issue #874
Not sure what else I need to change?

F string revert

---

content/3_Silver/DFS.mdx
solutions/USACO feb19-the-great-revegetation.mdx

1. Made new markdown file for the great revegetation (usaco920) with java solution
2. Added the new solution link to the problem constructor in bipartite/dfs
This is my first pull so if I did anything wrong please let me know

DFS/Bipartite (Silver) the great revegetation solution

---

CODEOWNERS
content-codeowners.json
functions/package.json
functions/src/index.ts

maybe title should no longer be "content-codeowners" though

upd those in charge of problem suggestions

---

solutions/USACO dec17-the-bovine-shuffle-silver.mdx

The internal sol on usaco.guide is pretty much the same as the official sol, so I thought it would be nice to add a different solution and in java as well.

Added java sol for bovine shuffle silver

---

solutions/CSES Flight Routes Check.mdx

To clear the meaning of the main idea

Update CSES Flight Routes Check.mdx

---

solutions/CSES Graph Girth.mdx

> avoid using additional macros beyond the ones listed above. In particular, for loop macros are highly discouraged.
- USACO Guide, 2020

Debenqify code

---

content/5_Plat/DP_Bitmasks.mdx

I wrote this as an elaboration for the topics presented, but it felt rather long, so I decided to make a blog and put it on there. Luckily all the mdx is cross compatible with usaco guide, so please do lmk if any sections should be merged. Not totally sure how we're going to do a pr the traditional way on this one though.

dp bitmasks

---

content/5_Plat/RURQ.mdx

fix typo / broken link in RURQ

---

content/2_Bronze/Complete_Rec.mdx
content/3_Silver/Prefix_Sums.mdx
content/5_Plat/Intro_Bitwise.mdx
content/ordering.ts

Closes #993 . I put it in "other" because it's technically not "dynamic programming"

move bitwise => plat

---

content/4_Gold/SP.mdx
content/6_Advanced/FFT.mdx
solutions/JOI 21-robot.mdx
solutions/POI 18-wie.mdx

- POI 2018 Polynomial (FFT module)
- JOI 2021 Robot (SP module)

JOI and POI - two editorials

---

content/5_Plat/2DRQ.mdx
solutions/IOI 13-game.mdx

Closes https://github.com/cpinitiative/usaco-guide/issues/916. There's not a lot to say about this problem...

Mini editorial for IOI 2013 Game

---

content/5_Plat/Sqrt.problems.json
content/6_Advanced/Persistent.problems.json
gatsby-node.ts

Forces problems with the same URL to have the same unique ID (unless specifically exempted)

ensure that problems with the same URL have the same unique ID

---

content/4_Gold/DP_Trees.problems.json
content/4_Gold/SP.problems.json
content/4_Gold/Sliding.problems.json
content/5_Plat/Centroid.problems.json
content/5_Plat/DC-DP.problems.json
content/5_Plat/DP_Bitmasks.problems.json
content/5_Plat/Merging.problems.json
content/5_Plat/RURQ.problems.json
content/5_Plat/Sqrt.problems.json
content/5_Plat/Sweep_Line.problems.json
content/6_Advanced/CntMin.problems.json
content/6_Advanced/Game_Theory.problems.json
content/6_Advanced/Interactive.problems.json
content/6_Advanced/LCT.problems.json
content/6_Advanced/String_Search.problems.json

fix: IOI solution json

---

content/3_Silver/Binary_Search.problems.json
content/3_Silver/Prefix_Sums.problems.json
content/3_Silver/Prefix_Sums_2.problems.json

Not completely sure if the ID's are in the right format.

Silver problems

---

tailwind.config.js

Remove comic sans

---

content/extraProblems.json
solutions/1_extra_usaco_probs.ts

Changed Just Green Enough to Stone Game

fix wrong name of usaco-1113 

---

content/4_Gold/LIS.mdx

Alternative RMQ Solution added

Update LIS.mdx With Alternative RMQ Solution

---

content/1_General/Fast_IO.mdx
content/2_Bronze/Intro_Greedy.mdx
content/3_Silver/Sorting_Custom.mdx
content/3_Silver/Sorting_Old.txt
content/4_Gold/DP_NT.txt
content/4_Gold/Knapsack_DP.mdx
content/4_Gold/Stacks.mdx
content/5_Plat/2DRQ.mdx
content/5_Plat/Intro_Bitwise.mdx
content/6_Advanced/CntMin.mdx
content/6_Advanced/Extend_Euclid.mdx
content/6_Advanced/Interactive.mdx
content/6_Advanced/String_Suffix.mdx

I left some usages of `:` in when I felt `:` made more sense than `-`

change : to -, closes #1056

---

content/6_Advanced/Segtree_Beats.mdx
content/6_Advanced/Segtree_Beats.problems.json

bear & powers of 42

---

solutions/USACO feb19-paintbarn.mdx

C++ sol taken from official analysis (with minor modifications). Java sol migrated to use Kattio. (This problem is being used in CPI class)

add C++ sol for paintbarn; use kattio for java

---

content/extraProblems.json
gatsby-node.ts
solutions/USACO feb21-clockwise-fence.mdx

Added a new solution in python for feb 21 bronze q3 using vector cross production

Added a new python solution for feb 21 bronze q3

---

content/1_General/Debugging_General.mdx

some recent USACO probs have used multitest

add back clearing data structures between test cases

---

src/components/MarkdownLayout/MarkCompleteButton.tsx
src/components/SectionsDropdown.tsx
src/components/TopNavigationBar/TopNavigationBar.tsx
src/components/markdown/ProblemsList/ProblemStatusCheckbox.tsx

I added dark mode support for the section dropdowns, module and problem status dropdowns and the settings dropdown.

Dark mode support for dropdowns

---

content/4_Gold/All_Roots.mdx

Addresses part of https://github.com/cpinitiative/usaco-guide/issues/1147
Not lowering frequency for this one to has not appeared bc this has appeared (directory traversal, which is a problem for the module)

Remove "(Optional)" from DP on Trees

---

content/4_Gold/LIS.mdx

Addresses part of https://github.com/cpinitiative/usaco-guide/issues/1147

Remove "(Optional)" from LIS and lower frequency

---

.storybook/preview-head.html
src/components/markdown/FocusProblem.tsx
src/components/markdown/HTMLComponents.tsx
src/components/markdown/Info.tsx
src/components/markdown/Optional.tsx
src/components/markdown/Warning.tsx
src/stories/markdown/FocusProblem.stories.tsx
src/stories/markdown/MarkdownContent.stories.tsx
src/stories/markdown/MiscMarkdownContent.tsx
src/stories/markdown/Optional.stories.tsx
src/styles/generalStyles.css
tailwind.config.js

- clean up list styles for markdown

add more components

---

content/5_Plat/Centroid.mdx
content/5_Plat/Centroid.problems.json

I think this makes it easier to understand. 
You guys never provided an explanation for how to find the centroid, and jumped directly to the centroid decomp algorithm.

Added explanation for find centroid algorithm

---

src/components/ForumCTA.tsx
src/components/ProblemAutocompleteModal/ProblemAutocomplete.tsx
src/components/ProblemAutocompleteModal/ProblemAutocompleteModal.tsx
src/components/markdown/Danger.tsx
src/components/markdown/IncompleteSection.tsx
src/components/markdown/LanguageSection.tsx
src/components/markdown/ResourcesList.tsx
src/components/markdown/Spoiler.tsx
src/stories/AsteriskTooltip.stories.tsx
src/stories/Button.stories.tsx
src/stories/Input.stories.tsx
src/stories/TextTooltip.stories.tsx
src/stories/Textarea.stories.tsx
src/stories/Tooltip.stories.tsx
src/stories/groups/ProblemAutocomplete.stories.tsx
src/stories/markdown/Danger.stories.tsx
src/stories/markdown/MarkdownContent.stories.tsx
src/stories/markdown/Spoiler.stories.tsx
src/stories/markdownLayout/ForumCTA.stories.tsx
src/styles/components.css
src/styles/generalStyles.css

made some minor styling adjustments for buttons/forms, problem / resource lists, etc, especially on dark mode
see https://606f93d2ed90e00021a7fec7-impapumyoj.chromatic.com/

more components

---

solutions/CSES Road Construction.mdx

Continued from the [previous pull request](https://github.com/cpinitiative/usaco-guide/pull/1277):
Added implementation heading and time complexity.

Update CSES Road Construction.mdx

---

solutions/USACO jan18-lifeguards.mdx

planning on making a video solution for this for CPI classes

update solutions for usaco lifeguards

---

content/4_Gold/All_Roots.mdx

upd impl, closes #1104

---

src/functions/src/submitProblemSuggestion.ts

removes both leading and trailing whitespace, when tags is empty returns an empty list as expected

prob suggestion tag parsing fix?

---

CONTRIBUTING.md
content/1_General/Contributing.mdx

Update contributing module

---

content/1_General/Contributing.mdx

I messed up the indentation of the problem json...

quick fix: problem json indentation

---

content/3_Silver/Binary_Search.problems.json
content/4_Gold/Intro_DP.problems.json
content/extraProblems.json

see https://forum.usaco.guide/t/introduction-to-dp-angry-cows/1168/3 for reasons

- angry cows from intro dp

---

src/components/ProblemSuggestionModal.tsx
src/hooks/useProblemSuggestionAction.tsx
src/models/problem.ts

- split tags same way regardless of whether in editor or not
- only one alert when source is not given
looks like
https://github.com/cpinitiative/usaco-guide/pull/1359#issuecomment-822114877
still not resolved though

prob-suggest-updates

---

content/1_General/Contributing.mdx
src/components/markdown/Danger.tsx
src/components/markdown/Info.tsx
src/components/markdown/Optional.tsx
src/components/markdown/ResourcesList.tsx
src/components/markdown/Spoiler.tsx
src/components/markdown/Warning.tsx
src/stories/markdown/MarkdownContent.stories.tsx
src/styles/generalStyles.css

think /general/contributing looks better now

add margin to pre in general css styles

---

solutions/CSES Prefix Sum Queries.mdx

Fix typo error (#1378)

---

content/5_Plat/Centroid.mdx

Hello, I've fixed the Java general Centroid code for https://usaco.guide/plat/centroid?lang=java. But I don't know c++, so maybe someone else can reference this and update the c++ code 😛 
I have a successful submission with that code here https://codeforces.com/contest/342/submission/113088188

Add General Centroid Code

---

solutions/CSES Sum of Divisors.mdx

I have updated the editorial for the problem Sum of Divisors after trying the problem myself and getting stuck on it. In my case I found it necessary to seek for external help via USACO forum / other editorials to fully understand the problem. Hence I proposed an update to the editorial.

Update CSES Sum of Divisors.mdx

---

content/3_Silver/Prefix_Sums.problems.json
content/4_Gold/Sliding.problems.json
solutions/USACO jan16-fortmoo.mdx

Sadly, the Python solution times out on 3 test cases.
Should I add an internal editorial as well?

Fort Moo Internal Solution

---

solutions/USACO jan16-promotion-bronze.mdx

Update USACO jan16-promotion-bronze.mdx

---

content/3_Silver/Flood_Fill.mdx

Change floodfill diagram

---

src/context/FirebaseContext.tsx

this should (?) resolve the hot reload issue of "a firebase app has already been initialized"

improve firebase context

---

src/components/elements/RadioList.tsx

This pr fixes the bug where unchecked radiolists have a white dot in the center when dark mode is on.

Fix Radio List Dark Mode Bug

---

content/4_Gold/Divis.mdx

can we have an f for the lack of python support though
also you can trust me, all sols have been tested and AC'd

Improved Divisor Module

---

solutions/CSES Labyrinth.mdx
solutions/CSES Monsters.mdx

add java implementation to cses labyrinth

Update CSES Labyrinth.mdx

---

solutions/USACO dec18-bucketlist.mdx

added a cpp solution to https://usaco.guide/problems/usaco-856-the-bucket-list/solution this page where the only solution is in python. Might also add a java sol later so we have support for all 3 languages for bronze and we can work our way up. Thats my goal if I ever join the team is to give every language equal amount of solutions and lessons.

Update USACO dec18-bucketlist.mdx

---

solutions/USACO dec19-lineup.mdx
solutions/USACO feb20-swap.mdx

No functionality has been changed, just the templates have been removed. The solutions in question are:
- Livestock Lineup (Bronze)
- Swapity Swap (Bronze)

Remove 2 Templates from Solutions

---

content/1_General/Expected.problems.json
solutions/USACO dec20-DoYouKnowYourABCs.mdx

solution to https://usaco.guide/general/expected?lang=cpp 
in java, since there are a ton of solutions in CPP and the official sol is in cpp

Create USACO dec20-DoYouKnowYourABCs.mdx

---

content/3_Silver/Conclusion.problems.json

cc @andrewwangva 
taken from #1515

add liars and truth tellers to mixed problemset

---

solutions/usaco-1038.mdx
solutions/usaco-1062.mdx
solutions/usaco-1064.mdx
solutions/usaco-1084.mdx
solutions/usaco-918.mdx

added five video solutions for bronze/silver questions, please check if the formatting is okay!

test add 5 video solutions

---

src/components/markdown/ProblemsList/DivisionList/DivisionList.tsx
src/pages/dashboard.tsx

Division Table Updates

---

src/components/markdown/CodeBlock/CodeBlock.tsx
src/components/markdown/CodeBlock/SyntaxHighlighting/Highlight.js

should also copy snippets properly (ex. in `/general/working-mdx`)
closes #1456

copying code blocks

---

src/components/MarkdownLayout/MarkdownLayout.tsx
src/context/UserDataContext/properties/userLang.ts

resolves first issue from #1550?

don't overwrite lang param when going to settings and back

---

content/2_Bronze/Rect_Geo.mdx
content/2_Bronze/Time_Comp.mdx

Added some stuff to the time complexity + rect geo module.

Improved some bronze modules

---

src/components/markdown/CodeBlock/CodeBlock.tsx
src/stories/markdown/CodeBlock.stories.tsx

Copy button fixes

---

content/4_Gold/MST.problems.json
solutions/cf-472D.mdx

Code for CF 472D hopefully with spaces/tabs fixed

add internal solution for CF 472D

---

src/components/markdown/CodeBlock/CodeBlock.tsx
src/stories/markdown/CodeBlock.stories.tsx

fixes https://usaco.guide/problems/usaco-807-teleportation/solution

update copy button for python

---

solutions/usaco-783.mdx

Added Java and Python support for both solutions- all have been tested.

Completed Blocked Billboard 2

---

content/3_Silver/DFS.mdx

Linked BFS in DFS module

---

src/mdx-plugins/rehype-snippets.js

small changes, nothing much to format really

formatted KattIO

---

solutions/usaco-104.mdx

Added Java implementation that follows the C++ version that is already there, added notes on both the C++ version and the new Java version to help people understand better. I made sure that the implementation for the new Java version is the same as the C++ code, it compiles and passes on Sphere.

Java Implementation for Haybale Stacking + New Notes

---

content/5_Plat/HLD.mdx

The solution for Path Queries II TLE'd on test case 8, so I switched the update and query functions for the segtree to be iterative instead of recursive.

Update HLD.mdx (corrected solution)

---

content/4_Gold/DSU.mdx

Added Python support and made the solutions consistent with the initial classes provided.

Improved DSU Module

---

content/4_Gold/DP_Ranges.problems.json
solutions/cses-1080.mdx

https://forum.usaco.guide/t/cses-empty-string/1361

CSES Empty String

---

content/3_Silver/Intro_Tree.problems.json
solutions/USACO feb20-clocktree-silver.mdx

Added an explanation different from official solution (the final code is very similar though). 
Added video link to further explain the solution.
Let me know if the video is proper. I can create more videos later if it is okay.
@maggie-j-liu  I closed PR1470 as somehow my local git don't let me adding new files to this PR..

Internal Solution for Clocktree (Closed PR#1470 and replaced with this) 

---

solutions/usaco-568.mdx

Added (and tested) Java + Python sol.

Improved speeding sol

---

content/2_Bronze/Complete_Rec.mdx

I added a python solution using `itertools.permutations` to Creating Strings. 
Maybe we should change the `next_permutation` section to a LanguageSection, and put this section there? I wasn't sure so I put it in a separate section for now, but I can change it.

Creating Strings python solution

---

solutions/usaco-735.mdx

Added the Java implementation of the problem since there was only C++ and Python

Java Implementation of The Lost Cow (735)

---

content/3_Silver/Prefix_Sums_2.mdx

Max Subarray Sum Java Implementation of Kadane's Algorithm

---

content/1_General/Running_Code_Locally.mdx

Added instructions to run C++ on Linux (installing `g++`, and how to use it to compile a file)

Instructions to run C++ on Linux

---

content/4_Gold/Divis.problems.json
solutions/cf-1536C.mdx

Do I need to write some small clarifications? I feel like the original editorial is good enough.
All solutions have been tested.

Diluc and Kaeya Solution

---

src/components/ProblemsPage/ProblemHits.tsx

Update ProblemHits title to be clickable

---

src/components/Editor/MainEditorInterface.tsx
src/components/markdown/CodeBlock/CodeBlock.tsx

Editor fixes

---

content/4_Gold/Unordered.mdx

add basic overview operations for unordered_map among some small changes.

unordered updates

---

solutions/usaco-1011.mdx

There are no Python solutions currently for this problem, so I thought I'd add mine!

Python Solution for USACO Triangles

---

solutions/ac-matching.mdx

All solutions have been tested.

Matching Revamp

---

solutions/usaco-615.mdx

There's also no Python solution for this question. All test cases pass for this answer.

Python Solution for Milk Pails

---

content/1_General/IO.mdx

Add `CodeSnip`s for Kattio

---

solutions/usaco-712.mdx

Python Solution for Why Did the Cow Cross the Road II 

---

content/6_Advanced/Persistent.mdx

Also, should we maybe move this before introducing the persistent segtree?

Added persistent array implementation

---

content/3_Silver/Binary_Search.problems.json

Problem Source: "CEOI 2012" -> "CEOI"

---

content/2_Bronze/Intro_Complete.problems.json
solutions/usaco-893.mdx

Copy pasted Brian Dean's code, added my own Java implementation, changed the .json file

Internal Solution for Guess the Animal

---

content/4_Gold/TopoSort.mdx

Added a c++ solution using bfs to Course Schedule, since the code there before wasn't a full solution.

Course Schedule c++ solution

---

content/4_Gold/Knapsack_DP.mdx

knapsack py sol + general changes

---

solutions/usaco-639.mdx
solutions/usaco-785.mdx

All test cases pass for this solution.

Python Solution: Out of Place and Diamond Collecter

---

content/2_Bronze/Intro_Complete.problems.json
solutions/usaco-1037.mdx

Added internal solution and put my own Java implementation with notes, json file changed

Internal Solution for Cowntact Tracing 

---

solutions/izho-14-bank.mdx

I removed BenQ from the author's list because I removed all the code he wrote. I can add him back if you guys want.

Bank Solution

---

content/4_Gold/DP_Bitmasks.mdx

Bitmask DP Revamp

---

src/components/ProblemSuggestionModal.tsx

quick fix: issue -> pull request in problem suggestion modal

---

solutions/usaco-964.mdx

There was only C++ (official analysis) and Python so I added the Java implementation, added notes as well.

Java Solution for Where am I

---

solutions/cf-1158A.mdx

The previous code iterated through the arrays again to find the minimum and maximum. However, they already sorted it, so they can just use the first and last elements.

Silver Greedy - Party and the Sweets Revised Solution

---

content/2_Bronze/Intro_Complete.problems.json
content/extraProblems.json
solutions/usaco-688.mdx

All test cases pass for this solution.

Solution for Hoof, Paper, Scissors

---

CODEOWNERS
content/authors/contributors.ts
src/components/Index/ContributorsSection.tsx

Also, do we want to add more people to CODEOWNERS (@nwatx @SansPapyrus683)?

create past contributors section, - myself from CODEOWNERS + rearrange

---

solutions/usaco-915.mdx

all test cases pass for this solution.

Added Python Solution for Sleepy Cow Herding

---

content/1_General/Debugging_General.mdx

remove some info already contained within the forum post: https://forum.usaco.guide/t/how-to-ask-for-help-on-a-problem/338#if-you-need-help-debugging-your-code-3

Refactor - Before Posting on the Forum

---

solutions/cses-1621.mdx

distinct #s solution - link to module

---

solutions/usaco-940.mdx

all test cases pass for this solution

Added Python Solution for Milk Factory

---

src/components/markdown/ProblemsList/ProblemsListItem.tsx
src/models/problem.ts

Adds open in ide button to all usaco problems, not just the ones in the usaco monthlies table

Add open in ide button to all usaco problems

---

content/3_Silver/Intro_Tree.problems.json
content/extraProblems.json

removed from module, added to extra problems

(module revamp) Remove IOI, POI, CCC problems

---

solutions/usaco-895.mdx

I hope the comments aren't too extra, I just feel like I need to comment on many lines because the implementation can be a bit confusing

Java Solution for Icy Perimeter

---

content/2_Bronze/Rect_Geo.mdx

Changed the print(total) line to print(union) in the python section

Change print(total) to print(union)

---

solutions/usaco-1138.mdx

Fixed stuff i messed up in the previous pr, added a solution using Prim's.
The general idea is the same as the official analysis, just implemented with Prim's instead of Kruskal's, so I didn't think I needed to add an explanation. I can write one if it's needed, though.

C++ Solution using Prim's for Portals

---

content/2_Bronze/Intro_Graphs.problems.json
content/extraProblems.json
solutions/usaco-916.mdx

Added Python Solution for The Great Revegetation 

---

solutions/usaco-939.mdx

Bucket Brigade C++ Solution

---

solutions/usaco-941.mdx

all test cases pass for this solution.

Added Python Solution to Cow Evolution (Bronze)

---

solutions/usaco-663.mdx

Square Pasture Java Solution

---

solutions/usaco-833.mdx

Added Python Solution for Family Tree (Bronze)

---

solutions/cf-831C.mdx

added java solution with notes included

Java Solution for Jury Marks

---

content/1_General/IO.mdx

Added file reading using .readlines() and .readline(), writing to files using .write(), and basic tutorial on f-strings.

Expanded on Python I/O

---

content/4_Gold/Intro_DP.mdx
content/4_Gold/Intro_DP.problems.json

Add Intro_DP Focus Problem

---

solutions/usaco-940.mdx

All test cases passed for the added solution. 
And besides, a question: If I didn't miss anything, shouldn't the time complexity of [Solution 2](https://usaco.guide/problems/usaco-940-milk-factory/solution#solution-2) be O(n^2)? This loop would cost N and DFS will also take N to iterate. So it would be N*N at the end. 
```
for(int i = 0; i < N; i++){
int ans = g.DFS(i);
if(ans == N){
out.println(i + 1); // If the number of visited stations from the DFS is equal to the total number of stations then output.
used = true;
break;
}
}
```

Added Java Implementation for Solution 1 of Milk Factory (Bronze)

---

solutions/usaco-1037.mdx

all test cases pass for this solution.

Added Python Solution for Cowntact Tracing (Bronze)

---

solutions/usaco-714.mdx

If someone can collapse that IO template in the C++ code that would be great I'm not sure how to do that

Java Solution for Why Did the Cow Cross the Road (Silver February 2017)

---

content/2_Bronze/Complete_Rec.mdx

Creating Strings 1 Solutions

---

solutions/cf-1398C.mdx

added comments to the c++ code as well

Java Solution for Good Subarrays

---

content/2_Bronze/Complete_Rec.problems.json
solutions/usaco-857.mdx

also commented out Benjamin Qi's code and added language section tag.

Added Python Solution to Back & Forth (Bronze)

---

solutions/cf-1365D.mdx

Added dx dy arrays to remove the if statements, changed to true/false boolean instead of 0/1

Make C++ Solution for Solve the Maze More Readable

---

solutions/usaco-593.mdx

also added brief editorial and time complexity, all test cases pass for this solution :)

Add Python Solution to Mowing the Field (Bronze)

---

content/5_Plat/Bin_Jump.problems.json
solutions/usaco-576.mdx

This is a continuation from [here](https://github.com/cpinitiative/usaco-guide/pull/1461).

Created Solution to "USACO - Max FLow"

---

solutions/cses-1661.mdx

removed spoiler because it isn't necessary

Java Solution for Subarray Sums II

---

solutions/usaco-941.mdx

Added Java Implementation for Cow Evolution (bronze)

---

solutions/usaco-833.mdx

All test cases passed. 
<s>I'm gonna also write an implementatino for Sol1. </s>   **Done.**

Added Java Implementation for Family Tree [833] (bronze)

---

solutions/usaco-694.mdx

I cannot make the lines any shorter

Java Solution for Hoof Paper Scissors (Gold Version of the Problem)

---

content/4_Gold/Knapsack_DP.problems.json
solutions/tc-submultiplesofn.mdx

not sure if the lines are too long
oh well

Submultiples of N Solution

---

content/2_Bronze/Simulation.problems.json
solutions/usaco-761.mdx

Add Python Solution for Milk Measurement (Bronze)

---

solutions/cses-1161.mdx

Added Java Solution to Stick Division [cses-1161]

---

solutions/cses-1202.mdx

https://forum.usaco.guide/t/possible-optimization-in-internal-solution-for-cses-cses-investigation/1719

Improve solution to CSES Investigation

---

content/4_Gold/DP_Bitmasks.mdx

Reverts cpinitiative/usaco-guide#2017

Revert "Add resource to bitmask dp module"

---

content/1_General/Resources_CP.mdx
content/4_Gold/DP_Bitmasks.mdx

Reverts cpinitiative/usaco-guide#2020

Revert "Add resource to resources section of bitmask DP + resources page"

---

src/components/TopNavigationBar/TopNavigationBar.tsx

Placed a link to the USACO IDE in the top navigation bar. This will spread awareness of IDE's existence and therefore bring it more users.

Added IDE to the top navigation bar

---

src/components/Dashboard/ActiveItems.tsx
src/components/Dashboard/DashboardProgress.tsx
src/components/Dashboard/ModuleLink.tsx
src/components/MarkdownLayout/MarkCompleteButton.tsx
src/components/SectionsDropdown.tsx
src/components/markdown/CodeBlock/CodeBlock.tsx
src/components/markdown/ProblemsList/ProblemStatusCheckbox.tsx
src/components/markdown/ProblemsList/ProblemsListItem.tsx
src/components/markdown/ResourceStatusCheckbox.tsx
src/components/markdown/ResourcesList.tsx
src/components/markdown/ResourcesListItem.tsx
src/context/UserDataContext/UserDataContext.tsx
src/context/UserDataContext/properties/userProgressOnResources.ts
src/models/resource.ts
src/stories/markdown/Resources.stories.tsx

Closes #1938
just copied the `ProblemsList` stuff, maybe worth refactoring

add resources checkbox, adjust copy button positioning

---

src/components/markdown/ResourcesListItem.tsx
src/templates/moduleTemplate.tsx

these now scroll properly:
https://usaco-guide-dgmoj15ea-cpinitiative.vercel.app/general/input-output?lang=java#method-1---scanner-and-systemoutprint
https://usaco-guide-dgmoj15ea-cpinitiative.vercel.app/silver/prefix-sums?lang=java#resource-https%3A%2F%2Fdarrenyao.com%2Fusacobook%2Fjava.pdf%23page%3D69

Fix Hash Scroll

---

content/2_Bronze/Rect_Geo.mdx
solutions/cf-814C.mdx

Redid Garland Sol (And Fixed Rect Geo Sol)

---

content/authors/authors.ts
src/components/SectionsDropdown.tsx
src/components/TopNavigationBar/TopNavigationBar.tsx

I also added IDE/Forum to the nav bar as well as updated the description for Siyong to be IOI gold medalist

Add flyout menu to top navigation bar + add IDE/Forum to mobile

---

.github/stale.yml

if no activity for 7+7 days then probably never

auto-close after 7 days

---

content/4_Gold/DSU.mdx
solutions/cses-1090.mdx

I also added myself to the ferris wheel internal solution because I forgot in my previous PR (oops).

Add focus problem solution explanation to DSU module + refactor solution code

---

src/components/ButtonGroup.tsx
src/components/ProblemSuggestionModal.tsx
src/components/markdown/ProblemsList/ProblemsList.tsx
src/functions/src/submitProblemSuggestion.ts
src/models/problem.ts

Since no one wants to deal with them :P

Disable Problem Suggestions

---

solutions/usaco-738.mdx

all test cases pass for this solution :) (video editorial for cpi coming soon)

Python Solution + Editorial in Paired Up (Silver)

---

solutions/usaco-760.mdx

Python Solution for the Bovine Shuffle (Bronze)

---

solutions/cses-1640.mdx

Reverts cpinitiative/usaco-guide#2069

Revert "Update cses-1640.mdx"

---

content/1_General/Intro.problems.json

update problem link

---

solutions/cses-1640.mdx

Add Python/Java/C++ Solution for Sum of Two Values

---

content/3_Silver/Binary_Search.problems.json
solutions/ceoi-12-JobScheduling.mdx

[All test cases passed.](https://oj.uz/submission/448807)

Added internal solution for Job Scheduling [ceoi-12]

---

content/3_Silver/Func_Graphs.mdx

All test cases ([java](https://codeforces.com/contest/1020/submission/125218500), [cpp](https://codeforces.com/contest/1020/submission/125217515)) passed.

Added java implementation and refactored cpp code for functional graphs [silver]

---

content/1_General/Modules.mdx
content/1_General/Using_This_Guide.mdx
src/components/ContactUsSlideover/ContactUsSlideover.tsx
src/components/ContactUsSlideover/SlideoverForm.tsx
src/components/MarkdownLayout/SidebarBottomButtons.tsx
src/components/TopNavigationBar/TopNavigationBar.tsx
src/components/markdown/ProblemsList/ProblemListItemSolution.tsx
src/context/FirebaseContext.tsx
src/functions/src/index.ts
src/functions/src/submitContactForm.ts
src/hooks/useContactFormAction.tsx
src/pages/index.tsx

Update contact form to submit github issue

---

solutions/cses-1091.mdx

Note: Results in TLE on test cases 5 and 8. Not sure if there's any way to fix this. Also, I might have put way too many comments and made them all very verbose; I'm so sorry if that's the case.

Add Java solution to Concert Tickets CSES

---

content/2_Bronze/Rect_Geo.mdx
content/4_Gold/Knapsack_DP.problems.json
solutions/ojuz-knapsack.mdx

someone help me explain why the complexity is S^2 log s lol i have no clue

Knapsack Solution

---

solutions/usaco-988.mdx

all test cases pass for this solution, also @SansPapyrus683 please have mercy 🙏 :)

Add C++ Solution to Photoshoot (Bronze)

---

content/extraProblems.json
solutions/cf-1560B.mdx

all test cases pass for this solution :) 
@SansPapyrus683 hopefully my c++ code is better this time 🙏

Add Python, C++, and Java Solution to Who's Opposite? (CF)

---

src/components/Groups/LeaderboardList/LeaderboardList.tsx
src/components/Groups/LeaderboardTable/LeaderboardTable.tsx

Rounds the points displayed on the leaderboard to the nearest integer.

Fix leaderboard precision

---

solutions/usaco-736.mdx

Also added to the Solution 1 description

Add Java solution to Bronze Bovine Genomics (Solution 1)

---

content/6_Advanced/Wavelet.mdx

I might add some more problems in the Wavelet section later

Wavelet Resource

---

content/3_Silver/Two_Pointers.mdx

Oh and I also fixed a mistake in a sentence.

Two Pointers Add Walkthrough since It's kinda confusing

---

content/4_Gold/BFS.problems.json
solutions/ioi-00-walls.mdx

someone tell me if the complexity is right all i know is that it works
also i hate java so no java sol
(i could do it, it just would take so long given that there's no pair class and it needs a hashmap)

walls internal solution

---

solutions/usaco-712.mdx

Fixed wrong variable name in C++ solution

Update usaco-712.mdx - fix typo

---

content/2_Bronze/Time_Comp.mdx

i only have 3 questions rn, if you have any ideas, lmk :D

Add quiz to Time Complexity module

---

solutions/cses-1202.mdx

Added Java Implementation to Investigation [cses-1202]

---

content/1_General/Input_Output.mdx

Added stdin and stdout as methods for input and output for the Python section. I might additionally add stdin and stdout to Fast I/O for Python in the future if it would be helpful. Any tips relating to GitHub, as you could probably tell, would be very much appreciated :).

Update Input_Output.mdx - stdin and stdout Python

---

announcements/Groups Access.mdx
src/components/Groups/GroupSelectPage/GroupSelectPage.tsx
src/components/TopNavigationBar/TopNavigationBar.tsx

Added a link to the groups access form on the groups page and created an announcement

Add Groups Access Form

---

solutions/usaco-571.mdx

I forgot to read in `n` for the C++ solution.

Error in Solution!

---

solutions/cf-702C.mdx

I didn't solve the problem this way, so I don't think I can improve the comments that much

Java Solution for Cellular Network (Implementation 2, Two Pointers)

---

content/2_Bronze/Intro_Greedy.mdx

Add quiz for Intro to Greedy Algos

---

content/2_Bronze/Complete_Rec.mdx
solutions/usaco-988.mdx

Continuing changes from pr that didn't make any

Make photoshoot changes

---

solutions/usaco-760.mdx

Jesse Chloe code was very messy and hard to understand + had a huge header for some reason??
Added my code which has detailed comments that explain the code in a simple manner and added neat variable names

Update usaco-760.mdx 

---

content/extraProblems.json
solutions/cf-1566B.mdx

sorry for not doing any prs last week, caught up with other stuff

Add Python/C++ Solution to MIN-MEX Cut (CF)

---

content/1_General/Expected_Knowledge.mdx

At the end of the page "Resources: Learning to Code" for C++ in the General section:
"Knowledge of pointers, structs and classes is useful but not required."
is mentioned, but is not included in the Expected Knowledge page.

Add Expected Knowledge

---

content/3_Silver/Binary_Search.mdx
solutions/ceoi18-clo.mdx

they were awfully inconsistent

redid some parts of the binsearch module

---

solutions/usaco-1060.mdx

Add Python Solution to Daisy Chains (Bronze)

---

content/2_Bronze/Complete_Rec.mdx

From [here](https://github.com/cpinitiative/usaco-guide/pull/2162)

Complete Recursion Quiz

---

content/3_Silver/Binary_Search.mdx

i'll get around to adding python support for the last problem

did the rest of binsearch

---

content/3_Silver/Binary_Search.problems.json
content/3_Silver/Sorting_Custom.problems.json
solutions/usaco-1015.mdx
solutions/usaco-1038.mdx
solutions/usaco-666.mdx
solutions/usaco-715.mdx

USACO Silver problems Counting Haybales, Triangles, Social Distancing, Why Did the Cow Cross the Road II

Add code from my (Albert Zhu) videos

---

solutions/usaco-918.mdx

Add cpp solution for usaco-918

---

content/5_Plat/Binary_Jump.problems.json
solutions/cfgym-102694C.mdx

pr for sloth naptime cf

---

content/3_Silver/DFS.problems.json
solutions/cf-862B.mdx

sans pls go easy on the java code 🙏 
---
done._

Add C++/Java Solution to Bipartiteness (Silver)

---

content/1_General/Adding_Solution.mdx
content/1_General/Cpp_Command.mdx
content/1_General/Fast_IO.mdx
content/1_General/Running_Code_Locally.mdx
content/6_Advanced/Vectorization.mdx

- Reorganized C++ section of running code locally
- Added instructions for formatting C++ code (Closes #2292)
- Closes #1795

Revise General C++ Info

---

content/4_Gold/Shortest_Paths.problems.json
solutions/usaco-861.mdx

Internal Java solution for fine dining

---

content/3_Silver/Prefix_Sums.mdx

Quiz for Prefix Sums

---

solutions/usaco-861.mdx

🤦‍♂️ I accidentally set the wrong problem ID for my fine dining solution
done._

Fix problem id for fine dining solution

---

solutions/usaco-1011.mdx

fix code coloring

---

content/5_Plat/Matrix_Expo.mdx
content/5_Plat/Matrix_Expo.problems.json

Matrix Exponentiation Focus problem

---

content/4_Gold/LIS.mdx

add translation again

---

solutions/dmoj-Phidias.mdx

add java implementation to phidias

---

content/3_Silver/Intro_Ordered.problems.json
solutions/usaco-859.mdx

i was going to do python, but it's really bad for problems like this
ill start working on the two pointers quiz soon
---
done._

Add C++ Solution for Convention II (Silver)

---

content/4_Gold/Intro_DP.problems.json
solutions/usaco-993.mdx

Add java implementation to time is mooney

---

.github/workflows/test.yml
content/1_General/Running_Code_Locally.mdx
content/3_Silver/DFS.mdx
content/3_Silver/Flood_Fill.mdx
content/4_Gold/PURS.mdx

Fix workflow

---

content/2_Bronze/Rect_Geo.mdx

fix error in rect-geo

---

solutions/usaco-892.mdx

Update usaco-892.mdx - added cpp solution

---

content/1_General/Contests.mdx

Add an alternative to CF-Predictor in the contest resources page

---

content/4_Gold/Intro_DP.problems.json
solutions/usaco-863.mdx

done._
does this count as a "clear improvement over existing material"?

internal sol for teamwork

---

src/functions/src/cpiclasses/approveLiveFinancialAid.ts
src/functions/src/cpiclasses/processLiveRegistration.ts
src/functions/src/cpiclasses/utils/updateLiveMailingList.ts

@jeffreymeng once you approve/merge, can you also deploy the updated functions? Thanks!
done._

Update firebase functions for winter classes

---

content/3_Silver/Intro_Tree.mdx

Add quiz questions to Intro to Tree Algorithms section

---

content/3_Silver/Binary_Search.mdx

Clarify `lo--` in binary search implementation

---

content/1_General/Input_Output.mdx

done._
should close #2333 as well

io module stuff

---

solutions/cses-2166.mdx

typo in solution 2 title

---

solutions/cses-1636.mdx

Add java solution for coin combinations II

---

content/4_Gold/Intro_DP.problems.json
content/4_Gold/Shortest_Paths.problems.json
solutions/usaco-971.mdx

Add solution to usaco moortal cowmbat

---

src/components/markdown/ProblemsList/ProblemsList.tsx
src/components/markdown/ProblemsList/SuggestProblemRow.tsx

Reopen Problem Suggestions

---

content/3_Silver/Two_Pointers.mdx

Two Pointers Quiz (Silver)

---

content/3_Silver/Binary_Search.mdx

Quiz for Binary Search

---

content/5_Plat/Matrix_Expo.problems.json
solutions/cf-718C.mdx

Solution for CF-718C

---

src/components/TopNavigationBar/TopNavigationBar.tsx

changed alert message to sign up for classes (banner)

---

content/4_Gold/MST.mdx
content/4_Gold/MST.problems.json
solutions/joi-15-inheritance.mdx

done._
**again, i would like some editorial suggestions, i have no clue how to write proofs**
oh this should close #2301

joi inheritance support

---

content/5_Plat/Convex_Hull_Trick.problems.json
content/5_Plat/DC-DP.problems.json
solutions/cf-660F.mdx

Solution for CF-660F

---

content/4_Gold/Intro_DP.problems.json
solutions/usaco-945.mdx

make internal solution for usaco snakes gold

---

solutions/usaco-811.mdx

C++ Solution + Brief Editorial for Snow Boots (Silver)

---

solutions/usaco-570.mdx

Updated Solution for Switching on the Lights

---

solutions/usaco-946.mdx

Add link to official analysis

---

content/4_Gold/Intro_Bitwise.mdx

better bitwise stuff

---

content/4_Gold/MST.problems.json

No way this is an easy...
done._

Set "Checksum" difficulty to "Hard"

---

content/5_Plat/HLD.problems.json
content/5_Plat/Sqrt.problems.json
solutions/cf-1017G.mdx

AC Submission Here: https://codeforces.com/contest/1017/submission/136114509

Solution for CF-1017G

---

content/2_Bronze/Intro_DS.mdx

Add Intro to Data Structures Quizzes

---

src/components/TopNavigationBar/TopNavigationBar.tsx

done._
- [✓ ] I have tested my code
- [✓ ] I have followed the code style guidelines mentioned
- [✓] I have properly formatted the files according to the steps mentioned

Added new mobile nav bar

---

src/components/Groups/EditProblemPage/EditProblemHintModal.tsx

done._
- [✓] I have tested my code
- [✓] I have followed the code style guidelines mentioned
- [✓] I have properly formatted the files according to the steps mentioned

Hint editing

---

content/1_General/Debugging_Lang.mdx

done._
honestly the compiler stuff just seems kinda unnecessary
i'd delete them but idk what you guys would feel

overhauled debugging

---

solutions/cses-1074.mdx

done._
**The naming of variables inherits from C++ code.**

Add Python solution to CSES 1074 (Stick Lengths)

---

content/1_General/Debugging_Lang.mdx
content/1_General/Fast_IO.mdx

done._
gonna do the rest of fast io later

debugging module smol change + fast io half done

---

solutions/usaco-1083.mdx

done._
NOTE: My bufferedreader line is over 80 characters :|

add java implementation to usaco uddered but not herd bronze

---

solutions/usaco-696.mdx

Add Euler Tour Solution

---

solutions/cses-1084.mdx

Add Python solution to CSES 1084 (Apartments)

---

content/3_Silver/Intro_Sorted_Sets.mdx

Make Silver SortedSets better

---

solutions/cses-1090.mdx

Add Python solution to CSES 1090 (Ferris Wheel)

---

solutions/cses-1073.mdx

Add Python solutions to CSES 1073 (Towers)

---

solutions/cses-1620.mdx

[NEW] Add Java/Python solutions to CSES 1620 (Factory Machines)

---

content/1_General/Fast_IO.mdx
content/1_General/Generic_Code.mdx

rest of fast io and generic code

---

content/4_Gold/Shortest_Paths.problems.json
solutions/usaco-717.mdx

Why did the cow cross the road sol

---

solutions/usaco-915.mdx

added my own c++ solution to the problem, since c++ solution was missing. feel free to change formatting, I'm pretty new to github and this is actually my first pull request

Add C++ to problem

---

solutions/usaco-993.mdx

yay a new pr! 
a lot of sols in intro to dp don't have cpp solutions, so ill be adding some throughout this week :)
---
done._

Add C++ Solution + Short Editorial to Time is Mooney (Gold) 

---

solutions/usaco-945.mdx

lmk if you want me to go into more detail with the editorial
---
done._

Add C++ Solution + Editorial to Snakes (Gold)

---

solutions/cses-1081.mdx

done._
added comments, improved formatting, etc.

revamped some code

---

solutions/usaco-526.mdx

Add Python Solution for "Censoring (Bronze)" in "Simulation" Module

---

solutions/usaco-1059.mdx

Added C++ code for Do You Know Your ABCs? -bronze problem in usaco-1059.mdx
done._

Added C++ code in usaco-1059.mdx

---

content/2_Bronze/Intro_Sets.mdx
content/4_Gold/Unordered_Map.mdx

Add Unordered Sets + fix maps iteration section (Java & C++)

---

content/5_Plat/Convex_Hull.mdx

fixed typo

---

content/4_Gold/Intro_DP.mdx

python support for intro dp

---

content/4_Gold/String_Hashing.mdx

done._
thinking of rewriting the solutions but that would take way too long given my iq

hashing python

---

solutions/usaco-1061.mdx

Wrote solution (with comments) in C++ for Stuck in a Rut.
done._

Solution in C++ for Stuck in a Rut (usaco-1061)

---

solutions/usaco-971.mdx

Floyd-warshall runs in M^3
done._

Fix time complexity in editorial of Moortal Cowmbat

---

content/1_General/Adding_Solution.mdx
content/1_General/Debugging_General.mdx

Revamp of Debugging General + Adding Solution

---

solutions/usaco-969.mdx

kinda late but merry christmas/happy holidays!
also, i set the time complexity to harry's solution: his sol checks a constant number of candidates, while i check m.
let me know if i should change this or set separate time complexities. (i thought this might be confusing)
---
done._

Add C++ Solution + Editorial to Milk Pumping (Gold)

---

content/extraProblems.json
src/components/Dashboard/DashboardProgress.tsx
src/components/markdown/ProblemsList/DivisionList/DivisionList.tsx
src/components/markdown/ProblemsList/ProblemsList.tsx

`/general/usaco-monthlies`
Add some tags, allow showing all problems.
done._

Monthly Table Revamp

---

solutions/usaco-839.mdx

Add semicolon and avoid macro conflicts

---

solutions/usaco-831.mdx

Add Java solution using Sets to usaco-831

---

content/5_Plat/DC-SRQ.mdx

D&C SRQ - fix typo

---

solutions/usaco-1059.mdx

add python solution

---

src/components/markdown/ProblemsList/ProblemsListItem.tsx
src/components/markdown/ProblemsList/ProblemsListItemDropdown.tsx
src/hooks/useUserSolutionsForProblem.tsx

previously loading every solution for every problem actually used up a lot of firebase reads. this lazy loads them so that users have to click the dropdown before the solutions will be loaded.

Fix: lazy load solutions

---

content/3_Silver/DFS.problems.json
content/4_Gold/Conclusion.problems.json
content/4_Gold/DP_Ranges.problems.json
content/4_Gold/DP_Trees.problems.json
content/4_Gold/LIS.problems.json
solutions/usaco-718.mdx

Add December Problem Requests and improve Cow Cross II Solution

---

solutions/usaco-834.mdx

Out of Sorts

---

solutions/dmoj-rank.mdx

Add solution to DFS Silver

---

solutions/usaco-807.mdx

Add Java Solution to USACO-807

---

content/4_Gold/Modular.problems.json
solutions/cses-1095.mdx

sorry for the lack of prs. ( had a lot of homework :((( )
---

Add C++ Solution + Editorial to Exponentiation II (Gold)

---

.github/PULL_REQUEST_TEMPLATE.md
content/1_General/Fast_IO.mdx
content/1_General/Input_Output.mdx
src/mdx-plugins/rehype-snippets.js

- Reworded some things around Kattio, moved up mention of Fast I/O module
- Fixed typo in PR template
- VSCode apparently decided to adjust the spacing

Rearranged Java I/O

---

content/1_General/Practicing.mdx
content/1_General/faq.mdx

add note re: training pages

---

content/3_Silver/DFS.problems.json
content/extraProblems.json
solutions/usaco-1159.mdx

Java solution for connecting two barns

---

content/1_General/Fast_IO.mdx

Replaced both example problems with a simpler one and timed them on the USACO servers. 
Caveat: it's not possible to submit to this.

rewrite fastio

---

content/1_General/Debugging_General.mdx

Debugging General - reword parts relating to undefined behavior

---

content/2_Bronze/Conclusion.problems.json
solutions/usaco-790.mdx

Added At Large Solution + Added Bronze Conclusion Problems

---

solutions/usaco-863.mdx

the difficulty inflation...
---

Add C++ Solution + Editorial to Teamwork (Gold)

---

content/1_General/Adding_Solution.mdx
src/components/TopNavigationBar/TopNavigationBar.tsx

Contact Us button fix

---

content/2_Bronze/Intro_Sets.problems.json
solutions/usaco-687.mdx

Fixed Not Last Solution

---

content/2_Bronze/Intro_Sets.problems.json
solutions/ac-MadeUp.mdx

made up solution

---

solutions/cf-863B.mdx

kayaking py

---

solutions/usaco-1159.mdx

Update Connecting Two Barns Sol

---

content/4_Gold/Shortest_Paths.problems.json
solutions/usaco-899.mdx

comments really bad this time 😖 
---

Add C++ Solution + Editorial to Shortcut (Gold)

---

content/3_Silver/Sorting_Custom.problems.json
solutions/usaco-834.mdx

Make Out of Sorts Solution Show Up on Website

---

content/2_Bronze/Rect_Geo.mdx

a little bug in python sample

---

content/1_General/Contributing.mdx

new discord link

---

content/2_Bronze/Complete_Rec.problems.json

think enough people agreed that it was a crap problem

removed wormhole

---

content/5_Plat/Geo_Pri.problems.json
solutions/ys-SortPointsByArgument.mdx

Thanks to Dustin Miao's solution!

Added solution for ys-SortPointsByArgument

---

content/4_Gold/BFS.problems.json

Fix the title of the problem 

---

src/components/TopNavigationBar/TopNavigationBar.tsx

added workshop banner for today

added USACO January workshop banner

---

solutions/ceoi-10-AHugeTower.mdx

Update ceoi-10-AHugeTower.mdx because official solution's explanation doesn't go in-depth

---

content/3_Silver/DFS.problems.json
content/extraProblems.json

Added Cereal 2 to DFS Module

---

content/3_Silver/DFS.problems.json
content/extraProblems.json
solutions/ceoi-10-AHugeTower.mdx
solutions/usaco-857.mdx
src/components/TopNavigationBar/TopNavigationBar.tsx

back n forth sans

---

solutions/cses-1093.mdx

ive been so inconsistent lately
---

Add C++ Solution + Editorial to Two Sets II (CSES)

---

content/4_Gold/MST.mdx
content/4_Gold/MST.problems.json

python implementation

---

.github/workflows/build-tests.yml
.github/workflows/test.yml
content/4_Gold/MST.problems.json

Seems like tests didn't run on https://github.com/cpinitiative/usaco-guide/pull/2558? Not sure if they will on this one
Resolves build in #2562?

Fix Metadata for Road Reparation

---

content/2_Bronze/Rect_Geo.mdx

bruh for some reason a code link didn't even link to the right place

rect geo crap

---

content/1_General/Contributing.mdx

fix link *again*

---

content/6_Advanced/Persistent.mdx

fix pseg link

---

content/6_Advanced/Segtree_Beats.mdx

Fixed Typo in Segment Tree Beats Module

---

solutions/usaco-860.mdx

Added c++ solution for Mooyoo Mooyoo (USACO 860)

---

content/2_Bronze/Conclusion.problems.json
content/4_Gold/Conclusion.problems.json
content/extraProblems.json

Added Problems to Conclusion Modules

---

content/extraProblems.json
solutions/usaco-1187.mdx

Tests for haybale c++ solution

---

solutions/usaco-944.mdx

Add cpp solution to usaco-944

---

content/4_Gold/Intro_DP.mdx
content/4_Gold/Intro_DP.problems.json
solutions/cf-1418C.mdx

imma throw the next contest...
---

Add C++ Solution + Editorial to Mortal Combat Tower (Gold)

---

solutions/usaco-899.mdx

Shortcut sol

---

solutions/usaco-740.mdx

Added c++ solution for Where's Bessie (usaco-740)

---

content/4_Gold/PURS.mdx

Problems may have more than one correct output as of January 2022, as confirmed by benq on discord.

Remove misleading hint

---

solutions/cses-1158.mdx

Add C++ code to cses-1158

---

content/4_Gold/Sliding_Window.mdx

Python Sliding Window Solution

---

src/functions/src/submitContactForm.ts

Add URL to Contact Form

---

content/4_Gold/TopoSort.mdx
content/4_Gold/TopoSort.problems.json

python implementation for topo sorting

---

content/4_Gold/TopoSort.problems.json

revert solution metadata

---

content/2_Bronze/Conclusion.problems.json
content/4_Gold/Intro_Bitwise.problems.json
content/extraProblems.json
problemsList.ts

brute force -> complete search tag

---

content/3_Silver/Sorting_Custom.mdx

Add Warning Block to Sorting Custom

---

content/4_Gold/DP_Bitmasks.problems.json
solutions/ys-MaxIndepSet.mdx

Add C++ Solution for Max indep set

---

content/4_Gold/Intro_DP.problems.json
solutions/usaco-815.mdx

Add different C++ solution for usaco-815

---

solutions/usaco-739.mdx

python too slow, i tried everything

bovine genomics stuff

---

content/3_Silver/DFS.problems.json
solutions/cc-AMONGUS2.mdx

Add C++ Solution + Editorial to Among Us (Silver)

---

solutions/ys-MaxIndepSet.mdx

---
use \ instead of / 
[src](https://en.wikipedia.org/wiki/Complement_(set_theory)#Relative_complement)

fix set-difference symbol

---

src/styles/generalStyles.css

feat: turn img background color to gray in dark mode

---

content/5_Plat/2DRQ.mdx

since this isn't submittable (https://forum.usaco.guide/t/where-to-find-and-submit-to-usaco-camp-problems/2761)

comment out camp problem

---

solutions/usaco-893.mdx

guess that animal sans

---

content/6_Advanced/Segtree_Beats.mdx
solutions/cses-1081.mdx
solutions/cses-1644.mdx
solutions/usaco-856.mdx
solutions/usaco-993.mdx

Fixed a few typos

---

solutions/usaco-858.mdx

sorry java people, i couldn't save you...
---

Add Explanation + C++ Solution for Convention (Silver)

---

solutions/usaco-963.mdx

cow gymnastics sans

---

content/4_Gold/DP_Bitmasks.problems.json
solutions/ceoi-19-AmusementPark.mdx

Add solution to ceoi19-amusementpark

---

README.md

updated application link in readme

---

solutions/usaco-569.mdx

sorry jesse, basically rewrote your entire thing

bad milk sans

---

solutions/usaco-689.mdx

cow tipping

---

content/4_Gold/DP_Trees.problems.json
solutions/cf-1528A.mdx

Add C++ Solution + Editorial to Parsa's Humongous Tree (Gold)

---

src/components/TopNavigationBar/TopNavigationBar.tsx

Add banner for US Open workshop

---

content/3_Silver/Intro_Tree.mdx

just chap 14

---

solutions/usaco-616.mdx

cbarn support

---

src/pages/index.tsx

Update copyright year

---

solutions/usaco-617.mdx

load balancing bronze

---

solutions/usaco-898.mdx

Add BIT sol for Sleepysort

---

solutions/usaco-917.mdx

traffic sans

---

content/3_Silver/DFS.problems.json
solutions/usaco-1206.mdx

add usaco-1206 solution

---

src/components/TopNavigationBar/TopNavigationBar.tsx

remove promo for open

---

content/3_Silver/More_Prefix_Sums.mdx
content/3_Silver/More_Prefix_Sums.problems.json
content/3_Silver/Sorting_Custom.problems.json
solutions/cses-1163.mdx
solutions/usaco-1063.mdx

addressed some issues

---

content/2_Bronze/Conclusion.problems.json
solutions/usaco-1181.mdx

uhh hey its me again hopefully this PR isn't as bad of a trainwreck as last time lol

add usaco-1181 solution

---

solutions/ac-MultipleOf2019.mdx

Explanation added for Multiples of 2019 Atcoder

---

src/pages/index.tsx

separate sponsors into different tiers

---

content/2_Bronze/Intro_Complete.problems.json
content/extraProblems.json
solutions/usaco-1228

usaco-1228 nlogn solution

---

solutions/ac-GCDOnBlackboard.mdx

Java Solution for gcd on blackboard

---

solutions/usaco-894.mdx

grass planting sans

---

content/3_Silver/Prefix_Sums.mdx

Updated the mod equation at one of the quizes

---

content/2_Bronze/Rect_Geo.mdx
content/4_Gold/Stacks.problems.json
content/6_Advanced/Lagrange.mdx
content/extraProblems.json
solutions/usaco-1162.mdx

should close #2593 
should also close #2647 
finally, should close #2535

more issue addressing

---

content/4_Gold/Intro_DP.problems.json
solutions/usaco-673.mdx

you don't know how long i spent debugging to realize that i got the modulus wrong...
\+ im kinda tired so this editorial might not be the best, ill proofread tomorrow
---

add c++ solution to team building (plat)

---

content/3_Silver/More_Prefix_Sums.mdx
content/3_Silver/Two_Pointers.mdx

Two pointer implementation

---

content/1_General/Adding_Solution.mdx
content/4_Gold/String_Hashing.problems.json
solutions/cses-1163.mdx

final(?) issue batch

---

solutions/usaco-719.mdx

add cpp solution + editorial for circlecross (gold)

---

content/4_Gold/LIS.mdx
solutions/cses-1163.mdx
solutions/usaco-831.mdx

tttt python and an issue

---

content/6_Advanced/DP_More.mdx
content/6_Advanced/DP_More.problems.json

- [DONE] I have tested my code.
- [DONE] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [DONE] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 

Knuth's optimization description and sample problems

---

solutions/usaco-990.mdx

add python solution 990

---

content/4_Gold/Sliding_Window.problems.json
solutions/usaco-767.mdx

it is spring break and im bored

usaco-767 C++ Implementation

---

solutions/cses-2422.mdx

Adding solution for video purposes

Add Python Solution to CSES Multiplication Tables

---

solutions/usaco-1228.mdx

Add Python Solution for Counting Liars (1228)

---

content/6_Advanced/DP_More.mdx

Fix Parquet Explanation

---

src/components/ProblemSolutions.tsx

Sort Public Subissions By User Langauge

---

.github/workflows/build-tests.yml

fix `pub` not found

---

content/3_Silver/Intro_Sorted_Sets.problems.json
solutions/cf-862E.mdx

Add C++ Solution + Editorial to Mahmoud and Ehab and the Function (Silver)

---

solutions/usaco-715.mdx

add python solution for Why Did the Cow Cross the Road II (715)

---

content/2_Bronze/Ad_Hoc.problems.json
solutions/usaco-737.mdx

add python solution for modern art (737)

---

content/4_Gold/Divisibility.mdx

add python implementation

---

content/2_Bronze/Simulation.mdx

change python solution for mixing milk

---

content/extraProblems.json
solutions/cses-1631.mdx

add cses-1631 solution

---

solutions/usaco-987.mdx

add python solution for word processor (987)

---

content/4_Gold/DP_Ranges.problems.json
content/4_Gold/Faster_Hash.problems.json
solutions/usaco-994.mdx

Solve3sum sol

---

content/5_Plat/Binary_Jump.mdx

LCA implementation

---

solutions/usaco-574.mdx

add python solution for fruit feast (574)

---

solutions/usaco-1228.mdx

sans if you're just going to change my variable names at least make it right lmao

minor syntax fix in usaco-1228

---

solutions/usaco-620.mdx

For the self-study video for this problem

Add Python Code for DFS Solution (620)

---

content/2_Bronze/Intro_Graphs.mdx

Before, both answers were marked as correct. This pull request makes false an incorrect answer, since true is the correct answer.

Fix true/false in question 6 of the Check Your Understanding on Introduction to Graphs

---

content/3_Silver/Conclusion.problems.json
content/4_Gold/BFS.problems.json
content/4_Gold/DP_Ranges.problems.json
content/4_Gold/Shortest_Paths.problems.json
content/5_Plat/Binary_Jump.problems.json
content/6_Advanced/SCC.problems.json

add a few cool problems

---

solutions/usaco-619.mdx

load balancing silver

---

solutions/usaco-691.mdx

add python solution for 691

---

content/4_Gold/Combinatorics.mdx

Add Combo module

---

solutions/cses-1641.mdx

add python solution to cses-1641.mdx

---

content/3_Silver/Binary_Search.problems.json

Reverts cpinitiative/usaco-guide#2797
see https://github.com/cpinitiative/usaco-guide/pull/2797#issuecomment-1133972144

Revert "Update Binary_Search.problems.json"

---

src/functions/src/cpiclasses/utils/permissions.ts

update finaid perms

---

content/3_Silver/Greedy_Sorting.problems.json
solutions/cf-321B.mdx

add cpp sol for ciel and duel (silver)

---

solutions/usaco-673.mdx

add java solution usaco-673

---

content/5_Plat/Binary_Jump.problems.json
solutions/cf-609E.mdx

the official editorial doesn't provide a sample code

CF-609E C++ Solution

---

solutions/usaco-811.mdx

add python solution for snow boots, silver (811)

---

solutions/usaco-1181.mdx

Adding Python Solution for Drought (1181)

---

content/4_Gold/DP_Bitmasks.problems.json
solutions/usaco-494.mdx

add c++ solution to guard mark (gold)

---

solutions/usaco-1084.mdx

comments & stuff

---

content/4_Gold/BFS.problems.json
solutions/ac-SmallMultiple.mdx

c++ small multiple

---

announcements/Groups Open To Public.mdx
src/components/Groups/GroupSelectPage/GroupSelectPage.tsx
src/components/TopNavigationBar/TopNavigationBar.tsx

Open groups access to everyone

---

content/4_Gold/Shortest_Paths.problems.json
solutions/cf-1627E.mdx

cf-1627E :blobreach:

---

solutions/usaco-944.mdx

The c++ code showed up with the java solution.

Fixed usaco-944.mdx

---

solutions/usaco-737.mdx

modern art

---

content/5_Plat/Bitsets.problems.json
solutions/cses-2138.mdx

cses 2138 uwu

---

solutions/usaco-860.mdx

add python solution for mooyo mooyo (860)

---

solutions/cses-2079.mdx

add java solution cses-2079

---

solutions/usaco-896.mdx

add python solution for mountain view (896)

---

solutions/usaco-807.mdx

- USACO 807 CPP Solution added
<hr>
- [ x ] I have tested my code.
- [ x ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ x ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 

usaco-807: CPP Solution added

---

content/3_Silver/Binary_Search.mdx
content/4_Gold/LIS.mdx
content/4_Gold/Sliding_Window.mdx
solutions/cf-1117C.mdx
solutions/lc-FindPivotIndex.mdx
solutions/lmio-19-triusis.mdx
solutions/usaco-1181.mdx
solutions/usaco-619.mdx
solutions/usaco-689.mdx
solutions/usaco-737.mdx
solutions/usaco-831.mdx
solutions/usaco-859.mdx

i was reading [this type annotation PEP](https://peps.python.org/pep-0585/) and realized i've been getting type annotations wrong
so i ctrl f'd and tried to fix all of them

fix type annotations and convention ii

---

content/4_Gold/DP_Bitmasks.problems.json

Add Burza editorial link

---

gatsby-config.ts
src/components/Groups/EditPostPage/EditPostPage.tsx
src/components/Groups/Feedback.tsx
src/components/Groups/GroupLeaderboardPage/GroupLeaderboardPage.tsx
src/components/Groups/JoinGroupPage.tsx
src/components/Groups/LeaderboardTable/LeaderboardTable.tsx
src/models/groups/posts.ts
src/pages/groups/[...].tsx
vercel.json

Groups fixes

---

content/6_Advanced/String_Search.problems.json

Add some trie problems from Codeforces

---

content/5_Plat/Centroid.problems.json
content/5_Plat/Merging.problems.json
solutions/ioi-11-race.mdx

Small-to-Large Merging Solution and Editorial for IOI Race

---

solutions/usaco-736.mdx

Create Python Solutions (And fix existing ones) for Bovine Genomics

---

content/4_Gold/Combinatorics.mdx
content/4_Gold/Combinatorics.problems.json
content/extraProblems.json

Edit Combinatorics to be More Thorough.

---

solutions/usaco-856.mdx

Add Python Solution to Bucket List

---

solutions/cses-2428.mdx

Added Python Solution for cses-2428(Subarray Distinct Values)

---

content/6_Advanced/Offline_Del.problems.json
solutions/ys-PersistentUnionFind.mdx

persistent dsu ys

---

solutions/cses-2428.mdx

cses-2428 C++ solution added

---

solutions/cses-1639.mdx

The code gave wrong output due to missing brackets(operator precedence). I added brackets on line 101 to debug the cpp code, now it works fine

CPP code didn't work

---

solutions/usaco-1017.mdx
solutions/usaco-717.mdx

added cpp solution to usaco-717

---

solutions/cf-20C.mdx

Added python solution to cf-20C (Dijkstra?)

---

solutions/usaco-670.mdx

ryan attempts to clean up code for cow checklist (gold)

---

solutions/cses-1082.mdx

cses divisor sum?

---

content/1_General/Running_Code_Locally.mdx
solutions/cf-1279D.mdx

closes #2909 and also closes #2901

two issues

---

solutions/usaco-831.mdx

C++ code to usaco-831.mdx

---

content/1_General/Data_Types.mdx

I have removed a double "the" from line 40 in `Data_Types.mdx` file.

remove a double "the" from line 40

---

content/4_Gold/DP_Ranges.mdx

Added python code for Space Jazz in DP_Ranges.mdx

---

solutions/cf-847B.mdx

Added python solution to cf-847B

---

content/authors/authors.ts

Simply added a small fix for Darren and a highlight to Andi that he's too humble to put up himself 🙂

Small author changes

---

content/5_Plat/Matrix_Expo.mdx

Updated Matrix_Expo.mdx with python code

---

content/4_Gold/String_Hashing.problems.json
solutions/ceoi-17-PalindromicPartitions.mdx

palindromic partitions yo

---

solutions/cses-1745.mdx

------
Adding a C++ solution to the problem cses-1745 ([Money Sums](https://cses.fi/problemset/task/1745)), the code has been inspired by the Java version, and I used the same comment for the Java one.

Add C++ solution to cses-1745

---

solutions/usaco-834.mdx

add python solution for out of sorts (834)

---

content/5_Plat/Binary_Jump.mdx
src/mdx-plugins/rehype-snippets.js

Added Tarjan LCA sol

---

solutions/usaco-573.mdx

C++ code added 

---

content/4_Gold/Stacks.problems.json
solutions/ceoi-11-bal.mdx

_If any of the below doesn't (?) apply to this Pull Request, mark the checkbox as done._
Judge Result:
https://oj.uz/submission/604111
https://oj.uz/submission/604103

Add internal solution for ceoi-11-bal (Balloons) with cpp and java code [ceoi11]

---

content/4_Gold/MST.problems.json
solutions/usaco-1211.mdx
solutions/usaco-717.mdx

Added internal solution for usaco-1211 Moo Networks

---

content/4_Gold/Sliding_Window.mdx

I think cpalgo explained the method quite well. But if u wish to have a short explanation of the method, I could write some. 
---

Add two stacks method to sliding window section

---

solutions/usaco-666.mdx

usaco 666 solution

---

solutions/cses-1161.mdx

Fix broken link in CSES-1161 solution

Fix broken link in CSES-1161 solution

---

content/4_Gold/Combinatorics.mdx

Close #2961.
Gotten accepted on a [straightforward stars and bars problem](https://www.hackerrank.com/challenges/k-candy-store/problem) after fixing the bug
and have run the project locally
Also, some `nCr` were changed to `nCk` when `k` was used.

Fix Pascal's triangle DP

---

README.md
content/1_General/Contributing.mdx

fixed discord server link #2968

---

content/6_Advanced/String_Search.mdx

Update String_Search.mdx, added the missing semi-colon

---

solutions/cses-1662.mdx
solutions/cses-2132.mdx

added python code to cses 1662

---

content/4_Gold/Divisibility.problems.json

Fix typo in Gold/Divisibility

---

content/4_Gold/DP_Ranges.problems.json
solutions/cf-245H.mdx

cf 245h yo 🤡 

---

content/4_Gold/Intro_DP.problems.json
content/extraProblems.json
solutions/usaco-1185.mdx

qwq
i added it in the `intro-dp` section, should it be changed?
---

add cpp sol + editorial to drought (gold)

---

solutions/cf-1418C.mdx

fix: rename overriden var i in cpp
style: make variable naming in expl and cpp code consistent
feat: add java implementation
--- 

Improve consistency and add java implementation for MortalKombatTower (CF1418C)

---

solutions/usaco-940.mdx

Added CPP solution for usaco-940

---

content/4_Gold/String_Hashing.problems.json
solutions/cf-1056E.mdx

Add internal solution for Check Transcription (cf1056e)

---

content/4_Gold/String_Hashing.problems.json
solutions/cses-1733.mdx

some cses string hashing problem 

---

content/4_Gold/PURS.mdx

segtree update

---

solutions/usaco-987.mdx

fixed the word processor thing

---

content/6_Advanced/String_Search.problems.json
solutions/ys-SetXORMin.mdx

set xor min trie thingy

---

solutions/cses-1734.mdx

Rewrite explanation, refactor CPP and (gonna) add Java for Distinct Values Queries (CSES1734)

---

content/5_Plat/Conclusion.problems.json
solutions/joi-19-cake-circle.mdx

Added solution for "JOI - Cake Circle"

---

content/extraProblems.json
solutions/cf-1702E.mdx

Add cf1702e

---

content/4_Gold/PURS.mdx

Python code for BIT and Segment Tree

---

content/4_Gold/PURS.mdx

Added my name to changes made in #3012 

Attribution

---

solutions/cses-1634.mdx

add python solution cses-1634

---

solutions/cses-1753.mdx

Updated cses-1753(KNP) with Python Code

---

content/4_Gold/Intro_DP.problems.json
solutions/usaco-622.mdx

Add internal solution for Circular Barn Revisited (usaco622)

---

solutions/usaco-966.mdx

Update usaco-966.mdx with cpp code

---

solutions/usaco-992.mdx

Fix USACO 992

---

solutions/usaco-991.mdx

Updated usaco-991.mdx with Python Code

---

content/1_General/Input_Output.mdx

Clarify that method 2 is the recommended method of performing Java I/O in a USACO contest, and that it is okay to refer to it in-contest. Motivated by https://forum.usaco.guide/t/input-and-output-in-java/3373

Java I/O Note

---

README.md
solutions/usaco-1210.mdx

- [_] I have tested my code.
- [_] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [_] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 

Added python solution for usaco-1210

---

content/4_Gold/Combinatorics.mdx
content/4_Gold/Combinatorics.problems.json

Added Section to "Gold - Combinatorics"

---

solutions/cses-1757.mdx

add java solution to cses 1757

---

solutions/usaco-1037.mdx

Add usaco 1037 cpp solution

---

solutions/usaco-619.mdx

rewrite the pos_of_interest function in a cleaner way.

Refactor usaco 619 cpp solution

---

content/4_Gold/MST.problems.json
solutions/usaco-623.mdx

cpp solution for usaco-623

---

solutions/usaco-964.mdx

Add usaco 964 cpp solution

---

solutions/usaco-718.mdx

Changed c++ code. id1 and id2 are now 1 indexed, and added missing opening bracket.

Issue #3047

---

solutions/usaco-966.mdx

Updated usaco-966.mdx with Java Code

---

solutions/usaco-1018.mdx

Added Python code in usaco-1018.mdx

---

solutions/coci-21-sjeckanje.mdx

add external solution to coci thing

---

solutions/usaco-944.mdx
src/models/problem.ts

python sol fenceplan

---

content/2_Bronze/Simulation.problems.json

Correct problem name

---

.github/PULL_REQUEST_TEMPLATE.md

Fix grammar and consise-ify PR template

---

solutions/cf-1398C.mdx

good subarrays patch

---

solutions/usaco-786.mdx

lifeguard patch

---

solutions/usaco-763.mdx

measurement patch

---

solutions/usaco-763.mdx

measurement patch 2

---

solutions/usaco-669.mdx
solutions/usaco-787.mdx

rental & moocast patch

---

solutions/cf-1117C.mdx
solutions/cf-847E.mdx

fix my old sols

---

content/3_Silver/Sorting_Custom.problems.json
solutions/usaco-967.mdx

meeting solution

---

solutions/cses-2079.mdx

Updated cses-2079 with python code.

---

solutions/usaco-1230.mdx

Fix strange indentation of the cpp code;
Add some comments and renamed some variables;
Add java implementation;
<del>TODO: add explanation</del> Done

Add explanation, refactor CPP and add Java code for Visits (usaco1230)

---

solutions/usaco-620.mdx

added python solution to Milk Pails (620)

---

solutions/usaco-416.mdx

lazy patch

---

solutions/usaco-834.mdx

sorting patch

---

solutions/usaco-716.mdx

countcross patch

---

solutions/usaco-664.mdx

Update usaco-664.mdx - Java solution

---

src/components/Groups/ProblemPage/ProblemSubmissionInterface.tsx
src/components/Groups/ProblemPage/ProblemSubmissionsList.tsx
src/components/Groups/ProblemSubmissionPopup.tsx
src/functions/src/groups/submitToProblem.ts
src/hooks/groups/usePostActions.ts
src/models/groups/problem.ts

url submission for non-autogradeable questions

---

src/functions/src/submitProblemSuggestion.ts

change problem suggestion bot credentials

---

content/3_Silver/Flood_Fill.problems.json
content/4_Gold/Conclusion.problems.json
problemsList.ts
solutions/usaco-716.mdx
solutions/usaco-836.mdx
src/context/UserDataContext/properties/problemURLToIdMap.tsx
src/functions/src/submitProblemSuggestion.ts

**someone please tell me if the time complexity is correct**

multiplayer moo patch

---

content/6_Advanced/Segtree_Beats.mdx

Fix bug in pseudocode

---

solutions/usaco-813.mdx

snowboots gold patch

---

solutions/usaco-623.mdx

<sup><sub>my hands will be their hands until im free</sub></sup>
---

fenced in revamp (gold)

---

src/components/TopNavigationBar/TopNavigationBar.tsx

The "Learn more" links to CPI Team Application Form

Add looking for webdevs banner

---

solutions/usaco-991.mdx

loan repayment patch

---

solutions/usaco-968.mdx

milkvisits patch

---

solutions/dmoj-bots.mdx

Fix typo in DMOJ bots solution

---

src/functions/src/groups/submitToProblem.ts

fixes https://github.com/cpinitiative/usaco-guide/issues/3122

use empty string if display name is undefined

---

solutions/usaco-671.mdx

Add python solution to usaco: lasers and mirrors

---

solutions/usaco-992.mdx

every day is leg day when you're running from your problems

wormsort patch

---

content/1_General/Generic_Code.mdx

Pass container by reference to sz() function

---

content/5_Plat/Convex_Hull_Trick.problems.json
solutions/cses-2087.mdx

Solution for CSES Houses and Schools

---

solutions/usaco-987.mdx
solutions/usaco-991.mdx

added video?

---

content/4_Gold/PURS.mdx

Fix link in PURS

---

solutions/usaco-790.mdx

add python solution for usaco: cow at large (790)

---

solutions/usaco-788.mdx

someone please help with the silver implementations i'm dying here

mootube patch

---

solutions/usaco-668.mdx

moocast patch

---

content/6_Advanced/Flow_LB.problems.json

Fixed Broken Link

---

solutions/usaco-896.mdx

mountain patch

---

content/ordering.ts

ty @izhang05 for the suggestion!
---

reorder modules

---

content/5_Plat/Range_Sweep.problems.json
content/5_Plat/Segtree_Ext.problems.json
solutions/usaco-624.mdx

Add segment tree solution with cpp and java implementation. 
Refactor the binary search solution. 
Add explanations. 

Add segment tree solution for Load Balancing (usaco 624) 

---

solutions/usaco-923.mdx

HOW DID THE REVIEWERS NOT CATCH THIS

---

solutions/usaco-714.mdx

helpcross patch

---

solutions/usaco-714.mdx

oh no forgot tabs

---

solutions/usaco-663.mdx

add video for square pasture

---

solutions/usaco-783.mdx

video for blocked billboard 2

---

solutions/usaco-1059.mdx

video for do yk your abcs

---

src/components/TopNavigationBar/TopNavigationBar.tsx

remove mobile-only announcement

---

src/components/TopNavigationBar/TopNavigationBar.tsx

add looking for problem writers

---

content/6_Advanced/Extend_Euclid.mdx

Extend_Euclid.mdx add java and simplify

---

solutions/usaco-785.mdx

added video solution to usaco-785

---

solutions/usaco-917.mdx

added video solution to usaco-917

---

solutions/usaco-526.mdx

added video solution to usaco-526

---

solutions/cses-1676.mdx
solutions/usaco-646.mdx

add solutions and editorials to usaco-646 and cses-1676

---

solutions/usaco-646.mdx

c++ -> closing the farm (gold) 

---

solutions/usaco-810.mdx

reststops python
