cpinitiative/usaco-guide

CONTRIBUTING.md, content/1_General/Working_MDX.mdx, src/components/markdown/LanguageSection.tsx, src/components/markdown/MDXComponents.tsx
=> add one-lang-only components

solutions/usaco-736.mdx
=> cownomics patch

solutions/usaco-647.mdx
=> 248, c++, gold

solutions/usaco-1061.mdx
=> added video solution to usaco-1061

solutions/cf-702C.mdx, solutions/cf-782b.mdx, solutions/cses-1085.mdx, solutions/usaco-1038.mdx, solutions/usaco-594.mdx, solutions/usaco-969.mdx
Add editorial and python solution to usaco: Angry Cows
Add 1 editorial and 1 python solution to cf: Cellular Network
Add editorial and python solution to usaco: Social Distancing
Add python solution to cses: Array Division
Add python solution to cf: The Meeting Place Cannot be Changed
Add python solution and clean up usaco: Milk Pumping
I had the python docstrings already from months ago so I decided to keep them in
=> add a few solultions and editorials

solutions/cses-1682.mdx
=> Add py solution to Flight Routes Check cses-1682

content/4_Gold/Stacks.mdx
=> Add py solution to Nearest Smallest Value in Stacks module

content/6_Advanced/SCC.mdx
=> added tutorials for 2-SAT

solutions/usaco-740.mdx
=> where patch

solutions/cf-839C.mdx
=> Add py code to CF: Journey

solutions/cf-1365D.mdx
=> Add py code to CF: Solve the maze

solutions/cses-1751.mdx
=> Add python solution to cses: Planets Cycle

solutions/cses-1636.mdx
=> Add python solution to cses: Coin Combinations II

solutions/usaco-1062.mdx
=> Edit python solution in usaco: Cowtaigon to more follow styleguide

solutions/cses-1093.mdx
=> Add python solution to cses: Two Sets II

solutions/usaco-1013.mdx
sleigh bells  jingling, ring ting ting a ling
---
=> vid sol swap

solutions/usaco-940.mdx
its beginnning to look al ot like christmast
---
=> milk factory uwu

solutions/usaco-833.mdx
=> family tree

solutions/usaco-569.mdx, solutions/usaco-616.mdx, solutions/usaco-665.mdx, solutions/usaco-736.mdx, solutions/usaco-893.mdx, solutions/usaco-939.mdx, solutions/usaco-963.mdx
=> a couple videos

solutions/usaco-568.mdx, solutions/usaco-619.mdx, solutions/usaco-739.mdx, solutions/usaco-857.mdx, solutions/usaco-965.mdx
=> hoodie grind #1

solutions/cf-1216C.mdx
have a holly jolly christmas
---
=> white sheet

solutions/cses-1625.mdx
=> grid paths

content/4_Gold/String_Hashing.problems.json, solutions/coci-16-zamjene.mdx
=> zamjene sol

solutions/usaco-894.mdx
=> grass planting

content/1_General/Basic_Debugging.mdx, content/1_General/Debugging_Checklist.mdx
Adds redirects for links broken by #3172.
=> debugging redirects

solutions/usaco-920.mdx
=> revegetate

solutions/usaco-591.mdx
=> rpaormotion countnig

solutions/usaco-809.mdx
=> tamigna thte herd

solutions/usaco-810.mdx
=> went and bought pop for the lonely sunsets

solutions/usaco-915.mdx
=> sleeppyppy cow ehrard

solutions/usaco-1088.mdx
=> hoodie pls

solutions/usaco-989.mdx
=> more than fun, you're the sanctuary

solutions/usaco-946.mdx
- add explanation for sol1 (Prim's algorithm)
- add code for sol 1
- add explanation for sol 2
- rewrite code for sol 2 to make it human-readable [done]
- maybe some small style fix for sol 3
---
=> Add solution to I Would Walk 500 Miles (usaco-946)

solutions/usaco-713.mdx
=> so tell me, am i crazy?

solutions/usaco-104.mdx
- [✔] I have tested my code.
- [✔] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [✔] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
=> added python code

content/1_General/Choosing_Lang.mdx
- [ ✓] I have tested my code.
- [ ✓] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ✓] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
=> Added python solution for Wormhole Sort

content/4_Gold/String_Hashing.problems.json, solutions/baltic-18-genetics.mdx, solutions/usaco-595.mdx, solutions/usaco-920.mdx
still have to write an editorial
=> initialize genetics solution

solutions/usaco-761.mdx
shorten and remove unnecessary hardcoding of cows' names
resolves https://forum.usaco.guide/t/intersol-for-milk-measurement/3716
=> simplify milk measurement bronze

solutions/usaco-669.mdx, solutions/usaco-894.mdx
=> moocast gold

content/3_Silver/Flood_Fill.mdx
This optimization is helpful as it allows some problems to be passed using python without a TLE (for example USACO Icy Perimeter TC 10). However, I'm not really sure how we are supposed to add text to only show up to a specific language so I just did what works.
=> Add part detailing python optimization to FloodFill

content/4_Gold/DP_Bitmasks.mdx, content/4_Gold/Shortest_Paths.mdx
bitmask dp up (there has been a bitmask DP problem each of the last two years, which is more frequent than any other of the categories currently marked "rare"), shortest path down (can't remember the last time we had a Dijkstra problem). there may be other topics also worth updating, suggestions are welcome.
=> Update Gold Topic Frequencies

content/2_Bronze/Time_Comp.mdx
=> Time Complexity

src/components/Editor/EditorPage.tsx, src/components/Editor/MainEditorInterface.tsx, src/components/Editor/editorUtils.ts
Closes #3244. Also modified `editorUtils.ts` not to make an unnecessary request.
=> fix editor loading

solutions/usaco-619.mdx
Reverts #3038 (which was incorrect) and closes #2793.
=> Revert load balancing silver and tweak explanation

content/2_Bronze/Complete_Rec.mdx
=> update complete rec

src/components/ProblemsPage/ProblemHits.tsx
Adds status, removes "View Problem Statement" (since you can already click on the title of the problem to view the problem statement).
=> Revise ProblemHits

content/2_Bronze/Intro_Complete.problems.json, solutions/usaco-1203.mdx
=> Sleeping in Class solution

solutions/cf-860D.mdx
=> remove template from cf-860d

content/4_Gold/All_Roots.mdx, content/4_Gold/All_Roots.problems.json, solutions/usaco-793.mdx
=> fix module, remove fakesolve

content/6_Advanced/Persistent.problems.json, content/6_Advanced/String_Search.problems.json, content/6_Advanced/Treaps.problems.json, src/components/ProblemsPage/Source.tsx, src/models/problem.ts, src/pages/problems.tsx
=> add problem filter by source

solutions/usaco-1228.mdx
=> fix typo in counting liars

solutions/usaco-856.mdx
wow, remember when sathu was a CA?
=> blist redo

content/4_Gold/BFS.problems.json, solutions/usaco-282.mdx
=> Add internal solution for What's Up With Gravity (usaco-282)

src/components/Index/features/ProblemsetsFeature.tsx, src/components/ProblemsPage/ProblemHits.tsx
adds difficulty mentioned in https://github.com/cpinitiative/usaco-guide/issues/86#issuecomment-788536196
=> add difficulty to ProblemHit

solutions/usaco-593.mdx
stupid java and their nonhashable arrays
=> mowing redo

solutions/usaco-664.mdx
=> blocks redo

solutions/usaco-785.mdx
- [N/A] I have tested my code.
- [N/A] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [N/A] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
=> Fixed the time complexity for Out of Place

solutions/usaco-1061.mdx
a pr a day keeps the boredom away
=> stuckrut redo

solutions/usaco-761.mdx
=> measurement redo

content/2_Bronze/Simulation.mdx
=> simulation redo

solutions/usaco-615.mdx
=> pails redo

src/components/TopNavigationBar/TopNavigationBar.tsx
=> blue banner text change

solutions/bronze/usaco-1011.mdx
=> triangles redo

solutions/bronze/usaco-784.mdx
=> lifeguards redo

solutions/bronze/usaco-712.mdx
=> circlecross redo

solutions/bronze/usaco-1203.mdx
=> sleeping in class redo

solutions/bronze/usaco-639.mdx, solutions/bronze/usaco-739.mdx
screw it, added python even though it doesn't get ac
=> cownomics "redo"

src/components/ContactUsSlideover/ContactUsSlideover.tsx, src/functions/src/submitContactForm.ts
- Encourage posting on the forum only for "Unclear Explanation."
- Automatically add labels when a form a submitted (UNTESTED).
=> update contact form, label form submissions

content/2_Bronze/Intro_Sorting.mdx
=> Sorting redo

content/2_Bronze/Intro_Complete.mdx
=> complete search redo

content/1_General/faq.mdx
=> link to additional FAQs

src/components/TopNavigationBar/TopNavigationBar.tsx
=> change announcement for problem review

content/2_Bronze/Intro_Greedy.mdx
According to the module:
> A greedy algorithm never takes back its choices
=> Fix Intro Greedy Quiz Answers

solutions/bronze/usaco-1107.mdx
=> year of the cow redo

content/4_Gold/MST.mdx
=> Refactor cpp code in Gold/MST

src/components/TopNavigationBar/TopNavigationBar.tsx
=> change banner back for recruiting

src/pages/problems.tsx
=> Added pagination and ability to change hit number to problems page

solutions/bronze/usaco-569.mdx, solutions/bronze/usaco-713.mdx
=> cowqueue redo

content/5_Plat/Sqrt.mdx
=> Remove template for plat/sqrt and add Java implementation

content/2_Bronze/Intro_Greedy.problems.json, solutions/bronze/cf-831C.mdx, solutions/bronze/usaco-1227.mdx
=> photoshoot hints

solutions/gold/cses-1757.mdx
=> remove c++ template from cses-1757, add python sol

content/1_General/USACO_Monthlies.mdx, src/components/markdown/ProblemsList/DivisionList/DivisionList.tsx
reverse order of labels, remove link to my sols (outdated)
=> minor divlist updates

content/4_Gold/Shortest_Paths.mdx
added link: https://alexyd88.github.io/Dijkstra-Visualizer/ under O(MlogN) Dijkstra resources
=> Add Dijkstra vis resource

solutions/platinum/cses-1160.mdx
=> Fixed Typo in Planet Queries II Editorial

content/extraProblems.json, solutions/silver/usaco-1254.mdx
=> Add internal solution for Barn Tree (usaco-1254)

solutions/silver/usaco-990.mdx
=> god i want to eat strawberries now

content/1_General/Choosing_Lang.mdx, content/1_General/Input_Output.mdx, content/1_General/Practicing.mdx, content/1_General/Resources_CP.mdx, content/1_General/Working_MDX.mdx, content/1_General/faq.mdx, content/2_Bronze/Intro_Sorting.mdx, content/2_Bronze/Rect_Geo.mdx, content/4_Gold/Hashmaps.mdx, content/4_Gold/String_Hashing.mdx, solutions/advanced/balkan-15-clarkson.mdx, solutions/advanced/poi-05-template.mdx, solutions/gold/cses-1757.mdx, solutions/silver/ac-GCDOnBlackboard.mdx, src/components/Groups/ProblemPage/ProblemSubmissionInterface.tsx, src/components/ProblemSuggestionModal.tsx, src/components/markdown/ResourcesList.tsx, src/models/problem.ts, src/stories/markdown/MarkdownContent.stories.tsx
=> disable USACO problem suggestions for additional practice

content/1_General/Data_Types.mdx, src/components/MarkdownLayout/MarkdownLayout.tsx, src/styles/generalStyles.css
=> add wrapper around overflowing tables

src/components/ProblemsPage/ProblemHits.tsx, src/components/ProblemsPage/Status.tsx, src/models/problem.ts, src/pages/problems.tsx
closes #3264, fixes "appears in" for problems in the USACO monthly table
=> problem search bugfixes

content/3_Silver/Binary_Search.mdx
=> Fixed Incorrect Quiz Question in Binary Search Module

solutions/gold/usaco-623.mdx, solutions/gold/usaco-863.mdx, solutions/gold/usaco-945.mdx
=> Added hints to three problems

src/components/markdown/CodeBlock/CodeBlock.tsx
reverts #775, closes #3462 hopefully
=> revert space -> tab replacement

solutions/gold/usaco-1210.mdx
=> Fixed Latex

solutions/silver/usaco-918.mdx
=> Fix Sleepy Cow Herding time complexity

content/2_Bronze/Intro_Graphs.problems.json
=> change difficulty

solutions/bronze/usaco-857.mdx
=> hints for back and forth, bronze

solutions/bronze/usaco-808.mdx
=> hints for hoofball, bronze

solutions/bronze/usaco-916.mdx
=> hints for revegetate, bronze

solutions/bronze/usaco-737.mdx
=> hint for modern art, bronze

solutions/bronze/usaco-809.mdx
i hope i did it right this time
---
=> hint for taming the herd, bronze

solutions/silver/usaco-416.mdx
This problem is in More on Prefix Sums
=> Add prefix sum solution

src/components/TopNavigationBar/TopNavigationBar.tsx
- [ x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
=> February Contest Workshop banner

content/1_General/Modules.mdx
=> Specify Module and Problem Statuses

content/2_Bronze/Intro_Sets.mdx, content/2_Bronze/Intro_Sorting.mdx, content/4_Gold/Hashmaps.mdx
=> add hashmap hack case generators

.github/workflows/build-tests.yml, .github/workflows/test.yml
If the tests take longer that probably means that the build has stalled indefinitely (see #3506).
=> add timeout limits for workflows

src/components/markdown/ProblemsList/ProblemsListItemDropdown.tsx
should stop excessive firebase reads
=> move view solutions content into separate component

src/context/UserDataContext/UserDataContext.tsx, src/context/UserDataContext/properties/userProgressOnResources.ts, src/context/UserDataContext/userDataPropertyAPI.ts
=> migrate old resource values

src/components/ContactUsSlideover/ContactUsSlideover.tsx, src/functions/src/submitContactForm.ts
=> minor contact form updates

content/3_Silver/Prefix_Sums.mdx
=> change n to uppercase

src/components/markdown/ProblemsList/DivisionList/DivisionList.tsx
=> add space below division buttons

content/4_Gold/Combinatorics.mdx, content/4_Gold/Divisibility.mdx, content/4_Gold/Modular.mdx, solutions/gold/cses-1095.mdx
=> Small fixes for Gold/Math section

solutions/bronze/usaco-831.mdx, src/templates/syllabusTemplate.tsx
=> link to Bronze self-study course

solutions/bronze/usaco-1088.mdx
=> spaced out hint

solutions/bronze/usaco-1084.mdx
=> even more odd photos hint

solutions/gold/cses-1665.mdx
=> more readable code (no templates) + a small addition to sol

solutions/platinum/cf-609E.mdx
=> a minor mistake

content/2_Bronze/Complete_Rec.problems.json, solutions/bronze/usaco-1276.mdx
=> Add internal solution for Air Cownditioning II (usaco-1276)

content/4_Gold/DP_Bitmasks.problems.json, solutions/gold/cf-1043F.mdx, solutions/gold/cf-977F.mdx
don't worry, i'm still active as a CA myself
=> solution for make it one

content/2_Bronze/Intro_Sets.mdx, content/4_Gold/Hashmaps.mdx
tbh making a hack that says "screw you `unordered_set` users" is kind of a bad person move but whatever
=> unordered set warning

content/5_Plat/Centroid.mdx
_If any of the below don't apply to this Pull Request, mark the checkbox as d_If any of the below don't apply to this Pull Request, mark the checkbox as done._one._
=> Added a resource for centroid decomposition

solutions/platinum/cf-660F.mdx
=> Minor Changes in CF660F

content/1_General/Contests.mdx
[Google Code Jam has been discontinued](https://codingcompetitions.withgoogle.com/codejam/). I left the Kickstart link there for the farewell rounds. That will stay up until April 15. However there are no more onsite finals so this should be removed.
=> Google Code Jam discontinued

content/3_Silver/Binary_Search.mdx
=> Add java and py inpl for bin-search quiz

content/3_Silver/Greedy_Sorting.problems.json, solutions/silver/cfgym-102951B.mdx
=> link studying algorithms solution

content/3_Silver/Graph_Traversal.mdx, solutions/gold/cf-1627E.mdx, solutions/silver/cf-321B.mdx, src/gatsby/create-xdm-node.ts
Throws an error if more CPPSections (or any other language) are present than LanguageSections.
=> throw error on extra lang sections

src/components/Settings/General.tsx
=> Adds long polling label for Issue #3573

content/6_Advanced/DP_More.mdx, content/6_Advanced/DP_More.problems.json
=> Reformatted "DP More" Module

content/4_Gold/Modular.problems.json, content/4_Gold/Sliding_Window.problems.json, solutions/gold/ys-QueueComposite.mdx
digging through my old code :p
---
=> brief editorial + c++ solution to queue composite

content/1_General/Expected_Knowledge.mdx
=> Update Expected_Knowledge.mdx : Updated link to Codesignal - Arcade

content/4_Gold/Combinatorics.mdx
=> add java and python solutions to combo

content/4_Gold/LIS.problems.json, solutions/gold/baltic-09-candy.mdx
=> add solution with lis for baltic-09-candy

solutions/gold/usaco-743.mdx
=> add cpp implementation to usaco-743

content/2_Bronze/Intro_Sorting.problems.json, solutions/bronze/cf-1808B.mdx
=>  Add Problem "Playing in a Casino" to Bronze - Intro for Sorting

solutions/bronze/usaco-915.mdx
=> added Sleepy Cow Herding hints

solutions/bronze/usaco-1013.mdx
=> Add Python Implementation to "Swap" Problem

content/4_Gold/MST.problems.json, solutions/gold/cf-1513D.mdx
~~expl probably comes before next Sat.~~ Done
=> Add internal solution for GCD and MST (cf-1513d) 

solutions/bronze/usaco-832.mdx, solutions/bronze/usaco-894.mdx
=> hints for grass planting & milking order

solutions/silver/cf-1223C.mdx
=> Fix incorrect official editorial hyperlink

solutions/silver/usaco-990.mdx
=> faster solution for usaco-990

content/4_Gold/Knapsack_DP.problems.json, solutions/gold/usaco-897.mdx
=> added solution to usaco-897

solutions/bronze/usaco-989.mdx
=> hints for race (bronze)

solutions/gold/cses-1716.mdx
=> added hint to cses-1716

content/6_Advanced/Offline_Del.problems.json
=> Fixed Minor Typo

content/5_Plat/2DRQ.problems.json, content/6_Advanced/Treaps.mdx, content/6_Advanced/Treaps.problems.json
=> Added Treap Problems

content/6_Advanced/DP_SOS.mdx, content/6_Advanced/DP_SOS.problems.json, content/extraProblems.json
=> added usaco problem

content/4_Gold/Digit_DP.mdx
Java Impl is coming some time next week
=> Refactor cpp code in gold/digit-dp, add java implementation

solutions/gold/usaco-696.mdx
=> add cpp euler tour implementation to usaco 696

content/6_Advanced/Treaps.problems.json
The original link went to a different problem.
=> Fix problem link

solutions/bronze/usaco-1013.mdx, solutions/bronze/usaco-1084.mdx, solutions/bronze/usaco-1088.mdx, solutions/bronze/usaco-1227.mdx, solutions/bronze/usaco-831.mdx, solutions/bronze/usaco-857.mdx, solutions/bronze/usaco-941.mdx, solutions/bronze/usaco-989.mdx
=> final two hints

content/4_Gold/Digit_DP.mdx
=> Fix varaible naming in gold/digit

solutions/bronze/usaco-785.mdx, solutions/general/usaco-987.mdx
=> java sol for 785

content/6_Advanced/String_Search.mdx, solutions/advanced/apio-14-palindrome.mdx
The URL seems to not be working anymore, so I updated the link to an archived version.
=> Fix URL for palindrome tree resource

content/4_Gold/Tree_Euler.mdx
=> Add python code for Subtree Queries in Euler Tour module

content/4_Gold/PURS.mdx
=> segtree maintenance

content/5_Plat/Sweep_Line.mdx
=> Add C++ code for Closest Pair problem in Sweep Line module

solutions/silver/cf-1000C.mdx
=> Refactor code, add java implementation, add map solution for Covered Points Count (cf/1000c)

.vscode/settings.json, src/pages/index.tsx
=> Added Vercel-like home redirect to dashboard

content/4_Gold/Divisibility.mdx
=> divisibility maintenance

src/pages/index.tsx
=> Fixed useEffect not running for the dashboard redirect

content/2_Bronze/Complete_Rec.mdx
gonna do the queens code sometime later, that problem itself is god-awful
=> complete recursion maintenance

content/2_Bronze/Intro_Sets.mdx
=> add python support for sets & maps

content/2_Bronze/Complete_Rec.mdx
=> queens sol sans

solutions/platinum/cses-2138.mdx
=> oopsies poopsies

content/3_Silver/Func_Graphs.mdx
=> Python Support for Functional Graphs (Silver)

solutions/silver/cf-782b.mdx
=> add java solution to cf782b

solutions/gold/usaco-670.mdx
=> Fix typos in usaco-670.mdx

content/2_Bronze/Ad_Hoc.problems.json, content/2_Bronze/Complete_Rec.problems.json, content/2_Bronze/Intro_Complete.problems.json, content/2_Bronze/Intro_Greedy.problems.json, content/3_Silver/Binary_Search.problems.json, content/3_Silver/Conclusion.problems.json, content/3_Silver/Greedy_Sorting.problems.json, content/3_Silver/Intro_Sorted_Sets.problems.json, content/3_Silver/More_Prefix_Sums.problems.json, content/4_Gold/Combinatorics.problems.json, content/4_Gold/Conclusion.problems.json, content/4_Gold/DSU.problems.json, content/4_Gold/Divisibility.problems.json, content/4_Gold/PURS.problems.json, content/4_Gold/Paths_Grids.problems.json, content/4_Gold/Shortest_Paths.problems.json, content/4_Gold/String_Hashing.problems.json, content/4_Gold/TopoSort.problems.json, content/4_Gold/Tree_Euler.problems.json, content/4_Gold/Unweighted_Shortest_Paths.problems.json, content/5_Plat/Bitsets.problems.json, content/5_Plat/Segtree_Ext.problems.json, content/6_Advanced/String_Search.problems.json, content/extraProblems.json
=> problems revamp: add and moved a bunch of problems, including this years usaco problems and more

content/3_Silver/Intro_Tree.mdx, content/3_Silver/Two_Pointers.mdx, content/3_Silver/Two_Pointers.problems.json
=> some issues

content/5_Plat/Merging.problems.json, solutions/platinum/cf-600E.mdx
=> erm please work

content/4_Gold/Unweighted_Shortest_Paths.problems.json, solutions/gold/ac-constructapalindrome.mdx
=> construct a palindrome solution

content/3_Silver/Intro_Bitwise.problems.json, solutions/silver/ac-theedaysago.mdx, solutions/silver/ac-threedaysago.mdx
=> Add internal solution for Three Days Ago (abc295_d)

content/6_Advanced/DP_SOS.mdx
=> fixed https://github.com/cpinitiative/usaco-guide/issues/3733

content/2_Bronze/Ad_Hoc.problems.json, content/problems.schema.json, gatsby-node.ts, src/components/markdown/ProblemsList/DivisionList/DivisionList.tsx, src/components/markdown/ProblemsList/ProblemListItemSolution.tsx, src/models/problem.ts, src/templates/moduleTemplate.tsx, src/utils/algolia-queries.ts, static/problems.schema.json
Added the feature to show if a problem has hints which was requested in this issue - https://github.com/cpinitiative/usaco-guide/issues/3650
=> Functionality to show whether a problem has hints

gatsby-config.ts, package.json, src/pages/index.tsx, yarn.lock
Apparently the older google analytics is ending on July 1, 2023. But maybe we should just use Vercel analytics instead...? Does anyone have thoughts?
=> Update to Google Analytics 4

solutions/silver/usaco-416.mdx
=> Added internal written solution for USACO-416 / The Lazy Cow

content/4_Gold/Shortest_Paths.mdx
i'm so bored it's not even funny
=> shortest path maintenance

solutions/bronze/usaco-965.mdx
=> Python Implementation for Livestock Lineup

content/3_Silver/Graph_Traversal.mdx
=> dummy input for graph traversal

content/3_Silver/Binary_Search.problems.json, content/3_Silver/More_Prefix_Sums.problems.json, solutions/silver/cc-TRPTSTIC.mdx
=> Add implementation for CC-TripTastic

content/3_Silver/Intro_Bitwise.problems.json, solutions/gold/ac-constructapalindrome.mdx, solutions/silver/cf-1338A.mdx
the editorial is kinda crap ngl, would appreciate any feedback on that
=> powered addition solution

content/1_General/Generic_Code.mdx, content/2_Bronze/Intro_DS.mdx
Some of the LCPP version numbers were outdated 🙂
=> Correct LCPP chapter numbers

solutions/silver/cses-2185.mdx
=> added python sol to cses 2185

solutions/bronze/usaco-784.mdx
=> Lifeguards Hint

solutions/gold/usaco-1041.mdx
=> added hint & cpp solution to usaco-1041

content/3_Silver/Intro_Bitwise.problems.json, solutions/silver/usaco-1327.mdx
=> Add Editorial for Field Day

content/3_Silver/Intro_Bitwise.problems.json, solutions/silver/usaco-1182.mdx
=> Add internal solution for Searching for Soulmates (usaco-1182)

content/5_Plat/Binary_Jump.problems.json
added a problem in the binary lift section from the recent codeforces Div 3 round. 
Please review my pull request.
I could add an internal solution with explanation, if there is a need for it, do tell me.
=> Added problem in the binary lifting section, platinum

src/pages/index.tsx
=> Fix logo issue

content/3_Silver/Binary_Search.problems.json, solutions/bronze/usaco-592.mdx, solutions/gold/usaco-597.mdx
=> angry cows - update bronze and gold sols

content/3_Silver/Intro_Bitwise.problems.json, solutions/silver/cf-1732C1.mdx
=> Sheikh Editorial

content/3_Silver/Intro_Bitwise.problems.json, solutions/silver/cf-1088D.mdx
=> hard bitwise problem

content/5_Plat/Centroid.mdx
=> Made centroid decomposition c++ implementation easier to read

solutions/silver/cf-1017D.mdx
=> make wu faster

solutions/silver/cf-1158A.mdx
=> Address Contact Form Submission

content/5_Plat/Matrix_Expo.mdx
https://github.com/cpinitiative/usaco-guide/pull/2875
=> Added author name for an old contribution #2875

content/2_Bronze/Intro_Sets.problems.json
=> Fixed tag for Made Up problem from Set to Map

content/2_Bronze/Intro_Sets.problems.json
=> Replaced Set with Map in Tags property

content/5_Plat/Centroid.mdx
=> Refactor cpp code for Xenia & Tree (plat/centroid)

README.md
I am applying for coding club positions and it will help my application significantly if I am bestowed the honor of having my name listed on the usaco.guide GitHub readme. **I joined the team (you can see this on the discord) last month**, but here are some merged pull requests I've authored for good measure (4 major, 1 minor).
https://github.com/cpinitiative/usaco-guide/pull/3745
https://github.com/cpinitiative/usaco-guide/pull/3750
https://github.com/cpinitiative/usaco-guide/pull/3762
https://github.com/cpinitiative/usaco-guide/pull/3773
https://github.com/cpinitiative/usaco-guide/pull/3806
- If …
=> Update CA list

src/components/TopNavigationBar/TopNavigationBar.tsx
=> changed banner text to looking for instructors

src/components/TopNavigationBar/TopNavigationBar.tsx
=> capitalized words of banner

src/components/ProblemsPage/ProblemHits.tsx
=> Added ProblemStatusCheckbox to problems page

content/4_Gold/Combinatorics.problems.json, content/5_Plat/Bitsets.problems.json, solutions/gold/usaco-862.mdx
=> Cowpatibility Editorial

content/6_Advanced/SPneg.mdx
=> Added solution to SSSP Negative problem

content/4_Gold/TopoSort.mdx
=> Add Python Solution to CSES Longest Flight Route

solutions/gold/ys-MaxIndepSet.mdx
closes #3863
i am a man of my word
=> max indep set redo

content/4_Gold/MST.problems.json, solutions/gold/ks-checksum.mdx
=> Fix link for Checksum

gatsby-node.ts
Certain USACO monthly problems not associated with any module did not create a user solutions page
Fix for part of #3870, does not fix monthlies not appearing under problem search
=> Fixed missing user solutions pages

src/pages/index.tsx
=> Removed XCamp as a platinum sponsor

src/components/TopNavigationBar/TopNavigationBar.tsx
=> changed banner to advertise for students for USACO Bronze and Silver Classes

src/components/TopNavigationBar/TopNavigationBar.tsx
=> change the button to "Join here" instead of "Apply here"

solutions/gold/usaco-898.mdx
=> New C++ implementation for Sleepy Cow Sort

gatsby-node.ts
Some older USACO problems weren't included in div_to_probs, and were being skipped over in user solution page creation
Fixes #3901 
=> Fixed missing USACO user solutions pages

solutions/silver/cses-1085.mdx
=> Refactor cpp, add java implementation for Array Division (cses-1085)

content/3_Silver/More_Prefix_Sums.problems.json, solutions/silver/ac-nuske.mdx, solutions/silver/usaco-744.mdx
man it's been ages since i've made one myself
=> nuske java

content/4_Gold/Sliding_Window.mdx
=> Add Python Solution to CSES Playlist

content/4_Gold/Meet_In_The_Middle.mdx, solutions/bronze/usaco-689.mdx, solutions/bronze/usaco-940.mdx, solutions/silver/cses-1751.mdx, solutions/silver/usaco-1014.mdx, solutions/silver/usaco-416.mdx, solutions/silver/usaco-573.mdx
=> lazy cow fix

solutions/gold/cses-1142.mdx
=> Refactor solution for Advertisement (cses/1142)

src/context/UserDataContext/UserDataContext.tsx
=> fix show tag default

content/3_Silver/Binary_Search.problems.json, content/3_Silver/Intro_Sorted_Sets.problems.json
The problem requires binary search and is rated very difficult. I've done it myself, the part where you have to prevent it from 
integer overflow makes it easily a "Very Hard" / "Insane".
=> Fix problem category & difficulty (CF-1805F1)

content/extraProblems.json, solutions/bronze/usaco-1277.mdx
- [ ✓] I have tested my code.
- [ ✓] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ✓] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
- [ ✓] I have linked this PR to any issues that it closes.
=> added solution for usaco 1277

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Hid Class Registration Banner

content/6_Advanced/BCC_2CC.mdx
=> Forbidden Cities Editorial 

solutions/silver/cf-803D.mdx
=> added python sol for cf803D

solutions/silver/cf-1744F.mdx
=> added py sol for mex vs med cf1774f

solutions/silver/usaco-668.mdx
=> Hint for Moocast

solutions/gold/usaco-1085.mdx
=> Add faster solution for Just Stalling (usaco/1085)

solutions/gold/cses-1082.mdx
=> Fixed #3966

content/2_Bronze/Conclusion.problems.json, content/2_Bronze/Intro_Sets.problems.json, content/2_Bronze/Intro_Sorting.problems.json, content/3_Silver/Binary_Search.problems.json, content/3_Silver/Conclusion.problems.json, content/3_Silver/Greedy_Sorting.problems.json, content/3_Silver/Intro_Bitwise.problems.json, content/3_Silver/Intro_Sorted_Sets.problems.json, content/3_Silver/Intro_Tree.problems.json, content/3_Silver/More_Prefix_Sums.problems.json, content/3_Silver/Prefix_Sums.problems.json, content/4_Gold/Combinatorics.problems.json, content/4_Gold/DP_Trees.problems.json, content/4_Gold/DSU.problems.json, content/4_Gold/Intro_DP.problems.json, content/4_Gold/Knapsack_DP.problems.json, content/4_Gold/Stacks.problems.json, content/4_Gold/TopoSort.problems.json, content/4_Gold/Tree_Euler.problems.json
=> Problems Galore 1

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Added promo bar for interclub comp

content/5_Plat/Sweep_Line.mdx
=> fix minor mistakes

content/5_Plat/Sweep_Line.mdx
fixed time complexity spacing 
closes #3973 
=> time complexity fix

content/4_Gold/Paths_Grids.problems.json, solutions/gold/ac-swap.mdx
=> add editorial for swap (ac)

content/3_Silver/More_Prefix_Sums.mdx
=> more pref sum quiz

content/6_Advanced/Eulerian_Tours.mdx, content/6_Advanced/Max_Flow.mdx
=> Eulerian Tours editorial

solutions/gold/cses-1716.mdx
=> Add Java and Python Solution for Distributing Apples (cses/1716)

content/5_Plat/Centroid.mdx
=> Add an additional resource for Centroid Decomposition

content/6_Advanced/Max_Flow.mdx
=> Push Relabel Maximum Flow

content/3_Silver/Intro_Bitwise.problems.json, solutions/silver/cf-1851F.mdx
=> added solution to cf-1851F

content/3_Silver/Func_Graphs.mdx
=> one must imagine ks happy

content/5_Plat/Sparse_Segtree.mdx
=> added cp-algo dynamic segment tree to Sparse_Segtree.mdx

solutions/gold/usaco-265.mdx
=> Add Java Solution for The Cow Run (usaco-265)

content/5_Plat/Sqrt.mdx, content/5_Plat/Sqrt.problems.json
=> Mo's algorithm Problem

solutions/silver/cf-1851F.mdx
=> fix a typo in cf-1851F solution explanation

content/6_Advanced/BCC_2CC.mdx, content/6_Advanced/BCC_2CC.problems.json
=> Articulation points editorial

content/4_Gold/Divisibility.problems.json, solutions/gold/cc-KSIZEGCD.mdx
=> Maximum GCD Editorial

content/1_General/Practicing.mdx
- Previously the link was https://web.evanchen.cc/FAQs/raqs.html broken, updated to the new link.
=> [How to Practice] Fix Evanchen Broken Link

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Update TopNavigationBar.tsx with IOI workshop banner

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Added IOI 23 workshop banner

content/4_Gold/Conclusion.problems.json, solutions/gold/usaco-230.mdx
=> Island Travels

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Removed IOI Banner workshop banner

content/5_Plat/Binary_Jump.mdx
=> minor fix for binary jumping

solutions/bronze/cses-1640.mdx
=> Incorrect time complexity on solution for CSES Two Sum

content/1_General/Contests.mdx
=> remove google kickstart and hackerrank

content/4_Gold/Intro_DP.mdx
=> fix bug in a loop which causes infinity to be returned

solutions/advanced/cses-1695.mdx
Fixes #4050 
Modified usaco-guide/solutions/advanced/cses-1695.mdx
=> Fixed time-complexity in cses-1695.mdx

content/extraProblems.json, solutions/gold/usaco-1235.mdx
=> sol for balancing a tree!

solutions/gold/dmoj-Phidias.mdx
=> Fixed minor typo in IOI - Phidias

solutions/bronze/usaco-1251.mdx
=> added python solution for usaco-1251.mdx and reformatted code structure

solutions/bronze/usaco-917.mdx
=> fix traffic sol

content/2_Bronze/Ad_Hoc.mdx, content/3_Silver/Intro_Bitwise.mdx, content/4_Gold/DSU.mdx, content/4_Gold/MST.problems.json, content/4_Gold/PURS.mdx, solutions/gold/coci-17-sirni.mdx, solutions/silver/cf-782b.mdx, solutions/silver/cf-803D.mdx, solutions/silver/cses-1085.mdx, solutions/silver/usaco-594.mdx, solutions/silver/usaco-668.mdx, solutions/silver/usaco-716.mdx, solutions/silver/usaco-991.mdx
=> sirni sol and other things

content/6_Advanced/String_Search.mdx, content/6_Advanced/String_Search.problems.json
=> Add Trie Code 

content/3_Silver/Conclusion.problems.json, solutions/silver/ccc-Firehose.mdx
=> fix firehose

content/1_General/Running_Code_Locally.mdx
=> Remove Atom

content/4_Gold/PURS.mdx
=> bugs me tbh

content/4_Gold/PURS.mdx, content/4_Gold/Stacks.problems.json, solutions/gold/cses-2416.mdx
=> increasing array queries

content/3_Silver/Two_Pointers.mdx
=> two pointers wording

content/1_General/Olympiads.mdx
=> Old IOI syllabus link doesn't work, put a new one in

content/6_Advanced/String_Search.mdx
=> Minor Mistake (Advanced - String Searching)

.github/workflows/update-usaco.yml, src/utils/algolia-queries.ts
=> Update workflow + push to correct index

gatsby-node.ts
=> make sure ids.log doesn't grow to large

src/components/markdown/ProblemsList/DivisionList/DivisionList.tsx
=> Update DivisionList for 2023-24

src/components/ContactUsSlideover/ContactUsSlideover.tsx
=> automatically set solution title in contact form

content/3_Silver/Func_Graphs.mdx
https://forum.usaco.guide/t/solved-about-intro-to-func-graphs/5318
=> func graphs - clarify rooted tree

src/components/ContactUsSlideover/ContactUsSlideover.tsx, src/functions/src/submitContactForm.ts
should use this topic even mistake is not so minor
=> contact form: minor mistake -> mistake

src/components/TopNavigationBar/TopNavigationBar.tsx
Wait to merge this until dec23 workshop pr has been merged for joincpi.org
=> Added header for Dec23 workshop

content/6_Advanced/String_Search.mdx
=> fix: string_search

solutions/gold/usaco-1019.mdx
=> skibidi toilet

content/3_Silver/Binary_Search.mdx, content/3_Silver/Graph_Traversal.problems.json, content/4_Gold/MST.problems.json, content/5_Plat/Centroid.problems.json, content/6_Advanced/String_Search.problems.json
=> ton of issues

content/5_Plat/Sqrt.mdx, content/5_Plat/Sqrt.problems.json
=> SQRT Combining Algorithms

solutions/silver/usaco-669.mdx, solutions/silver/usaco-788.mdx
=> add python solution to usaco-788

content/4_Gold/Modular.mdx
=> Modular Inverse using Euclidean Division

src/pages/problems.tsx
=> get rid of extraneous gaps in problems page

content/3_Silver/Intro_Bitwise.problems.json
=> Add HasHints: true for CF-1386D

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Hide workshop banner

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Add live classes banner

solutions/platinum/usaco-1020.mdx
=> obscure delegation edge case that wasn't caught by any of the test cases very funny bro

src/functions/src/cpiclasses/approveLiveFinancialAid.ts, src/functions/src/cpiclasses/processLiveRegistration.ts
=> Fix firebase functions

content/6_Advanced/Suffix_Array.mdx, content/6_Advanced/Suffix_Array.problems.json, solutions/gold/cfgym-101102D.mdx
no one reads this anyways
might add other languages if i'm feeling up to it
=> felt cute, have a suffix array

solutions/gold/cses-1642.mdx
=> Add java solution for CSES Four Sum

solutions/silver/cses-1661.mdx
The article specified O(n log n), despite this being a linear time (and space) algorithm.
=> Correct time complexity for CSES Subarray Sum

src/components/TopNavigationBar/TopNavigationBar.tsx
=> class, contest, and workshop announcements

src/components/Dashboard/ActiveItems.tsx, src/components/Dashboard/Activity.tsx, src/components/Dashboard/Announcements.tsx, src/components/Dashboard/DailyStreak.tsx, src/components/Dashboard/DashboardCard.tsx, src/components/Dashboard/WelcomeBackBanner.tsx, src/components/TopNavigationBar/TopNavigationBar.tsx, src/pages/dashboard.tsx, src/pages/index.tsx
Task 1: Swap the order of the announcements and Active problems/modules sections on /dashboard
Task 2: Redirect the home page to dashboard if the user is signed in. Reference this …
=> fix Announcements

announcements/2021 Feb.mdx, announcements/Groups Open To Public.mdx, announcements/Open Source.mdx
This will be used later for the joincpi.org website to directly pull announcements from this repo
=> Removed relative addresses in announcements

content/3_Silver/Conclusion.problems.json
A binary lifting problem that's too easy to put in binary jumping but too difficult to put in functional graphs. Solving the problem without binary lifting is not intended and incredibly annoying.
=> rm LC 2386 Maximize Value of Function in a Ball Passing Game

announcements/2024 Spring Tournament.mdx
=> Update 2024 Spring Tournament.mdx

content/4_Gold/DP_Trees.problems.json
=> Fix typo in DP on trees JSON

content/4_Gold/Tree_Euler.problems.json
=> fix typo in euler tour trees json

content/6_Advanced/Vectorization.mdx, src/components/Dashboard/ModuleLink.tsx
Closes #4283, reverts change from #4157
=> Fix Module Frequency 0 Bug

content/ordering.ts
It doesn’t really make sense to sandwich this module, being as useless and rare as it is, between the 2 most important bronze topics.
It’s also, imo, one of the harder modules. And it’s the first thing we’re throwing at new programmers who just figured out how to program exactly what the statement asks them to program (simulation). And now we’re making them keep track of 4 or 8 or 12 terribly named variables and do confusing calculations on them?
=> move rect geo to additional

.github/workflows/update-usaco.yml
=> update update workflow

content/3_Silver/Sorting_Custom.problems.json
oops mistyped commit message 😭 
=> change lifeguards from 'easy' to 'normal'

src/components/markdown/ProblemsList/DivisionList/DivisionList.tsx
=> fix dark mode on monthlies

content/5_Plat/Geo_Pri.mdx, content/5_Plat/Geo_Pri.problems.json
=> Geometry Primitives - Polygon Lattice Points

src/atoms/editor.ts
before, when creating a new internal sol:
*as you can see, solutionMetadata is poorly formatted*
after:
=> fix problems.json formatting issues

src/components/Editor/BaseEditor.tsx, src/components/ProblemsPage/Selection.tsx, src/context/DarkModeContext.tsx, src/context/DarkModeProvider.tsx
=> fix flicker on "Select" elements

src/components/ProblemsPage/SearchBox.tsx
=> change text color from white to blue-900 while also fixing contrast

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Added feb 24 workshop

content/4_Gold/MST.mdx
=> Added Kruskal algorithm visualizer to MST resources

src/atoms/editor.ts, src/components/Editor/EditorTabBar.tsx
=> support pulling code into editor

content/5_Plat/Centroid.mdx
=> Minor updates to centroid decomp section

content/3_Silver/More_Prefix_Sums.mdx, content/5_Plat/Binary_Jump.problems.json
=> fix some issues

.github/workflows/update-usaco.yml
=> workflow issues?

solutions/platinum/ys-StaticRangeInversionsQuery.mdx
=> Add cleaner solution

content/team/contributors.ts
=> update team members

src/components/Dashboard/ModuleLink.tsx
=> fix warnings

content/3_Silver/Greedy_Sorting.problems.json
=> Add LC 502 IPO to Silver Greedy

content/3_Silver/Greedy_Sorting.problems.json
=> Fix IPO Difficulty

solutions/gold/cc-KSIZEGCD.mdx
=> Maximum GCD Clarification 

src/components/TopNavigationBar/TopNavigationBar.tsx
=> added US Open workshop banner

content/6_Advanced/Fracturing_Search.mdx
- [X ] I have tested my code.
- [X ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
- [X ] I have linked this PR to any issues that it closes.
=> Fix small typo in fracturing search

solutions/silver/usaco-380.mdx
=> feature: Added C++ solution for USACO-380

content/4_Gold/DP_Bitmasks.mdx
Fixed grammatical error in Bitmask DP section. 
=> Fix grammatical error

content/4_Gold/Hashmaps.mdx
fix typo from cusetom to custom.
=> fix typo (cusetom -> custom)

content/1_General/Expected_Knowledge.problems.json, solutions/general/cf-4A.mdx
=> Add cf-4A.mdx

content/extraProblems.json
- [X ] I have tested my code.
- [X ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
- [ X] I have linked this PR to any issues that it closes.
=> Add a difficulty to Maximizing Productivity

content/4_Gold/TopoSort.mdx
=> toposort revamp

src/components/TopNavigationBar/PrettyBanner.tsx, src/components/TopNavigationBar/TopNavigationBar.tsx
Looking for new web developers!
=> Updated Banner

content/6_Advanced/String_Search.mdx, content/6_Advanced/String_Search.problems.json
=> Z-Algorithm Editorial

content/4_Gold/MST.mdx
=> sansified mst

content/3_Silver/Conclusion.problems.json, content/4_Gold/DP_Trees.problems.json, solutions/gold/kattis-catandmice.mdx, solutions/gold/kattis-gcdharmony.mdx
=> gcd harmony

content/6_Advanced/LCT.mdx, content/6_Advanced/LCT.problems.json
=> Explain focus problems and description of algorithms for LCT module

solutions/silver/cses-1091.mdx
=> Added Python Solution for Concert Tickets

content/4_Gold/Modular.mdx
Implementation 
Changes old broken link (https://aryansh-s.github.io/The_Art_of_Modular_Arithmetic.pdf) to a new link (https://web.archive.org/web/20230324003836/https://aryansh-s.github.io/The_Art_of_Modular_Arithmetic.pdf) for the same resource.
Resolve #4468
=> changed broken link with new link

gatsby-node.ts, src/components/Groups/PostPage/PostPage.tsx, src/components/ProblemSolutions.tsx, src/models/problem.ts, src/templates/solutionTemplate.tsx, src/templates/userSolutionTemplate.tsx
=> add modules for user solutions page 

solutions/silver/cses-1161.mdx
=> added python solution for stick divisions

src/components/MarkdownLayout/DesktopSidebar.tsx, src/components/TopNavigationBar/Banner.tsx, src/components/TopNavigationBar/TopNavigationBar.tsx
I also refactored the `PrettyBanner` component to be more configurable.
=> Update banner to class promo

content/5_Plat/Binary_Jump.mdx
=> Binary Jump Module - Removed Benq Template

src/pages/dashboard.tsx
=> hid January 2024 banner

content/6_Advanced/Eulerian_Tours.problems.json
=> [Problem Suggestion] Added 949D

content/4_Gold/Modular.mdx
finally fixed, sorry for delay! no longer need to use archived version
=> fix link to my resource in Modular.mdx

content/3_Silver/Func_Graphs.mdx
=> Update Introduction to Function Graphs

content/1_General/Contributing.mdx
=> Discord Invite Fix

content/3_Silver/Conclusion.problems.json
=> Fix ordering of silver conclusion problems

solutions/orphaned/cses-2220.mdx
=> Fix typo in Counting Numbers CSES

content/6_Advanced/Multiplicative.problems.json
=> multiplicative: fix solution metadata kind

content/2_Bronze/Intro_DS.mdx, content/2_Bronze/Intro_Sets.mdx, content/5_Plat/Binary_Jump.mdx
=> spruce up intro ds mod

src/components/Editor/EditorTopNav.tsx, src/components/Index/TrustedBy.tsx, src/components/ProblemSuggestionModal.tsx, src/components/Settings/Authentication.tsx, src/components/SignInModal.tsx, src/components/markdown/IncompleteSection.tsx, src/components/markdown/LanguageSection.tsx, src/context/GlobalErrorBoundary.tsx, src/context/UserDataContext/UserDataContext.tsx, src/pages/index.tsx
It's pure torture for me to see "GitHub" capitalized as "Github", so I changed that.
=> GitHub proper capitalization

content/6_Advanced/MinCostFlow.problems.json
=> fix sol metadata for kattis-cordonbleu

content/3_Silver/Prefix_Sums.mdx
=> Add built-in approach for Prefix sums

solutions/bronze/cf-1914C.mdx
Added solution codes for [cf-1914C](https://usaco.guide/problems/cf-quests/solution) in Java and python as it was missing. 
Linking my accepted solutions of the question from codeforces below: 
Java accepted solution: https://codeforces.com/problemset/submission/1914/267802583
Python accepted solution: https://codeforces.com/problemset/submission/1914/267802332
~~- [ ] I have linked this PR to any issues that it closes.~~
This is my first time contributing to this project. Let me know if I have to change anything.
=> cf-1914C - Solution codes added in Java and Python

solutions/orphaned/cf-1566B.mdx
=> Java Solution Added to cf-1566B

solutions/bronze/cf-581D.mdx
=> added java and python solution

content/5_Plat/Geo_Pri.problems.json, solutions/platinum/ioi-02-frog.mdx
=> [Editorial] The Troublesome frog

solutions/silver/usaco-1206.mdx
=> hotfix and optimization

content/4_Gold/Combinatorics.mdx
=> Fix formula

solutions/silver/cf-632C.mdx
=> Java Solution added to cf-632

solutions/bronze/cf-1808B.mdx
Problem link : [Link](https://codeforces.com/contest/1808/problem/B)
Accepted Solution:  [Link](https://codeforces.com/contest/1808/submission/269687800)
=> Added Java solution for CF 1808B

solutions/bronze/usaco-1301.mdx
Problem link: [Link](https://usaco.org/index.php?page=viewproblem2&cpid=1301)
Solution Code : [Link](https://ide.usaco.guide/O1R-wAK9g11rZtagFTk)
=> added java solution code for usaco-1301

solutions/silver/cf-839C.mdx
=> Java Solution added to cf-839C

solutions/gold/cf-100886G.mdx
=> Fix max prod solution

content/3_Silver/Func_Graphs.problems.json, content/6_Advanced/SCC.problems.json
=> fix problem labels

gatsby-node.ts
=> Throw error when missing internal sol

content/6_Advanced/LCT.mdx
=> Fix minor typo

content/4_Gold/Meet_In_The_Middle.problems.json, solutions/gold/cf-585D.mdx
=> Editorial for Lizard Era Beginning

content/2_Bronze/Intro_Greedy.problems.json
=> general problem difficulty ordering updated

content/2_Bronze/Intro_Complete.problems.json, content/extraProblems.json
=> Add Tags for Recent USACO Problems

content/6_Advanced/Treaps.mdx, content/6_Advanced/Treaps.problems.json
=> Add more treap code (lazy prop and merging)

content/6_Advanced/Treaps.mdx
=> really small typo i missed

content/2_Bronze/Conclusion.problems.json, solutions/bronze/cf-1555B.mdx, solutions/bronze/cf-1808B.mdx, solutions/bronze/cf-1846D.mdx, solutions/bronze/cf-1914C.mdx
- [] I have linked this PR to any issues that it closes.
=> Internal Solution | cf-1846D and some other nitpicks

content/1_General/Cpp_Command.mdx
- Removed the "This section is not complete." box
- Added another resource under Linux
- Removed General
=> C++ With the Command Line edits

src/components/Editor/MainEditorInterface.tsx
=> add insert code option

solutions/gold/csa-MountainTime.mdx
=> Minor Mountain Time Refactoring (C++) 

content/2_Bronze/Ad_Hoc.problems.json, content/3_Silver/Two_Pointers.problems.json, content/4_Gold/Divisibility.problems.json, content/4_Gold/LIS.problems.json, content/4_Gold/Sliding_Window.problems.json, solutions/silver/cses-1630.mdx, solutions/silver/cses-1660.mdx
=> added tags for some problems

content/3_Silver/Intro_Bitwise.mdx
=> Added Java Solution to content/3_Silver/Intro_Bitwise.mdx

content/6_Advanced/Treaps.mdx
Issue linked: https://github.com/cpinitiative/usaco-guide/issues/4679
=> upd key -> val

content/1_General/Resources_CP.mdx
The IOI community link was broken at `./content/1_General/Resources_CP.mdx`
=> ioi community broken link removed

content/5_Plat/Geo_Pri.problems.json
=> Add 'Manhattan Multifocal Ellipse' Problem to Geo Prim Module

content/6_Advanced/Catalan.problems.json, solutions/advanced/cses-2187.mdx
=> [Editorial] Bracket Sequences II

content/3_Silver/More_Prefix_Sums.mdx
=> python sol for greg and array

content/6_Advanced/Game_Theory.problems.json
=> Fixed Problem

content/4_Gold/Combinatorics.mdx, content/4_Gold/Combinatorics.problems.json
Added some basic expected value content. Also modified some of the difficulty labels that were either incorrectly written or too high for the problem difficulty.
=> Add Expected Value

content/4_Gold/LIS.mdx
=> do some lis maintenance- mainly pass const refs

content/4_Gold/Tree_Euler.problems.json, solutions/gold/ac-distancequeries.mdx
=> Distance Queries in Tree Editorial

content/3_Silver/Intro_Bitwise.mdx
=> py solution for Xor Sigma Problem

content/4_Gold/Combinatorics.mdx
=> redo c++ and add python sol for marbles

content/4_Gold/Meet_In_The_Middle.problems.json, solutions/gold/cf-912E.mdx
=> add explanation for prime gift

src/components/TopNavigationBar/TopNavigationBar.tsx
Just commented out the banner.
=> remove summer class banner

solutions/silver/cf-1088D.mdx
=> py sol for cf-1088D

solutions/silver/cf-1879D.mdx
=> java / py sols for cf-1879D

solutions/silver/cf-1732C1.mdx
=> java sols for cf-1732C1

solutions/silver/cf-1851F.mdx
=> py sol for cf-1851F

solutions/silver/cf-1338A.mdx
=> java sol for powered addition

content/4_Gold/Conclusion.problems.json, solutions/gold/kattis-studentsko.mdx
=> studentsko sol and change difficulty

content/6_Advanced/String_Search.mdx, content/6_Advanced/String_Search.problems.json, solutions/advanced/cses-1732.mdx
=> [Editorial] Finding Borders

content/5_Plat/RURQ.problems.json, content/5_Plat/Sparse_Segtree.problems.json, solutions/platinum/ioi-05-mountain.mdx
i might try writing a sparse segtree solution if i learn it later, but i think this one is also ok
=> IOI Mountains Editorial

content/6_Advanced/String_Search.mdx, content/6_Advanced/String_Search.problems.json, solutions/advanced/cses-1110.mdx
=> [Editorial] Minimal Rotation

content/4_Gold/Divisibility.mdx
=> corrected range

solutions/gold/cf-1349A.mdx
=> py sol for Orac & LCM

content/6_Advanced/Game_Theory.mdx
=> better game theory expl

solutions/gold/ac-DivGame.mdx
=> java sol for DivGame

content/6_Advanced/String_Search.problems.json, solutions/advanced/cses-1655.mdx
=> [Editorial] Maximum Xor Subarray

src/components/TopNavigationBar/TopNavigationBar.tsx
https://discord.com/channels/754884077542441002/877330703853961268/1281451990668410990
=> fall banner

solutions/gold/cf-1514C.mdx, solutions/silver/cf-1088D.mdx
=> py/java sol for cf-1514C

content/3_Silver/Prefix_Sums.mdx
=> move problem warning

content/4_Gold/Combinatorics.mdx, solutions/gold/cses-1715.mdx
=> py sol for creating strings II and some typo

solutions/gold/cf-1462E2.mdx
=> py sol for close tuples

solutions/silver/cf-51C.mdx
=> C++ sol fix and py sol for cf-51c

solutions/gold/cfgym-102951C.mdx
=> py sol for lis on permutation

solutions/silver/cses-1620.mdx
Code link : https://cses.fi/paste/545a52383674578e9fe4b2/
I have tested that this submits as AC.
And the change on cses 1620 just reduces the search space of binary search from 1e18 to the best maximum time possible.
My earlier pr is still open hence this might show changes from there as well.
=> [Refactored] - Changed  cses 1620

solutions/gold/ac-swap.mdx
=> py sol for swap

content/5_Plat/RURQ.problems.json, solutions/platinum/ioi-14-wall.mdx
=> IOI Wall Solution

solutions/gold/ac-matching.mdx
=> py sol for matching

content/4_Gold/PURS.mdx, content/4_Gold/PURS.problems.json, content/5_Plat/2DRQ.mdx, content/6_Advanced/Multiplicative.mdx, solutions/gold/cses-2416.mdx
=> change headers and add recursive segtree impl

solutions/silver/cses-1085.mdx
Modified search space for binary search as left can be maximum element in array and right can be the sum of all elements in array.
=> [Refactored] : Update cses-1085.mdx

solutions/gold/cses-1080.mdx
=> py sol for empty string

content/4_Gold/Sliding_Window.mdx
=> py sol for sliding window max

solutions/silver/ccc-Firehose.mdx
=> py / java sol for Firehose

content/4_Gold/Combinatorics.mdx
So this is a very minor addition to the expected value section talking about expected products. I wanted to add more but I think the ordered pairs and powers technique found [here](https://codeforces.com/blog/entry/62792) would be too advanced for gold. Tell me if it is reasonable to add to anywhere else on USACO guide.
This will probably be the last time I touch expected value here :D
=> Expected Products

solutions/silver/ac-nuske.mdx
=> py sol for ac-nuske

content/3_Silver/More_Prefix_Sums.mdx, content/3_Silver/More_Prefix_Sums.problems.json
=> name formatting

solutions/gold/cses-1147.mdx
AC: https://cses.fi/paste/51819037e9803dd8a38726/
=> py sol for Maximum Building I

solutions/gold/cses-1681.mdx
AC: https://cses.fi/paste/456131b96e64ba3aa3275f/
=> py sol for game routes

solutions/gold/cses-1148.mdx
AC: https://cses.fi/paste/4270e1d181d2f153a3b111/
=> py sol for Maximum Building II

content/4_Gold/Meet_In_The_Middle.mdx
=> remove redundant lines

content/6_Advanced/XOR_Basis.problems.json
{
"uniqueId": "cf-1101G",
"name": "(Zero XOR Subset)-less",
"url": "https://codeforces.com/contest/1101/problem/G",
"source": "CF",
"difficulty": "Normal",
"isStarred": false,
"tags": [],
"solutionMetadata": {
"kind": "autogen-label-from-site",
"site": "CF"
}
},
=> Update XOR_Basis.problems.json - Add problem

solutions/silver/cf-1359C.mdx
close #4772
i swear this works
=> no more floating pt precision in mixing water

content/4_Gold/DP_Ranges.problems.json
=> add external sol for beetle

solutions/silver/cf-1359C.mdx
AC (Python): https://codeforces.com/contest/1359/submission/284879733
AC (JAVA): https://codeforces.com/contest/1359/submission/284882689
=> py / java sol for Mixing Water

solutions/silver/ceoi-10-AHugeTower.mdx
AC: https://oj.uz/submission/1097926
=> py sol for Huge Tower

content/6_Advanced/String_Search.mdx
AC proof: https://judge.yosupo.jp/submission/239873
=> Python implementation of Z-algorithm

solutions/gold/usaco-265.mdx
=> Update usaco-265.mdx - minor typo

content/6_Advanced/Catalan.mdx, solutions/advanced/cses-2187.mdx
AC: https://cses.fi/paste/95b7d3353fdea5c6a57dad/
=> py sol for bracket seq II 

content/6_Advanced/Eulerian_Tours.mdx
AC: https://cses.fi/paste/e2b2b4213f8c26b4a5af37/
=> py sol for teleporters path

content/6_Advanced/SPneg.mdx
AC: https://open.kattis.com/submissions/14638845
=> py sol for SSSP negative

content/6_Advanced/Eulerian_Tours.mdx
AC: https://cses.fi/paste/c471d1fbdd022ffaa5ae76/
=> py sol for De Bruijn Sequences

content/6_Advanced/SPneg.mdx
AC: https://open.kattis.com/submissions/14638901
=> py sol for APSP

content/6_Advanced/Eulerian_Tours.mdx
AC: https://cses.fi/paste/71d790740a105f2ba6235e/
=> py sol for Mail Delivery

content/4_Gold/Digit_DP.problems.json
=> Digit DP - remove misplaced problem

content/4_Gold/Conclusion.problems.json, solutions/gold/cf-1114D.mdx
OH MY GOD YOU HAVE NO IDEA HOW LONG THE JAVA SOL TOOK ME TO MAKE
LIKE IT WAS A BUG BECAUSE TWO `Integer`s CANT BE COMPARED WITH `==`
I'M ACTUALLY GONNA LOSE IT
=> floodfill sol

content/6_Advanced/Multiplicative.mdx
I just got rid of macros functions.
AC: https://judge.yosupo.jp/submission/244500
=> Sum of Totient Function code rfc

content/2_Bronze/Intro_Sorting.mdx
Added Python code for library sorting on static arrays section. Links to #3444, but does not fully resolve the entire issue.
=> Add Python to Intro_Sorting.mdx

content/5_Plat/DC-SRQ.problems.json
=> update problem name

content/6_Advanced/Multiplicative.mdx
=> py sol for sum of divisors

content/5_Plat/Geo_Pri.mdx
=> py sol for Point Location Test

content/5_Plat/Geo_Pri.mdx
The previous C++ was resulting in `RE` bcz we were excluding the case when `angles` array is empty and we are accessing the element which is not even there in for loop.
AC (Py): https://leetcode.com/problems/maximum-number-of-visible-points/submissions/1435032380/
AC (C++): https://leetcode.com/problems/maximum-number-of-visible-points/submissions/1435035886/
=> correct C++ code / py sol for Maximum Number of Visible Points

content/5_Plat/RURQ.problems.json, content/5_Plat/Sparse_Segtree.problems.json, solutions/platinum/ioi-05-mountain.mdx
=> Fix DMOJ Link for IOI Mountains (RURQ) 

content/5_Plat/Geo_Pri.mdx, content/5_Plat/Geo_Pri.problems.json, solutions/platinum/kattis-segmentintersection.mdx
AC: https://open.kattis.com/submissions/14757118
=> Editorial for Line Segment Intersection

solutions/platinum/ioi-02-frog.mdx
=> update Time Complexity

content/2_Bronze/Ad_Hoc.mdx, content/3_Silver/Sorting_Custom.mdx
Added quizzes to the below modules
- Bronze: Ad Hoc
- Silver: Sorting Custom
=> Add Quiz to Ad_Hoc, Sorting_Custom

content/4_Gold/Stacks.mdx
=> add time complexity

solutions/silver/usaco-744.mdx
=> py sol for Modern Art

solutions/bronze/dmoj-spirale.mdx
AC: https://dmoj.ca/submission/6717894
=> py sol for DMOJ Spirale

solutions/bronze/usaco-1276.mdx
=> py sol for usaco-1276

solutions/gold/usaco-1085.mdx, solutions/gold/usaco-673.mdx
=> py sol for Stalling

content/5_Plat/PIE.mdx, solutions/gold/usaco-862.mdx
=> py sols for Cowpatibility

solutions/gold/usaco-993.mdx
=> py sol for Time is Mooney

solutions/gold/usaco-815.mdx
=> py sol for Taming the Herd

solutions/gold/usaco-945.mdx
=> py sol for snakes

solutions/gold/usaco-718.mdx
=> py sol for usaco-718

solutions/bronze/usaco-1277.mdx
=> Add python solution for usaco-1277

content/2_Bronze/Conclusion.problems.json, solutions/bronze/cf-1624D.mdx
C++: https://codeforces.com/contest/1624/submission/290554951
Python: https://codeforces.com/contest/1624/submission/290555641
Java: https://codeforces.com/contest/1624/submission/290556762
=> Editorial Palindromes Coloring 

solutions/gold/cses-1653.mdx
=> correct page number

content/6_Advanced/SCC.mdx
=> py sol for Planets and Kingdoms

solutions/bronze/usaco-1228.mdx
close #4926
i swear i tested this!!
=> remove unnecessary checks in counting liars

solutions/silver/cf-632C.mdx
AC: https://codeforces.com/contest/632/submission/292353570
=> py sol for cf-632C

solutions/gold/usaco-694.mdx
=> py sol for hps

content/6_Advanced/SPneg.mdx
AC: https://cses.fi/paste/2dc3861cb9075445a62428/
I used `INF` because using `float('inf')` results in WA for 3 TCs
=> py sol for Cycle Finding

content/4_Gold/Shortest_Paths.problems.json, solutions/gold/ioi-11-crocodile.mdx
i finally remembered to link the official solution lol
=> IOI Crocodile Editorial

solutions/silver/cf-1000C.mdx
AC1: https://codeforces.com/contest/1000/submission/293515962
AC2: https://codeforces.com/contest/1000/submission/293514601
=> py sols for cf-1000C

solutions/silver/cc-TRPTSTIC.mdx, solutions/silver/cf-702C.mdx
AC: https://www.codechef.com/viewsolution/1110964545
=> py sol for TripTastic

content/3_Silver/Binary_Search.problems.json, solutions/silver/cf-1117C.mdx
=> update binary search problems.json

solutions/gold/cses-1635.mdx
=> update coin combinations I

solutions/gold/usaco-574.mdx
=> update fruits feast

solutions/silver/usaco-858.mdx
=> py sol for usaco-858

content/team/contributors.ts
=> change evan to board

content/4_Gold/DP_Bitmasks.mdx
Added a Python solution to Hamiltonian Flights, content/4_Gold/DP_Bitmasks.mdx.
Let me know if there are any optimizations to be made because I can't find any. This seems to be the fastest solution for this time complexity, and to get a faster solution requires a better time complexity (not completely sure if that exists / still uses Bitmask DP).
Python3: https://cses.fi/problemset/result/11270874/ (TLE, optimized the same as C++ code)
PyPy3: https://cses.fi/problemset/result/11270928/ (TLE, slower: worse case not including TLE is 0.06s)
My Python3: https://cses.fi/problemset/result/11270851/ (my own solution, somewhat different than C++ solution)
My original unoptimized _strangely done_ Python solution takes 0.04 worst case (not including TLE) which is slightly slower than the optimized …
=> Python Sol for Hamiltonian Flights in DP Bitmasks Module

solutions/silver/usaco-895.mdx
- added editorial to problem solution
- rewrote c++/java/python solutions so they are all consistent in implementation/comments/structure
- fixed python solution to pass ALL test cases (old solution TLE)
=> Icy Perimeter Editorial

solutions/silver/usaco-860.mdx
- added explanation to code
- rewrote c++/java/python solutions to keep consistency in impl/comments/variables
- very minor change but clarified the official analysis is in c++
=> Mooyo Mooyo Editorial

solutions/silver/apio-11-TableColoring.mdx
=> minor change

solutions/silver/cc-AMONGUS2.mdx
AC: https://www.codechef.com/viewsolution/1114028226
=> py sol for Among US

solutions/silver/cf-1365D.mdx, solutions/silver/usaco-380.mdx
=> add official editorial languages

solutions/silver/cc-AMONGUS2.mdx
It doesn't show any difference in files changed but it was like this.
=> minor formatting

solutions/silver/usaco-596.mdx
=> py sol for Build Gates

solutions/bronze/usaco-617.mdx
- added explanation
- tweaked c++ code a bit for simplicity/convention
=> Load Balancing Editorial

solutions/gold/usaco-993.mdx
- Revised explanation
- Updated C++, Java, and Python implementations
- Standardized comments across all implementations
- Revised readability and structure of the code
=> Time is Mooney Editorial

src/components/MarkdownLayout/NavBar.tsx
=> Fix for navbar

solutions/bronze/usaco-664.mdx
- added explanation to solution page
=> Block Game Editorial

src/components/TopNavigationBar/TopNavigationBar.tsx
=> December Contest Banner

content/3_Silver/More_Prefix_Sums.mdx
- [x ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
=> fix error with Maximum Subarray Sum solution

solutions/platinum/baltic-17-toll.mdx
AC: https://oj.uz/submission/1127133
=> py sol for baltic toll

solutions/gold/cses-1653.mdx
=> Elevator Rides Editorial

content/3_Silver/Sorting_Custom.mdx
=> Typo Fix in Custom Comparators (Silver)

content/2_Bronze/Complete_Rec.mdx, content/4_Gold/Hashmaps.mdx, content/4_Gold/LIS.problems.json, solutions/gold/cfgym-102951C.mdx
=> use archived mark nelson links

solutions/silver/usaco-714.mdx
=> Why Did the Cow Cross the Road Editorial

content/4_Gold/Digit_DP.problems.json, solutions/gold/spoj-DigitSum.mdx
=> digit sum thing

src/components/TopNavigationBar/TopNavigationBar.tsx
=> spring classes banner

content/3_Silver/Two_Pointers.problems.json, solutions/silver/cf-1777C.mdx
AC (C++): https://codeforces.com/contest/1777/submission/301621458
AC (Python): https://codeforces.com/contest/1777/submission/301621495
=> Quiz Master Editorial

solutions/silver/cf-1223C.mdx
=> formatting

content/5_Plat/DP_SOS.mdx
cc envy 🙏 
relevant problems: 
https://usaco.org/index.php?page=viewproblem2&cpid=1452
https://usaco.org/index.php?page=viewproblem2&cpid=1309
any other examples from usaco?
=> SOS DP (Rare -> Not Frequent)

content/6_Advanced/Persistent.mdx, content/6_Advanced/Persistent.problems.json, content/6_Advanced/Wavelet.mdx
Added 3 interesting problems from spoj about persistent segment tree
=> Update Persistent.problems.json (added 3 problems from spoj and some resources)

solutions/silver/cf-276C.mdx
=> add official editorial link

content/3_Silver/More_Prefix_Sums.problems.json
=> update difference array problems.json

content/6_Advanced/Offline_Del.mdx
Issue no: #4165 
AC: https://judge.yosupo.jp/submission/264335
=> py sol for vertex add comp sum

content/2_Bronze/Intro_DS.mdx
=> Fixed explanation of memset behavior for 32-bit array.

.github/workflows/update-usaco.yml
...since this step is causing the auto-updates to fail + it appears the relevant data is no longer available.
=> Stop updating contest to points

content/3_Silver/More_Prefix_Sums.problems.json, solutions/silver/cf-104114N.mdx
closes: #4916 
AC: 
C++: https://codeforces.com/gym/104114/submission/305205755
Python: https://codeforces.com/gym/104114/submission/305203095
=> Nusret Gökçe Editorial

content/3_Silver/Conclusion.problems.json, solutions/silver/cf-2060E.mdx
AC:
DFS: https://codeforces.com/contest/2060/submission/306174024
DSU: https://codeforces.com/contest/2060/submission/306178540
=> Graph Composition Editorial

solutions/silver/usaco-923.mdx
- [X (inapplicable)] I have tested my code.
- [X (inapplicable) ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X (inapplicable) ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
- [X (inapplicable) ] I have linked this PR to any issues that it closes.
Summary: minor edit to rather confusing wording in original explanation + elaboration for clarity on provided example.
=> Gold Problem: Painting The Barn - Minor Explanation Edit

solutions/silver/usaco-1016.mdx
- [X (inapplicable)] I have linked this PR to any issues that it closes.
Summary: Python translation of USACO Guide's C++ solution for 2020 Feb. Silv. Problem 3: Clock Tree; tested & passed all test cases.
=> Silver Problem: Clock Tree - Added Python Translation For Guide's Solution

solutions/bronze/usaco-965.mdx
=> Added Java solution for problem 965, maintaining equivalent logic and comments

content/2_Bronze/Complete_Rec.mdx
=> update perm initialization

solutions/silver/cf-104114N.mdx
=> Add Java solution for CF-104114N

content/3_Silver/More_Prefix_Sums.problems.json, solutions/silver/cf-816B.mdx
AC:
C++:https://codeforces.com/contest/816/submission/307551772
Java:https://codeforces.com/contest/816/submission/307554608
Python3: https://codeforces.com/contest/816/submission/307552904
=> Karen and Coffee Editorial

content/1_General/Running_Code_Locally.mdx
=> Fixed a typo

src/components/markdown/ProblemsList/ProblemsListItemDropdown.tsx
kind of a messy sol, but it should be a one-off fix 👀 didn't want to touch problemlistitemsolution
=> Manually Add "Internal Sol" Dropdown Item to Monthlies Table

src/components/ContactUsSlideover/ContactUsSlideover.tsx
=> bold CPI classes note in contact form

solutions/bronze/usaco-784.mdx
=> lifeguards bronze polish

content/3_Silver/Binary_Search.problems.json, solutions/silver/cses-1620.mdx
=> update Factory machines

solutions/silver/cf-276C.mdx
AC: https://codeforces.com/contest/276/submission/309636384
=> java sol for Little Girl and Maximum Sum

solutions/silver/cses-1660.mdx
=> java sol for Subarray Sums I

solutions/bronze/usaco-665.mdx
- added explanation to internal solution pages (woohoo)
=> The Cow-Signal Editorial

solutions/bronze/dmoj-spirale.mdx
🔹 Pull Request Title:
"Added Java solution for Spirale problem (Bronze)"
🔹 Pull Request Description:
Summary
This PR adds a Java solution for the Spirale problem in the Bronze category of the USACO Guide.
The Java implementation follows the same logic as the existing C++ and Python solutions, ensuring correctness and efficiency.
Explanation of the Approach
Matrix Initialization:
A 2D array mat[][] is initialized with Integer.MAX_VALUE to store the minimum distances.
Distance Update Function (updateDistance)
This function updates the matrix with the minimum distance encountered for each cell.
Input Handling:
Reads the grid dimensions (n, m) and the number of starting points (k).
Spiral Movement Simulation:
Each starting position follows a spiral traversal, updating distances accordingly. …
=> Added Java solution for Spirale problem  at   usaco-guide/solutions/bronze /dmoj-spirale.mdx

solutions/bronze/usaco-1251.mdx
- added Java solution code, matching w/ C++ and Python solutions. (used Scanner since it passes, faster IO not required)
=> Cow College Java Solution

solutions/silver/usaco-859.mdx
=> upd java code to PQ

content/6_Advanced/Interactive.problems.json, solutions/advanced/joi-20-StrayCat.mdx
If you'd like code I can add it, but I'm kinda too lazy to format my code rn
https://oj.uz/submission/1167015
submission here if you want it
=> Stray cat solution

solutions/gold/cses-1080.mdx
=> added solution to CSES problem number 1080 Empty Strings

solutions/silver/cf-702C.mdx
=> Cellular Network Binary Search Editorial

solutions/bronze/usaco-592.mdx
=> angry cows eeditorial

content/2_Bronze/Intro_Sorting.problems.json, solutions/bronze/cf-104520H.mdx
=> permutator editorial

solutions/silver/cf-1826D.mdx
AC: https://codeforces.com/contest/1826/submission/311314044
=> Running Miles (JAVA)

content/2_Bronze/Conclusion.problems.json, solutions/bronze/cf-104520H.mdx, solutions/bronze/cfgym-104417G.mdx
=> matching sol

content/2_Bronze/Conclusion.problems.json, solutions/bronze/cf-1873G.mdx
yeah i submitted trust me you can check my codeforces profile
=> abbc or smth i forgor

solutions/bronze/usaco-856.mdx
=> Bucket List Editorial

solutions/bronze/usaco-568.mdx
=> Speeding Editorial

content/2_Bronze/Intro_Sets.problems.json, solutions/bronze/cf-1209G1.mdx
=> into blocks editorial

solutions/bronze/usaco-916.mdx
I SWEAR I SUBMITTED EVERYTHING TRUST ME
=> revegetate revamp

package.json, src/components/MarkdownLayout/MarkdownLayout.tsx, src/components/markdown/ListTable/ListTable.tsx, src/components/markdown/ListTable/ListTableRow.tsx, src/components/markdown/ProblemsList/ProblemsList.tsx, src/components/markdown/ProblemsList/ProblemsListHeader.tsx, src/components/markdown/ProblemsList/ProblemsListItem.tsx, src/components/markdown/ResourcesList.tsx, src/components/markdown/ResourcesListItem.tsx, src/stories/markdown/Problems.stories.tsx, src/styles/main.css, src/templates/moduleTemplate.tsx, yarn.lock
=> Refactor Resource Table and Problem Table

solutions/silver/cf-1851F.mdx
- added java solution to internal solution pages
=> Lisa and the Martians Java Solution

solutions/gold/sumdiv.mdx
The comment of a is coprime with 10^9+7 is not correct.
=> Improve comments in sumdiv.mdx

solutions/silver/cses-2185.mdx
- added java solution to internal solution pages
=> Prime Multiples Java Solution

solutions/bronze/usaco-639.mdx
=> Diamond Collector Editorial

content/2_Bronze/Conclusion.problems.json, solutions/bronze/cf-1772D.mdx
=> absolute sorting sol

solutions/bronze/usaco-1181.mdx
=> Drought Redo

solutions/silver/usaco-1327.mdx
- added java solution to internal pages (same style, identical to c++/py solutions)
=> Field Day Java Solution

solutions/silver/usaco-624.mdx
=> C++ sol for Load Balancing

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Add workshop to banner

content/1_General/Adding_Solution.mdx, content/1_General/Contributing.mdx
=> contributing updates

solutions/silver/ceoi-10-AHugeTower.mdx
AC:
https://oj.uz/submission/1178899
https://oj.uz/submission/1178896
https://oj.uz/submission/1178905
=> Tower redo

solutions/silver/cf-1468D.mdx
https://codeforces.com/contest/1468/submission/314091178
https://codeforces.com/contest/1468/submission/314098048
=> Firecrackers redo

solutions/silver/cf-1744F.mdx
AC:
https://codeforces.com/contest/1744/submission/314007465
=> MAX vs MED 

content/4_Gold/TopoSort.problems.json
good problem
(also related to a CF problem that appeared today)
=> TopoSort Module: add abc304 h

solutions/silver/cf-51C.mdx
https://codeforces.com/contest/51/submission/314066931
https://codeforces.com/contest/51/submission/314065308
https://codeforces.com/contest/51/submission/314068210
=> Three Base Stations redo

solutions/silver/cf-1017D.mdx
- added Java solution to internal solution pages (identical to c++ code)
=> The Wu Java Solution

solutions/silver/cf-1077D.mdx
https://codeforces.com/contest/1077/submission/314109102
=> Cutting Out (JAVA)

solutions/silver/apio-11-TableColoring.mdx
AC:
Py: https://dmoj.ca/submission/7101238
Java: https://dmoj.ca/submission/7101207
C++: https://dmoj.ca/submission/7101203
=> table coloring redo

content/2_Bronze/Intro_Complete.problems.json, solutions/bronze/usaco-1324.mdx
i actually did submit
picture of me submitting
=> moo lang editorial

content/2_Bronze/Conclusion.problems.json, solutions/bronze/usaco-509.mdx
lmk if i should make the code reflect the non-2ptr approach
i think that might be a bit more suitable
=> it's all about base edi

solutions/silver/cf-1520F1.mdx
AC: http://codeforces.com/contest/1520/submission/315047200
=> Guess the K-th Zero Java Code

solutions/silver/cf-1088D.mdx
AC: https://codeforces.com/contest/1088/submission/315051532
=> Ehab and another another xor problem Java Code

solutions/silver/cf-847B.mdx
AC: https://codeforces.com/contest/847/submission/315049705
=> Preparing for Merge Sort Java Code

solutions/silver/usaco-788.mdx
=> Mootube Editorial

content/1_General/Generic_Code.mdx
=> Fixed a typo on content/1_General/Generic_Code.mdx

solutions/silver/cf-847E.mdx
=> formatting a bit off

content/6_Advanced/BCC_2CC.problems.json, solutions/advanced/poi-08-blockade.mdx
=> [Editorial] Blockade 

solutions/bronze/usaco-615.mdx
=> Milk Pails Explanation

solutions/silver/usaco-811.mdx
- redid the editorial for the internal solution pages (google spreadsheet with incomplete problems said old the explanation was too short and not detailed enough)
=> Snow Boots Editorial

solutions/bronze/cf-1846D.mdx
=> remove unnecessary line

solutions/silver/usaco-919.mdx
=> Painting the Barn Editorial

solutions/silver/cf-104002E.mdx
AC:
JAVA: https://codeforces.com/gym/104002/submission/318132204
Python: https://codeforces.com/gym/104002/submission/318132734
=> William and Robot [ Py / Java] 

solutions/bronze/usaco-964.mdx
=> Where Am I? Editorial

solutions/silver/leetcode-502.mdx
AC: https://leetcode.com/problems/ipo/submissions/1624391115/
=> IPO [Java]

solutions/bronze/usaco-736.mdx
=> Bovine Genomics

content/4_Gold/Knapsack_DP.problems.json, solutions/gold/ac-subsetSumQueries.mdx
AC
JAVA: https://atcoder.jp/contests/abc321/submissions/65398528
Python:https://atcoder.jp/contests/abc321/submissions/65398340
C++: https://atcoder.jp/contests/abc321/submissions/65068446
=> Subset Sum Queries

content/4_Gold/Knapsack_DP.problems.json, solutions/gold/cf-687C.mdx
AC:
C++: https://codeforces.com/contest/687/submission/317269498
JAVA: https://codeforces.com/contest/687/submission/318097130
PYTHON: https://codeforces.com/contest/687/submission/317272028
=> The Values You Can Make

solutions/bronze/usaco-963.mdx
- clarified official analysis is in c++
- added time complexity to solution 1 implementation
- fixed c++ video solution formatting (weird indentation)
=> Cow Gymnastics Editorial

solutions/gold/usaco-897.mdx
=> Cow Poetry [Py / Java]

solutions/bronze/usaco-785.mdx
=> Out of Place Editorial

src/components/TopNavigationBar/TopNavigationBar.tsx
=> Banner Switch

content/1_General/Expected_Knowledge.mdx
=> update VPlanet url

solutions/gold/usaco-1045.mdx
=> remove extra link

solutions/silver/cses-2179.mdx
- added Java solution to internal solution pages (same style, variables, formatting, etc. to C++ code for consistency)
=> Even Outdegree Edges Java Solution

solutions/bronze/cses-1640.mdx
=> Sum of Two Values [Major Formatting]

content/4_Gold/Conclusion.problems.json, solutions/gold/cf-1918D.mdx
cba to add python and java i'm ngl
ac: https://codeforces.com/contest/1918/submission/322453226
=> blocking elements sol

solutions/bronze/usaco-963.mdx
=> Cow Gymnastics Editorial 2

solutions/bronze/usaco-893.mdx
* Added explanation to internal solution
=> Guess the Animal Explanation

content/3_Silver/Graph_Traversal.problems.json, solutions/bronze/usaco-893.mdx, solutions/silver/cf-1176E.mdx
=> Cover it everything

solutions/silver/usaco-416.mdx
on EVERYONE'S soul i've tested this code on the oj as well as the tc in #5380
=> fix lazy cow impl

content/3_Silver/Conclusion.problems.json, solutions/silver/cf-1775D.mdx
ac: https://codeforces.com/contest/1775/submission/324579257
i'll first get the core parts (c++/edi) out, then tl later
=> not the best editorial for spiders but it is what it is

solutions/silver/cf-1777C.mdx
- added Java solution (matches C++ style, variables, comments, etc)
- changes += 1/-= 1 to ++/-- in C++ solution
=> Quiz Master Java Solution

content/3_Silver/Conclusion.problems.json, solutions/silver/cf-1620E.mdx
ac:https://codeforces.com/contest/1620/submission/324701454
i'll add cpp/java after baseline is approved
=> replace the numbers py + edi

content/3_Silver/Conclusion.problems.json, solutions/silver/cf-1856C.mdx
ac: https://codeforces.com/contest/1856/submission/324960454
=> to become max

content/3_Silver/Conclusion.problems.json, solutions/silver/cf-1638D.mdx
ac: https://codeforces.com/contest/1638/submission/324950651
=> big brush edi/c++

content/3_Silver/Conclusion.problems.json, solutions/silver/cf-1722E.mdx
ac: https://codeforces.com/contest/1722/submission/325045056
=> counting rectangles edi/c++

content/3_Silver/Conclusion.problems.json, solutions/silver/ac-fennecvssnuke.mdx
ac: https://atcoder.jp/contests/arc078/submissions/66873945
=> fennec vs snuke edi/c++

content/3_Silver/More_Prefix_Sums.mdx
=> More Prefix Sums - Fix Unclear Explanation

content/2_Bronze/Intro_DS.mdx, content/2_Bronze/Intro_Greedy.mdx, content/2_Bronze/Intro_Sets.mdx, content/2_Bronze/Rect_Geo.mdx
Several modules in `/2_Bronze` contain Java and Python code blocks that either lack inline comments or do not provide clear, beginner-friendly explanations. This makes it harder for new learners to understand the code, especially if they are not familiar with the language. I added comments and explanations in the affected files to improve unclear code/explanations.
=> Improved Explanations and Code Comments in Modules

solutions/bronze/usaco-989.mdx
=> Race [Explanation / Py]

content/2_Bronze/Rect_Geo.mdx, content/2_Bronze/Rect_Geo.problems.json
- Shorten Blocked Billboard code
- add note to last module section about being skippable
- adjust module problem relative difficulties (I think the last three practice problems are harder than the in-module examples)
=> rect geo - minor module upds and difficulty adjustment

content/2_Bronze/Intro_Graphs.mdx, content/2_Bronze/Intro_Graphs.problems.json, content/2_Bronze/Intro_Sets.mdx, solutions/bronze/usaco-833.mdx, solutions/bronze/usaco-916.mdx, solutions/bronze/usaco-941.mdx
=> add to Bronze graph internal sols

solutions/bronze/cf-581D.mdx
=> Add alternative solution for cf-581D

content/2_Bronze/Intro_Graphs.mdx
=> Java Translation for Constructing Adjacency Lists in Introduction to Graphs Bronze

content/extraProblems.json
=> fix majority opinion json (accidentally left usacoID in)

content/1_General/Adding_Solution.mdx
There are some portions I agree with and some I don't. For the most part, the portions I agree with can already be found in the module or in the Google style guide linked later in the module.
Please comment if there is some part of the guidelines that is especially important to keep within the Guide.
=> remove more in-depth code convention guidelines

solutions/gold/ac-constructapalindrome.mdx
https://forum.usaco.guide/t/question-about-time-complexity-of-solution/7904
=> Fix time complexity for ABC 197F Construct a Palindrome in Gold Unweighted Shortest Paths

content/5_Plat/Sweep_Line.mdx
=> Add code for closest-pair second solution

src/components/Editor/EditorSidebar/EditorSidebar.tsx
=> fix when user has more than 30 repos

content/3_Silver/Conclusion.problems.json
URL: https://usaco.guide/silver/silver-conclusion
Module: Silver - Additional Practice for USACO Silver Topic: Mistake
Message:
Problem: 2013 - Dreaming
Correct Source: IOI
Previous: other
=> Corrected source of IOI Problem 2013-Dreaming

content/3_Silver/Priority_Queues.mdx
=> feat: add Python solution for Priority_Queues.mdx

content/4_Gold/TopoSort.problems.json, solutions/gold/ac-abc304_h.mdx
Ref: https://forum.usaco.guide/t/usaco-gold-topological-sort-constrained-topological-sort/7922
Editorial did not have code so I added my own implementation
AC submission: https://atcoder.jp/contests/abc304/submissions/68003469
=> add impl for abc304h

content/4_Gold/Ternary_Search.mdx
=> feat: add Python examples and solution for Ternary_Search.mdx

content/4_Gold/Divisibility.mdx
=> [MinorFix][Typo] fixed from "linew" to "lines"

solutions/silver/usaco-1062.mdx
- added Java code to Sol 2, same as C++ code
=> Cowntagion Java Solution

content/3_Silver/Graph_Traversal.problems.json, content/3_Silver/Greedy_Sorting.problems.json, content/3_Silver/Intro_Bitwise.mdx, content/3_Silver/Intro_Tree.problems.json, content/extraProblems.json
=> Added 3 problems, and also code in Intro Bitwise module

solutions/bronze/usaco-1227.mdx
- added explanation to solution pages (because originally there were 2 hints and no explanation :skull:)
=> Photoshoot Editorial

solutions/bronze/usaco-1084.mdx
- another editorial at midnight cuz why not
=> Even More Odd Photos Editorial

solutions/silver/cf-104536F.mdx
- added java solution to internal pages (the usual biz)
=> Minimize the Diameter Java Solution

solutions/silver/usaco-1064.mdx
- redid the C++ solution since the original used a template and was a bit messy
- new code matches Java for consistency
=> Stuck in a Rut C++ Solution

solutions/gold/cf-472D.mdx
- added explanation to internal sol page
=> Design Tutorial Inverse the Problem Editorial

solutions/bronze/usaco-940.mdx
=> Milk Factory Editorial

solutions/silver/usaco-690.mdx
- fast one but added "Implementation" before code and move time complexity so that its visible from java and python
- originally only could see time complexity with c++
- yes ill take a chill pill for a week
=> Cow Dance Show Formatting

solutions/bronze/usaco-617.mdx
=> Update usaco-617.mdx to include Time Complexity

src/components/Index/ContributorsSection.tsx, yarn.lock
I modified the CSS for the `MemberCard` component so that the images will not be too zoomed in or cropped.
Old: 
New:
=> Contributors section images

content/6_Advanced/String_Search.problems.json
=> update difficulty order

solutions/bronze/usaco-713.mdx
=> Why Did the Cow Cross the Road III Editorial

solutions/silver/usaco-764.mdx
- added explanation to internal solution pages yipster hipster hooray
=> The Bovine Shuffle Editorial

solutions/gold/usaco-1138.mdx
- this was a fun one to write
- midnight PRs are back :skull: (no more this week trust)
=> Portals Editorial

solutions/silver/usaco-992.mdx
Closes #5626
removed `max_width` in solution 3 as its unnecessary.
=> Update usaco-992.mdx - Removed redundant piece of code.

solutions/general/usaco-591.mdx
=> Promotion Counting

src/components/TopNavigationBar/TopNavigationBar.tsx
I changed the `Banner` to advertise the problem writers application for the guide contest
=> Problem Writers Ad

solutions/bronze/usaco-809.mdx, solutions/bronze/usaco-892.mdx
=> Ad Hoc Problems minor upd

solutions/silver/usaco-690.mdx
- added explanation in internal sol pages
=> Cow Dance Show Editorial

content/3_Silver/Greedy_Sorting.problems.json, solutions/silver/usaco-1350.mdx
=> usaco-1350 sol

content/5_Plat/Binary_Jump.problems.json, content/5_Plat/HLD.problems.json, content/5_Plat/Merging.problems.json, content/6_Advanced/BCC_2CC.problems.json, solutions/platinum/usaco-842.mdx
=> Add solution for usaco-842

solutions/bronze/usaco-739.mdx
213 base 4 to base 10 is 39
2 * 16 + 1 * 4 + 3 * 1 = 32 + 4 + 3 = 39
=> fix typo usaco-739

content/6_Advanced/Multiplicative.mdx
Corrected expressions for the sum of Euler's totient function explanation.
This PR closes #5664
=> Fix formula for summing Euler's totient function

solutions/gold/usaco-1474.mdx
usaco was down yesterday so i didnt test
current code is tested
=> fix wa18 on usaco-1474

solutions/silver/usaco-1064.mdx
- quick one (added language to editorial hyperlink)
=> Stuck in a Rut Formatting

content/4_Gold/Sliding_Window.mdx, content/4_Gold/Sliding_Window.problems.json
=> Problems added in Module Sliding_Window
