solutions/JOI 13-bubblesort.mdx

At least, I think this is a typo?

content: fix small typo in bubblesort editorial

---

content/2_Bronze/Time_Comp.mdx

not sure if it was intentional but "node" was used instead of "code."

typo fix from Time_Comp.mdx

---

content/1_General/IO.mdx

In Python 3 "/" will result in a float, so it must be "//" which will be an int.

Typo for Python 3 example solution "Weird Algorithm"

---

content/1_General/Running_Code_Locally.mdx

I clarified the `PATH` note for Windows and added a link to some instructions.

Clarify Java PATH note

---

content/1_General/Contests.mdx
docs/Content Documentation.md
src/models/problem.ts

DMOJ no longer stands for Don Mills Online Judge.

remove outdated DMOJ acronym

---

content/3_Silver/Func_Graphs.mdx

The previous code had a bug when a node pointed to a node that pointed to itself. Because the node that pointed to itself would return -1, the node pointing to it would consider itself part of the cycle, when it should not be. The codeforces test cases (strangely) must not have had such an example, as the previous code AC'd. The testcase below (from Planet Cycles cses) is an example of such a case, in which 3 points to 8 which points to itself.
10
4 7 8 10 5 7 4 8 3 7
The previous code outputs
4 7 **3** 4 5 7 7 8 3 10 
when it should output
4 7 **8** 4 5 7 7 8 3 10 
which it does with the few characters modified in this pr.

Fix bug in silver successor graph solution to "Badge"

---

content/1_General/Fast_IO.mdx

Resolves https://forum.usaco.guide/t/different-types-of-fast-io/729 (not complete)
If someone could find an example for `cin.tie(0)` that would be great.

Elaborate on fast i/o

---

src/components/markdown/CodeBlock/CodeBlock.tsx

note: this replaces *all* instances of four spaces with a tab, regardless of whether the .mdx file was using four spaces or a tab.
this probably will create some issues:
- If the code is supposed to use a mixture of tabs and spaces, then all the spaces will be converted to tabs.
- If the code is poorly formatted (with two/three spaces), the tabs will get messed up.
closes #768

replace four spaces with tab in code block

---

gatsby-config.ts
src/components/DynamicMarkdownRenderer.tsx
src/components/markdown/CodeBlock/CodeBlock.tsx
src/mdx-plugins/rehype-snippets.js

A few problems I can fix if they need to be fixed:
- The "replacement text" (aka stuff in curly braces that is placed on the snipped line) is not formatted.
- Directly used style instead of a class
A few problems someone better than me needs to fix if they cause problems:
- If the majority of the code is snipped off, then the collapse detection fails.
- Did not use modern react stuff (I had to resort to `class ... extends React.component`)
- The part that detects BeginCodeSnip maybe hinders runtime
Use:
Put "`BeginCodeSnip{any random replacement text}`" somewhere in the code block and "`EndCodeSnip`" somewhere else. Everything on these 2 lines are deleted, and everything between them are code snips that are automatically minimized. There's buttons that can maximize it. I found the …

CodeBlock: Add Code Snips (excuse the spaghetti)

---

content/3_Silver/Prefix_Sums.mdx

Since [haybale stacking](http://www.usaco.org/index.php?page=viewproblem2&cpid=104) isn't submittable on USACO, your Guide's [Prefix Sums Silver](https://usaco.guide/silver/prefix-sums?lang=cpp#problems) module has a little note saying "use this link to submit." Previously, the link led to [this](https://www.acmicpc.net/problem/5912) Korean site that has a little link at the bottom to submit via https://www.spoj.com/problems/HAYBALE/, an English site. I've updated the Guide to just link directly to the English site.

Update alternative online judge

---

content/4_Gold/TopoSort.mdx

Also noted that the code doesn't do it
Closes https://github.com/cpinitiative/usaco-guide/issues/890

Clarify that BFS can be used to get the lexographically smallest toposort

---

content/6_Advanced/Min_Cut.mdx

Change problem link from https://maps20.kattis.com/problems/thewrathofkahn to https://open.kattis.com/problems/thewrathofkahn so people can submit to the judge without being an official participant

Change problem link

---

solutions/POI 04-mak.mdx

This is because it's actually dp[...][j] that depends on dp[...][j - 1], but I'm not sure how to word that nicely

Fixed array indexing in POI 04 Mak editorial(?)

---

src/pages/dashboard.tsx

`moduleId` was deleted so the statistics section was showing 0 problems. I noticed that the dashboard problem total doesn't match the problem total in the section, is this because some problems show up in multiple sections/modules?

Fix dashboard problem statistics

---

content/2_Bronze/Complete_Rec.mdx
content/2_Bronze/Rect_Geo.mdx
content/2_Bronze/Simulation.mdx

I wanted to make code from some bronze modules easier to read by adding Kattio instead of buffered reader and formatting the code to follow Java conventions. The reformatted code has all been tested.

Reformat + simplify java code from bronze modules

---

src/components/ProblemsPage/ProblemHits.tsx

The problem name being block made the star appear on the next line.
Is there anything else that needs to be changed about the problems page? The clickable problem name makes the view problem statement redundant, but since it's not obvious that the problem name is clickable, people who are used to clicking the link below might not know what happened.
The link styling is also inconsistent; only the title underlines when hovered and they're all different colors.

Inline problem name on problems page

---

content/1_General/Fast_IO.mdx

If you see [here](https://usaco.guide/general/fast-io?lang=cpp#method-4---fread-and-fwrite), the include for bits/stdc++.h is missing.

Added include to bits/stdc++

---

content/4_Gold/Intro_DP.mdx

Like [last time](https://github.com/cpinitiative/usaco-guide/pull/998), I guess screenshot the blog directly to review it. A link can be found [here](https://nwatx.me/post/atcoderdp), or you can PR [source](https://github.com/nwatx/nwatx-blog/blob/main/content/atcoderdp.mdx) directly I guess.

add editorial for atcoder dp contest + small wording fixes

---

src/components/ProblemsPage/ProblemHits.tsx
src/pages/problems.tsx

closes #1762 
I also increased the tag limit to 500, since the original tag limit of 100 didn't show all the tags, making it hard to search for problems tagged "Sorting" or "Simulation", for example. I can revert if this change isn't good, though.
I think that limiting tags to 100 is fine, except the tags are sorted alphabetically, so it doesn't make sense. It might be better to sort tags by their frequency and limit to the 100 most frequent tags.

increase tag limit + fix tag alignment

---

content/5_Plat/Convex_Hull.mdx

BTW, the link to the animation provided for Graham Algorithm seems broken. See [Graham->Worked Example](https://usaco.guide/plat/convex-hull?lang=java#solution)
The java code passed both test cases on Kattis. But I think those tests are weak.

Added Monotone Chain Algorithm and implementations to Convex Hull module (plat)

---

src/components/Dashboard/Activity.tsx

If you solve a problem and unsolve/solve a few times, the activity in the chart will increase. This pr fixes it so that activity is only counted once per problem or module per day.
This doesn't fix some other problems such as solve + unsolve still counting as a solve, but hopefully makes the calculations a bit more accurate.

Fix multiple activity counts for the same problem

---

content/1_General/Running_Code_Locally.mdx

Closes #2140 
It's not the 2019 IOI (their website doesn't exist anymore), but i think this is still relevant.

Fix Link for IOI

---

package.json
yarn.lock

I think vercel is unable to install broken-link-checker from github for some reason...

Install broken-link-checker from registry

---

solutions/cses-1196.mdx

macro was `pi` standing for `pair<int, int>`, not `pii`
hence corrected 
`vector<pii> adj[MX];` 
to 
`vector<pi> adj[MX];`

Fixed typo.

---

content/2_Bronze/Intro_Sets.mdx

found some inconsistencies, but most of them were in java. unfortunately, i don't code in java, so someone else might be able to address this, @nathangong, @Navigator365 ? 
if anyone finds any more issues, lmk!
Issues I found:
- different example on iterating over maps. java uses a set (bronze) (fixed, thanks @nathangong!)
- example isn't given in multiset section (silver)
fixes #2349
---
done._

fix some minor inconsistencies in set module (bronze)

---

content/1_General/Input_Output.mdx
src/mdx-plugins/rehype-snippets.js

As discussed in https://forum.usaco.guide/t/can-i-use-the-default-starting-code-that-comes-with-every-new-project-on-ide-usaco-guide/2511

Java IO - add warning regarding USACO contests, correct a mistake

---

content/2_Bronze/Rect_Geo.mdx

Fix the return type of the function that checks if two rectangles intersect. It must be `bool`.
Solving issue #2543

Fix the intersect function's return type

---

content/2_Bronze/Time_Comp.mdx

In the Time_Comp.mdx file, from the Bronze section, there is an error in the java code block at line number 356
`for(int i = i; j <= m; i++)` is erroneous and must be changed to `for(int i = 1; i <= m; i++)`

Found erroneous code at line 356

---

solutions/cses-1753.mdx

In the Knuth–Morris–Pratt algorithm C++ solution for "String Matching", the code does not work due to:
1. there is a missing semicolon which is an syntax error
2. variable `j` is uninitialized which causes segmentation error on most machines I've tested on.
This small fix makes the code snippet work.

Fix semicolon and uninitialized variable

---

src/components/markdown/CodeBlock/CodeBlock.tsx
src/components/markdown/HTMLComponents.tsx
src/components/markdown/Quiz.tsx

fixes an issue where the intro-ds page would glitch upon reload (thanks @cirex-web for reporting)
basically the dom nesting was invalid because of nested `buttons`, so i just removed the copy button when the right answer hasn't been selected yet

quiz codeblock fix

---

content/6_Advanced/Vectorization.mdx

It turns out pragmas do work for USACO as mentioned in [a recent editorial](http://www.usaco.org/current/data/sol_prob3_silver_open22.html). Updated this module accordingly.

Update Vectorization.mdx (Pragmas actually work for USACO)

---

solutions/usaco-569.mdx

Sick events must be before drinking events if they occur at the same time.

Update Problem Explanation - Fix Events Sorting

---

content/3_Silver/DFS.problems.json
problemsList.ts
src/context/UserDataContext/properties/problemURLToIdMap.tsx

The two links changed, https://open.kattis.com/contests/acpc17open/problems/laneswitching and https://open.kattis.com/contests/mcpc19open/problems/basketballoneonone, do not allow submitting (they give an error when submitting). However, the new links, https://open.kattis.com/problems/laneswitching and https://open.kattis.com/problems/basketballoneonone respectively, do allow submitting. The problems are the exact same, just the links are different so they actually allow submitting. 
- If changes are requested, I will re-request the review after making the …

Fix Kattis contest links to problems

---

content/4_Gold/Combinatorics.mdx

We can calculate the modular inverses of factorials with a time complexity of O(n + log(p)) instead of O(n * log(p)) by using binary exponentiation only on the largest factorial and calculating the rest from there.

Better time complexity for modular inverses of factorials

---

.gitignore
firebase.json
src/context/UserDataContext/UserDataContext.tsx

closes #534. Also forces users to upload local data to server if they're creating an account for the first time.
If creating an account for the first time, we add a field `CREATING_ACCOUNT_FOR_FIRST_TIME` with value of `serverTimestamp()`. In firebase security rules, we allow user document *creation* as long as user ID matches. for document *updates*, we require `CREATING_ACCOUNT_FOR_FIRST_TIME` to not change. This prevents data writes where the client mistakenly thinks the account is just being created and accidentally overwrites user data.

prevent accidental user data override

---

src/pages/dashboard.tsx
src/templates/syllabusTemplate.tsx

- Resolves https://forum.usaco.guide/t/problem-progress-bug/3795. Now marking a problem as skipped should only increase the count by one.
- Ensures that dashboard problem counts match syllabus problem counts. currently, the dashboard shows fewer problems since it doesn't correctly take into account problems that belong to multiple sections

make dashboard and syllabus progress bars consistent

---

src/functions/README.md
src/functions/src/submitProblemSuggestion.ts

Problem suggestions are now assigned to be reviewed by the corresponding codeowners. Currently they aren't assigned to anyone.
(Alternatively, if we don't want to review problem suggestions, then we can disable problem suggestions altogether.)

disable removing reviewers for problem suggestions

---

solutions/bronze/usaco-1228.mdx

In the problem explanation for: [Counting Liars](https://usaco.guide/problems/usaco-1228-counting-liars/solution)
What if we add a little sentence ("after we sort the input") or something similar to the start of the explanation, since I was confused after reading the explanation (solution is not possible without sorting the input) but seeing the code cleared up my doubts, I think it should be mentioned in the explanation that we are sorting the input first before continuing on to explain further steps :)

Adding more context to the start of the explanation (Counting Liars)

---

docs/Front End Documentation.md
package.json
src/components/Groups/ProblemSubmissionPopup.tsx
src/components/Groups/SafeMarkdownRenderer.tsx
src/components/ProblemSolutions.tsx
src/components/QuizGeneratorModal.tsx
src/components/markdown/CodeBlock/CodeBlock.tsx
src/components/markdown/HTMLComponents.tsx
src/stories/markdown/CodeBlock.stories.tsx
src/styles/generalStyles.css
yarn.lock

Pull request for issue #3253
**Summary**: 
1. Make class component `CodeBlock` render with prism's light theme in light mode.
2. Add light mode styles for short snippet expand line, long snippet expand button and gradient
I couldn't use context hook in the class so I passed the `isDarkMode` as a required prop from parent components. I really need help testing this change as I'm not sure where to test some components below on website and possibly missed something.
Besides the …

Enable light mode code in light mode

---

src/components/markdown/ResourceStatusCheckbox.tsx
src/context/UserDataContext/UserDataContext.tsx
src/context/UserDataContext/properties/userProgressOnModules.ts
src/context/UserDataContext/properties/userProgressOnProblems.ts
src/context/UserDataContext/properties/userProgressOnResources.ts

closes #3396, #3425
I don't actually know if this works lol, but hopefully if data is lost we will only lose the data on that particular problem / module progress which is fine.
I think other places `setDoc` is used include daily # of pageviews, but I don't think it's that bad if that data is lost.
The scary part of using `updateData` is if the doc doesn't exist then it will crash and die. But this would only happen when the user account is first created, and I think once the account is created data is written anyway...

(try to) fix user progress on modules / problems deletion issue

---

content/4_Gold/Intro_Bitwise.mdx
content/4_Gold/Paths_Grids.mdx
solutions/bronze/usaco-526.mdx
solutions/bronze/usaco-941.mdx
solutions/gold/cf-1187E.mdx

closes #3307
I just looked through all the occurrences of `\\` and `\newline` ... 
is there a better way (e.g., get gatsby to print locations of warnings)? @thecodingwizard 

fix katex warnings

---

content/4_Gold/Hashmaps.mdx

Should have the value V (instead of null_type) for generic hash table.

Incorrect value for gp_hash_table

---

content/1_General/Generic_Code.mdx

In the previous pull I made the sz function take reference, but now I realize that const reference also allows to use sz for rvalues, `sz(some_func_returning_vector())`

sz() function now takes reference to const container

---

content/3_Silver/Intro_Bitwise.mdx

I removed the unnecessary backslashes in silver / intro to bitwise operators quiz answers.

fix bitwise operators quiz answers format

---

content/2_Bronze/Conclusion.problems.json
content/3_Silver/Graph_Traversal.problems.json
content/4_Gold/Combinatorics.problems.json
content/4_Gold/Intro_DP.problems.json
content/4_Gold/Shortest_Paths.problems.json
content/4_Gold/Tree_Euler.problems.json
content/5_Plat/2DRQ.problems.json
content/5_Plat/Binary_Jump.problems.json
content/5_Plat/Centroid.problems.json
content/5_Plat/DC-SRQ.problems.json
content/5_Plat/RURQ.problems.json
content/5_Plat/Sqrt.problems.json
content/6_Advanced/BCC_2CC.problems.json
content/6_Advanced/Comb_Sub.problems.json
content/6_Advanced/FFT.problems.json
content/6_Advanced/Flow_LB.problems.json
content/6_Advanced/LCT.problems.json
content/6_Advanced/Offline_Del.problems.json
content/6_Advanced/Persistent.problems.json
content/6_Advanced/String_Search.problems.json
content/6_Advanced/Wavelet.problems.json
content/extraProblems.json
solutions/advanced/dmoj-COCIPeriodni.mdx
solutions/gold/dmoj-Phidias.mdx
solutions/platinum/dmoj-BobEquilibrium.mdx
solutions/platinum/dmoj-FluidDynamics.mdx
solutions/platinum/dmoj-TimeTravellerImaxblue.mdx
solutions/silver/dmoj-rank.mdx
src/context/UserDataContext/old-properties/problemURLToIdMap.tsx
src/models/problem.ts

*tries* to close #3756, probably fails tho

dmoj problem labels?

---

content/3_Silver/Intro_Bitwise.problems.json
content/4_Gold/DP_Bitmasks.problems.json

It seems that a 2200-rated (codetiger.me/projects/usaco) Bitmask DP problem in the Intro to Bitwise Operator Silver section 

Fix location of Bitmask DP problem

---

solutions/bronze/usaco-1228.mdx

fix counting liars

---

solutions/gold/usaco-597.mdx

add editorial + cpp code to angry cows

---

src/atoms/editor.ts

put new solutions in the proper folder

---

content/6_Advanced/BCC_2CC.mdx

- [x ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
The missing check `(a == c || b == c)` has been added.
Tested: https://cses.fi/problemset/result/8374142/
Issue: https://github.com/cpinitiative/usaco-guide/issues/4274

Fixed bug in CSES: Forbidden cities solution

---

content/4_Gold/Digit_DP.problems.json
solutions/gold/cf-100886G.mdx

Solution purposely leaves out details to encourage more thinking, although if reader is truly stuck they can consult implementation
ac submission: https://codeforces.com/gym/100886/submission/245660915
#4165 

Solution for max product

---

solutions/gold/cses-1644.mdx

When maximizing the sum of subarrays between sizes **[A, B]**, the solution text talks about a sliding window of size **B**. Actually the sliding window is of size **B - A + 1**, the difference between the size bounds.
If the sliding window were of size **B**, the problem statement would be different: maximimzing the sum of subarrays **having a max size of B**.

Rectify solution description for CSES Max Sum Subarray II

---

solutions/gold/cses-1076.mdx

Since there is no "official" order statistics library in Java and the code is not insanely long, we can fit an implementation along with the solution. Instead of storing Pairs of <int, int>, we can modify the behaviour of each node to store the count of that key and correctly handle it when updating the `size` field (which is used in the order statistics operations). This is a little bit more efficient than storing each duplicate node separately along with its index.
Code is directly adapted from CLRS Introduction to Algorithms 3rd ed.

CSES Sliding Window Median - Java solution using Red-Black Order Statistics Tree

---

content/4_Gold/Conclusion.problems.json
solutions/gold/poi-sums.mdx

Solution for POI Sums

---

src/components/markdown/ProblemsList/DivisionList/scripts/update.py

update script to https

---

content/1_General/Contributing.mdx

Removed `? might work` in contributing portion of website in install yarn step. 
`npm install -g yarn` command does work as expected. 

removed '?might work' from usaco.guide/general/contributing

---

content/6_Advanced/Lagrange.mdx
content/6_Advanced/Lagrange.problems.json

aliens trick 👽

---

content/5_Plat/Binary_Jump.problems.json
solutions/platinum/bts-hotcold.mdx

Editorial for problem Hot & Cold

---

solutions/platinum/cses-2081.mdx

Closes #4110.
First PR so let me know if I missed a requirement. I ran pre-commit and that's about it since I just replaced some existing code/explanation with other code/explanation.

Fix TLE for CSES - Fixed Length Paths II internal solution

---

src/components/MarkdownLayout/DesktopSidebar.tsx

Revert changes to sidebar

---

content/4_Gold/String_Hashing.mdx

Bug arises when trying to get hash of the entire string: `get_hash(0, s.size())`

Fix string hashing bounds bug

---

content/6_Advanced/LCT.mdx

issue it solves:
https://github.com/cpinitiative/usaco-guide/issues/2897

Update LCT.mdx #2897

---

content/5_Plat/Geo_Pri.mdx
content/5_Plat/Geo_Pri.problems.json

[Editorial] Maximum number of visible points

---

content/6_Advanced/SCC.mdx

better 2sat impl

---

content/5_Plat/Geo_Pri.problems.json
solutions/platinum/leetcode-149.mdx

[Editorial] Max points on a line

---

solutions/gold/cses-1634.mdx

Proofs of AC :
C++ - 
Java - 
Python -

[Refactored] : Update cses 1634 condition and format Python section

---

content/5_Plat/2DRQ.mdx

- added a (in my opinion) cleaner 2d bit impl (which is also more in line w/ the PURS bit impl)
- added a slightly different verison of the offline bit impl
- like the bit impl in the purs module, everything is zero indexed here
- greatly improved the efficiency of the code by passing in the vector for the `ind` function as a reference

Fenwick Tree Updates

---

solutions/silver/usaco-595.mdx

I'm modifying this page [https://usaco.guide/problems/usaco-595-subsequences-summing-to-sevens/solution](https://usaco.guide/problems/usaco-595-subsequences-summing-to-sevens/solution)
Even though Java and Python solutions pass all test cases at [https://usaco.org/index.php?page=viewproblem2&cpid=595](https://usaco.org/index.php?page=viewproblem2&cpid=595), they don't pass my own 2 test cases below.
Reason: the current solutions use 0-indexed when computing the subarray's length. We should use 1-indexed instead.
Suggestion: add these test cases to the USACO original problem.
```
7
7
5
1
6
2
14
10
```
```
7
7
5
1
6
2
14
7
```
- If changes are requested, I will re-request a review …

Fix Java and Python solutions of "Subsequences Summing to Sevens"

---

content/5_Plat/Geo_Pri.mdx

py sol for Polygon Area

---

content/5_Plat/Geo_Pri.mdx

py sol for Polygon Lattice Points

---

solutions/platinum/leetcode-1453.mdx
solutions/platinum/leetcode-149.mdx

AC: https://leetcode.com/problems/maximum-number-of-darts-inside-of-a-circular-dartboard/submissions/1436222954/

py sol for Maximum Number of Darts Inside of a Circular Dartboard

---

solutions/platinum/kattis-maxcolinear.mdx

AC (C++): https://open.kattis.com/submissions/14757865
AC (Py): https://open.kattis.com/submissions/14757862

C++ code rfc / py sol for max collinear

---

content/2_Bronze/Intro_DS.mdx

memset(arr, 1, sizeof) should set vals to 1 and memset(arr, -1, sizeof) will set vals to 2s complement. Textbook was not consistent with this.
- [ X ] I have tested my code.
- [ X ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ X ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
- [ X ] I have linked this PR to any issues that it closes.

Fix typo within memset description

---

content/4_Gold/DSU.mdx

I'm modifying [https://usaco.guide/gold/dsu](https://usaco.guide/gold/dsu)
The java DSU implementation initializes array `sizes` with -1 which is incorrect, should be 1 instead.

Fix java DSU implementation

---

content/6_Advanced/Game_Theory.mdx

In this page was written that MEX-function is maximum excluded, but it's minimum excluded.

updated: fixed "mex" definition

---

solutions/advanced/ac-GameOnTree.mdx

AC: https://atcoder.jp/contests/agc017/submissions/59446662
The solution without `pypyjit` results `MLE` in `Python (PyPy 3.10-v7.3.12)` but it works absolutely fine in `Python (CPython 3.11.4)`.

py sol for Game on Tree

---

solutions/bronze/usaco-1301.mdx

update Watching Mooloo

---

content/3_Silver/Sorting_Custom.mdx

Added a Python solution to the example problem in Sorting_Custom: [Rectangular Pasture](http://www.usaco.org/index.php?page=viewproblem2&cpid=1063)
- The Python solution TLEs even with the correct time complexity (I believe it to be similar if not more optimized than the C++ solution). On a different OJ with PyPy3 (DMOJ), the longest case takes 0.502s.
- I added the exact same note that Java has for lambda with a different link since there is not much to change.
- I'm not 100% sure if I need to add my solution if it's a solution for a problem in the module. That's why box 2 is not checked.
- I understand that if it is clear that I have not attempted to follow these conventions, my PR will be …

Python Sol 1063 content/3_Silver/Sorting_Custom.mdx

---

content/3_Silver/Graph_Traversal.mdx

Adds new Python Solutions to https://cses.fi/problemset/task/1668/ for content/3_Silver/Graph_Traversal.mdx.
Relates to #3444
DFS (missing Python): https://cses.fi/problemset/result/11118878/ (0.74s)
Previous BFS Sol: https://cses.fi/problemset/result/11118911/ (0.90s)
New BFS Sol: https://cses.fi/problemset/result/11118910/ (0.69s)
_Note: Updated/changed the pre-existing Python BFS solution as I had a simpler, faster solution._
---

Update BuildingTeams PySol content/3_Silver/Graph_Traversal.mdx

---

solutions/gold/usaco-696.mdx

HLD solution for Promotion Counting(Platinum)

---

content/5_Plat/Convex_Hull.mdx

Adding new blog for rotating calipers

---

solutions/platinum/cses-1191.mdx

update Cyclic Array

---

solutions/silver/usaco-834.mdx

- added explanation to solution pages

Out of Sorts Editorial

---

solutions/platinum/baltic-15-editor.mdx

The previous solution resulted in `RE` because the range of `max_n` was only taken until `2e5`, when it should be `3e5`, as mentioned in the problem.
AC (C++): https://oj.uz/submission/1127122
AC (PY): https://oj.uz/submission/1127124

update Baltic Editor

---

solutions/silver/cses-1661.mdx

[https://usaco.guide/problems/cses-1661-subarray-sums-ii/solution](https://usaco.guide/problems/cses-1661-subarray-sums-ii/solution
)
STL ordered map data structure used for implementation with N accesses.
Each access takes logn.
Time complexity should be O(N log N), is incorrectly denoted O(N).

CSES Subarray Sums II - Wrong Time Complexity

---

solutions/silver/usaco-1159.mdx

Cpp Solution: Connecting Two Barns

---

content/3_Silver/More_Prefix_Sums.problems.json
solutions/silver/cf-276C.mdx

AC (C++): https://codeforces.com/contest/276/submission/301004525
AC (Python): https://codeforces.com/contest/276/submission/301005093

Little Girl and Maximum Sum Editorial 

---

solutions/silver/usaco-990.mdx

Berry Picking Editorial

---

content/3_Silver/Greedy_Sorting.problems.json
solutions/silver/leetcode-502.mdx

AC (C++): https://leetcode.com/problems/ipo/submissions/1516663992/
AC (Python): https://leetcode.com/problems/ipo/submissions/1516663118/

IPO Editorial

---

solutions/silver/cf-1117C.mdx

- added explanation to internal solution pages (my speciality)

Magic Ship Editorial

---

solutions/bronze/usaco-1276.mdx

Add Java Solution for USACO Problem 1276 - Air Conditioning II

---

solutions/silver/cc-TRPTSTIC.mdx

- added Java solution code to internal solution pages, following comments/variables/structures like the C++ and Python solution codes
AC: [https://www.codechef.com/viewsolution/1137383826](https://www.codechef.com/viewsolution/1137383826)

TripTastic Java Solution

---

content/extraProblems.json
solutions/orphaned/usaco-1498.mdx

ok hopefully adding this to monthlies works

Best Subsequence Editorial

---

solutions/platinum/ioi-11-race.mdx

Returning zero highways does not make sense for this problem. Both original and fixed solutions pass submission tests on oj.uz, probably because there is no test for k=1

Fix solutions/platinum/ioi-11-race.mdx

---

src/components/Groups/ProblemPage/ProblemSubmissionInterface.tsx

Issued Link: https://github.com/cpinitiative/usaco-guide/issues/5094
There was a bug where a user could submit an empty URL and still get points. I fixed this issue by adding an if statement inside the handleSubmitLink function to check if the URL is empty. Now, a user can't submit an empty URL and still gain points.

Fix empty submission url bug

---

src/mdx-plugins/rehype-math.js

…n] isnt a function
In src/mdx-plugins/rehype-math.js, there's a potential issue with math rendering where the code throws a generic error message "unknown tag?" when encountering an unexpected tag. I improved this by throwing this error:
`Error('Unknown tag encountered in rehype-math.js: ' + element.tagName);`
Now, the error message is more descriptive and follows proper conventions by throwing an error. Also, I provided a fallback for when file[fn] isn't a function:
` 
if(typeof file[fn] === 'function') …

Provide more descriptive error message and provide error fallback 

---

src/pages/index.tsx

The image was unnecessarily inverted for dark mode because the `<NonTrivial />` component already accounts for dark mode, making it the same color as the black background.

fix: platinum sponsor logo not visible in dark mode

---

src/README.md
src/components/Editor/EditorPage.tsx
src/pages/editor.tsx
src/utils/lazyLoad.tsx

I implemented lazy loading for heavy components for faster development speed. In the original src/README.md, it says:
"Delete pages/editor.tsx and pages/groups.tsx (or have them return an empty
component). These pages have a lot of dependencies that slow down webpack.
On my personal computer, I have hot reload times of ~1.5 seconds."
It seemed strange to be deleting files and altering the codebase, so I wrapped the editor.tsx and groups.tsx in lazy components to only load them when necessary. The page now …

Lazy loading for faster development speed

---

content/4_Gold/Divisibility.mdx

Corrects a typo in the mathematical notation in phi function where an exponent was written as a subscript.
**Before:** `p_q`
**After:** `p^q`

Fix typo in gold divisibility module

---

solutions/silver/usaco-1062.mdx

- MAX_N is literally never used in Java Sol 2 skull
^ AC with line removed

Cowntagion Java Solution 2
